### ISSUE TITLE
Trying to load a saved game file and wondering if you cuold help?

### ISSUE THREAD

**Issue by bfhaller** [Vhati/ftl-profile-editor#100]
[code]
SavedGame Parser Error

Exception: java.lang.RuntimeException: Not a bool: 2

Stack Trace...
  net.blerf.ftl.parser.Parser.readBool(Parser.java:21)
  net.blerf.ftl.parser.SavedGameParser.readSavedGame(SavedGameParser.java:84)
  net.blerf.ftl.ui.FTLFrame$11.actionPerformed(FTLFrame.java:802)
  javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
  javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)

Editor Version: 25
OS: Mac OS X 10.12.6
VM: Java HotSpot(TM) 64-Bit Server VM, 1.8.0_144, x86_64
[/code]

File ("ae_prof.sav.bak")...
[code]
0900000002000000240000000c0000004143485f534543544f525f3500000000
0c0000004143485f534543544f525f38000000000e0000004143485f554e4c4f
434b5f414c4c00000000090000004143485f5343524150000000000d00000041
43485f4e4f5f44524f4e4553000000000f0000004143485f494e564144455f53
48495000000000150000004143485f554e495445445f46454445524154494f4e
00000000100000004143485f46554c4c5f415253454e414c000000000e000000
4143485f544f5547485f5348495000000000120000004143485f454e45524759
5f534849454c445300000000100000004143485f454e455247595f504f574552
00000000130000004143485f454e455247595f4d414e504f5745520000000013
0000004143485f535445414c54485f44455354524f5900000000110000004143
485f535445414c54485f41564f494400000000140000004143485f535445414c
54485f544143544943414c000000000b0000004143485f524f424f5449430000
00000f0000004143485f4f4e4c595f44524f4e45530000000009000000414348
5f494f4e4544000000000d0000004143485f524f434b5f464952450000000011
0000004143485f524f434b5f4d495353494c455300000000100000004143485f
524f434b5f4352595354414c00000000140000004143485f4d414e5449535f43
5245575f4445414400000000140000004143485f4d414e5449535f534c415547
4854455200000000130000004143485f4d414e5449535f5355525649564f5200
0000000f0000004143485f534c55475f564953494f4e000000000f0000004143
485f534c55475f4e4542554c41000000000c0000004143485f534c55475f4249
4f00000000100000004143485f4645445f50415449454e434500000000110000
004143485f4645445f4449504c4f4d414359000000000f0000004143485f4645
445f5550475241444500000000110000004143485f4352595354414c5f534841
524400000000140000004143485f4352595354414c5f4c4f434b444f574e0000
0000110000004143485f4352595354414c5f434c415348000000001300000041
43485f4c414e4955535f414456414e43454400000000100000004143485f4c41
4e4955535f534352415000000000110000004143485f4c414e4955535f4f5859
47454e0000000001000000010000000100000001000000010000000100000001
0000000100000001000000010000000100000001000000010000000100000001
0000000100000001000000000000000100000000000000000000000000000000
0000000000000005000000070000004272617661697313000000504c41594552
5f534849505f4352595354414c6e080000060000000000000000000000010000
00070000004272617661697313000000504c415945525f534849505f43525953
54414c9707000008000000000000000000000001000000070000004272617661
697313000000504c415945525f534849505f4352595354414c4c070000060000
000000000000000000010000000700000054656b7469746512000000504c4159
45525f534849505f524f434b5f33810600000600000000000000000000000100
0000070000004272617661697313000000504c415945525f534849505f435259
5354414cea05000005000000000000000000000001000000170000000d000000
456e746572707269736520442010000000504c415945525f534849505f484152
44e6010000020000000000000000000000000000000d000000456e7465727072
69736520442010000000504c415945525f534849505f48415244950100000200
00000000000000000000000000000b000000546865204b65737472656c100000
00504c415945525f534849505f48415244780100000200000000000000000000
00000000000b000000546865204b65737472656c10000000504c415945525f53
4849505f484152446a0100000200000000000000000000000000000006000000
53696d6f2d4815000000504c415945525f534849505f535445414c54485f333b
000000010000000000000000000000010000000c00000054686520426173696c
69736b14000000504c415945525f534849505f4d414e5449535f321400000001
0000000000000000000000010000000a000000546865204f73707265790f0000
00504c415945525f534849505f464544f7040000040000000000000000000000
010000000a000000546865204f73707265790f000000504c415945525f534849
505f4645444f020000030000000000000000000000010000000a000000546865
204f73707265790f000000504c415945525f534849505f4645440a0000000100
00000000000000000000010000000a0000004d616e206f662057617211000000
504c415945525f534849505f4a454c4c59280000000100000000000000000000
00010000000a0000004d616e206f662057617211000000504c415945525f5348
49505f4a454c4c590a0000000100000000000000000000000100000007000000
54656b7469746512000000504c415945525f534849505f524f434b5f33810600
00060000000000000000000000010000000700000054656b7469746512000000
504c415945525f534849505f524f434b5f33cb02000003000000000000000000
0000010000000700000054656b7469746512000000504c415945525f53484950
5f524f434b5f3302020000030000000000000000000000010000000700000054
656b7469746512000000504c415945525f534849505f524f434b5f3386000000
0100000000000000000000000100000007000000427261766169731300000050
4c415945525f534849505f4352595354414c6e08000006000000000000000000
000001000000070000004272617661697313000000504c415945525f53484950
5f4352595354414c970700000800000000000000000000000100000007000000
4272617661697313000000504c415945525f534849505f4352595354414c4c07
0000060000000000000000000000010000000700000042726176616973130000
00504c415945525f534849505f4352595354414cea0500000500000000000000
0000000001000000090000004361726e656c69616e15000000504c415945525f
534849505f4352595354414c5f32b50200000300000000000000000000000100
0000090000004361726e656c69616e15000000504c415945525f534849505f43
52595354414c5f32be0000000100000000000000000000000100000009000000
4361726e656c69616e15000000504c415945525f534849505f4352595354414c
5f322a000000010000000000000000000000010000000a000000546865205368
72696b6517000000504c415945525f534849505f414e4145524f4249435f3280
010000020000000000000000000000010000000f0000001201000046000000d7
04000090040000123c00000a0000001101000039000000000000001700000007
0000004d6f6e7376696b070000006372797374616c0100000007000000080000
0046656c6963697479070000006372797374616c000000007200000008000000
56616c65726979610500000068756d616e010000004400000005000000546f6d
6173070000006372797374616c01000000020000000400000057696c6c070000
006372797374616c01000000
[/code]

**Comment by Malanius** [comment]
Hello,
you're trying to open "ae_prof.sav.bak", which is a backup of the profile file. Profile file contains achievements and scores.
If you want to edit saved game, you have to open "continue.sav" file.

Please also note, that .bak files are created by the editor as a backup in case something goes wrong during the edit, do not modify those, or you might lose your progress backup.
