### ISSUE TITLE
Profile Parser Error

### ISSUE THREAD

**Issue by Inziel** [Vhati/ftl-profile-editor#101]
[code]
Profile Parser Error

Exception: java.lang.RuntimeException: Expected string length (19) would extend beyond the end of the stream, from current position (597)

Stack Trace...
  net.blerf.ftl.parser.Parser.readString(Parser.java:78)
  net.blerf.ftl.parser.ProfileParser.readAchievements(ProfileParser.java:127)
  net.blerf.ftl.parser.ProfileParser.readProfile(ProfileParser.java:82)
  net.blerf.ftl.ui.FTLFrame$4.actionPerformed(FTLFrame.java:403)
  javax.swing.AbstractButton.fireActionPerformed(Unknown Source)

Editor Version: 25
OS: Windows 10 10.0
VM: Java HotSpot(TM) 64-Bit Server VM, 1.8.0_144, amd64
[/code]

File ("ae_prof.sav")...
[code]
09000000020000002e0000000c0000004143485f534543544f525f3501000000
0c0000004143485f534543544f525f38000000000c0000004143485f57494e5f
4541535900000000090000004143485f53435241500000000009000000414348
5f5348495053000000000f0000004143485f4e4f5f5550475241444553000000
000d0000004143485f4e4f5f524550414952010000000f0000004143485f4e4f
5f4d495353494c4553000000000d0000004143485f4e4f5f44524f4e45530000
00000c0000004143485f4e4f5f4445415448000000000f0000004143485f494e
564144455f53484950000000000e0000004143485f534c4943455f4449434500
0000000d0000004143485f535546464f4341544500000000150000004143485f
554e495445445f46454445524154494f4e00000000100000004143485f46554c
4c5f415253454e414c000000000e0000004143485f544f5547485f5348495000
000000120000004143485f454e455247595f534849454c445300000000100000
004143485f454e455247595f504f57455200000000130000004143485f454e45
5247595f4d414e504f574552000000000b0000004143485f524f424f54494300
0000000f0000004143485f4f4e4c595f44524f4e455300000000090000004143
485f494f4e4544000000000d0000004143485f524f434b5f4649524500000000
110000004143485f524f434b5f4d495353494c45530000000014000000414348
5f4d414e5449535f435245575f4445414400000000140000004143485f4d414e
5449535f534c415547485445520000000013000000
[/code]

**Comment by Vhati** [comment]
That profile appears to be corrupt. It's truncated. You'll need to delete it, I'm afraid.

If there's an "ae_prof.sav.bak" file in the same folder, you can copy/rename it to recover your progress. Failing that, you can use the editor to recreate your achievements as best you can remember.

Can you provide any details about what led up to this?

**Comment by Vhati** [comment]
FTL repeatedly overwrites files while in a campaign.
Maybe it hadn't finished writing at the moment the editor tried to read your profile?

For future reference:
* Quitting FTL before editing is safest.
* Saved games can be edited while at the main menu (since FTL 1.5.4).
