### ISSUE TITLE
SavedGame Parser Error

### ISSUE THREAD

**Issue by Helminsted** [Vhati/ftl-profile-editor#102]
So I tired to post the right thing but the site wont let me show you the necessary bit for you to help but lets see what we can do! when I tried to use the profile editor it said it couldn't interpret the file correctly. I can't post the part that I'm suppose to because the site here wont let me says it has too many characters. hopefully I can post this with a file that shows the information.
[the information.txt](https://github.com/Vhati/ftl-profile-editor/files/1446023/the.information.txt)

**Comment by Malanius** [comment]
Hello,
according to the attached log, you're trying to open "data.dat" file, which is the data file of the game.
To edit the save game, open "continue.sav",
to edit the profile, open "prof.sav" or "ae_prof.sav" (if you're using Advanced edition of the game).
I hope it helps.
