### ISSUE TITLE
Problem with the new version of FTL

### ISSUE THREAD

**Issue by BluTree** [Vhati/ftl-profile-editor#104]
Hello, I have a problem with ftl profile editor.
If you didn't know, the beta 1.6.1 is available to download (via steam properties). This change the location of the resources. They were in resources\data.dat and same for resource.dat but now there is only one big ftl.dat where there are resource and data.
So, when I try to launch ftl profile editor, a window appear telling me to find the path to data.dat but there isn't any data.dat so I cant launch ftl profile editor.

**Comment by Vhati** [comment]
I'm on it, thanks!
There is no immediate workaround.
The editor and mod manager will each require an update in order to support FTL 1.6.1.

[Thread](http://subsetgames.com/forum/viewtopic.php?f=12&t=32518): FTL Mod Dev Forum - Big FTL changes are coming!

**Comment by Vhati** [comment]
Fixed in v27.
FTL 1.6.1-1.6.2 is supported.
