### ISSUE TITLE
Profile Parser Error

### ISSUE THREAD

**Issue by FTLUser1783** [Vhati/ftl-profile-editor#106]
[code]
Profile Parser Error

Exception: java.lang.RuntimeException: End of stream reached before reading enough bytes for an int

Stack Trace...
  net.blerf.ftl.parser.Parser.readInt(Parser.java:43)
  net.blerf.ftl.parser.Parser.readBool(Parser.java:18)
  net.blerf.ftl.parser.ProfileParser.readShipUnlocks(ProfileParser.java:317)
  net.blerf.ftl.parser.ProfileParser.readProfile(ProfileParser.java:84)
  net.blerf.ftl.ui.FTLFrame$4.actionPerformed(FTLFrame.java:403)

Editor Version: 25
OS: Windows 10 10.0
VM: Java HotSpot(TM) Client VM, 1.8.0_151, x86
[/code]

File ("ae_prof.sav")...
[code]
0900000002000000140000000c0000004143485f534543544f525f3501000000
0c0000004143485f534543544f525f38010000000c0000004143485f57494e5f
4541535900000000090000004143485f5343524150000000000d000000414348
5f4e4f5f524550414952000000000f0000004143485f4e4f5f4d495353494c45
53000000000d0000004143485f4e4f5f44524f4e4553010000000c0000004143
485f4e4f5f444541544801000000150000004143485f554e495445445f464544
45524154494f4e00000000100000004143485f46554c4c5f415253454e414c00
0000000e0000004143485f544f5547485f534849500000000012000000414348
5f454e455247595f534849454c445301000000100000004143485f524f434b5f
4352595354414c01000000100000004143485f4645445f50415449454e434500
000000110000004143485f4352595354414c5f53484152440100000014000000
4143485f4352595354414c5f4c4f434b444f574e0100000017000000504c4159
45525f534849505f4645445f564943544f52590000000000000000ffffffffff
ffffff15000000504c415945525f534849505f4645445f515545535400000000
16000000504c415945525f534849505f524f434b5f5155455354010000001900
0000504c415945525f534849505f4352595354414c5f51554553540100000001
0000000100000000000000000000000000000000000000010000000000000001
0000000000000000000000000000000100000000000000010000000000000001
0000000000000001000000000000000000000000000000
[/code]

**Comment by Vhati** [comment]
That profile was corrupted, truncated somehow.
Can you describe the circumstances or recreate the problem?

If the editor glitched during its last save, look for "ae_prof.sav.bak" in the same folder, and rename it to "ae_prof.sav". That might recover everything.

**Comment by Vhati** [comment]
FTL repeatedly overwrites files while in a campaign.
Maybe it hadn't finished writing at the moment the editor tried to read your profile?

For future reference:
* Quitting FTL before editing is safest.
* Saved games can be edited while at the main menu (since FTL 1.5.4).
