### ISSUE TITLE
SavedGame Parser Error

### ISSUE THREAD

**Issue by FTLUser1783** [Vhati/ftl-profile-editor#107]
[code]
SavedGame Parser Error

Exception: java.lang.RuntimeException: End of stream reached before reading enough bytes for an int

Stack Trace...
  net.blerf.ftl.parser.Parser.readInt(Parser.java:43)
  net.blerf.ftl.parser.SavedGameParser.readCrewMember(SavedGameParser.java:919)
  net.blerf.ftl.parser.SavedGameParser.readShip(SavedGameParser.java:453)
  net.blerf.ftl.parser.SavedGameParser.readSavedGame(SavedGameParser.java:129)
  net.blerf.ftl.ui.FTLFrame$11.actionPerformed(FTLFrame.java:802)

Editor Version: 25
OS: Windows 10 10.0
VM: Java HotSpot(TM) Client VM, 1.8.0_151, x86
[/code]

File ("continue.sav")...
[code]
090000000100000001000000150000003a000000ad0200000800000008000000
5265642d5461696c12000000504c415945525f534849505f484152445f320600
0000000000000f0000000a000000626c75655f616c69656e0100000009000000
646561645f63726577040000000e00000064657374726f7965645f726f636b01
0000000a000000656e765f64616e676572020000000a00000066697265645f73
686f748201000006000000686967686f32010000000b0000006b696c6c65645f
637265771f000000090000006c6f73745f6372657702000000060000006e6562
756c61040000000f00000072656163746f725f75706772616465080000000e00
000073746f72655f7075726368617365100000000c00000073746f72655f7265
70616972030000000e00000073797374656d5f75706772616465070000000a00
000074656c65706f727465640b0000000e000000776561706f6e5f7570677261
64650100000012000000504c415945525f534849505f484152445f3208000000
5265642d5461696c090000006b65737472616c5f32040000000500000068756d
616e040000004a6f656c0500000068756d616e070000004d756c6c6574740600
0000656e65726779050000004169736861060000006d616e7469730600000053
6f7068696101000000084c01000000000000000000090000000b000000170000
00160000003100000007000000040000004a6f656c0500000068756d616e0000
0000640000007a0000007a00000002000000010000000100000000000000ffff
ffff020000000000000002000000000000000100000002000000060000000000
0000110000000000000003000000010000000100000003000000010000000c00
00003a000000000000000000000000000000ffffffffe8030000000000004b00
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000
[/code]

**Comment by Vhati** [comment]
That saved game was corrupted, truncated somehow.
Can you describe the circumstances or recreate the problem?

If you saved during combat, there is a known bug in v25 during saving - it prints an error in the log and truncates when asteroids or certain projectiles are present. Immediate workaround for that is to save when things are calm, until v26 comes out to fix it. The next attempt at opening said file would hit the "end of stream" prematurely.

If the editor glitched during its last save, look for "continue.sav.bak" in the same folder, and rename it to "continue.sav". That might recover everything.

**Comment by Vhati** [comment]
The projectile bug has been fixed in v26.
