### ISSUE TITLE
Profile read error on FTL 1.6.9

### ISSUE THREAD

**Issue by Arusekk** [Vhati/ftl-profile-editor#116]
[code]
Profile Read Error

Editor Version: 28
OS: Linux 4.19.72-gentoo
VM: OpenJDK 64-Bit Server VM, 1.8.0_222, amd64
[/code]

File ("ae_prof.sav")...
[code]
0900000002000000170000000c0000004143485f534543544f525f3500000000
0c0000004143485f534543544f525f38000000000c0000004143485f57494e5f
4541535900000000090000004143485f5343524150000000000f000000414348
5f4e4f5f4d495353494c4553000000000d0000004143485f4e4f5f44524f4e45
53000000000c0000004143485f4e4f5f4445415448000000000e000000414348
5f534c4943455f44494345000000000d0000004143485f535546464f43415445
00000000150000004143485f554e495445445f46454445524154494f4e000000
00100000004143485f46554c4c5f415253454e414c0000000012000000414348
5f454e455247595f534849454c445300000000130000004143485f454e455247
595f4d414e504f574552000000000b0000004143485f524f424f544943000000
000f0000004143485f4f4e4c595f44524f4e455300000000090000004143485f
494f4e454400000000140000004143485f4d414e5449535f534c415547485445
5200000000100000004143485f4645445f50415449454e4345000000000f0000
004143485f4645445f555047524144450000000018000000504c415945525f53
4849505f484152445f564943544f52590000000000000000ffffffffffffffff
1a000000504c415945525f534849505f434952434c455f564943544f52590000
0000ffffffffffffffff0000000017000000504c415945525f534849505f4645
445f564943544f52590000000000000000ffffffffffffffff1a000000504c41
5945525f534849505f454e455247595f564943544f52590000000000000000ff
ffffffffffffff01000000010000000000000000000000010000000000000001
0000000100000001000000000000000000000000000000000000000000000001
0000000000000000000000000000000100000000000000000000000000000000
0000000000000005000000090000004a617374727ac4856210000000504c4159
45525f534849505f48415244060f000008000000010000000000000001000000
0a000000437a776f726f6bc4857414000000504c415945525f534849505f4349
52434c455f33f20e000008000000010000000000000001000000090000005279
626fc582c3b3770f000000504c415945525f534849505f464544ef0e00000800
0000010000000000000001000000070000004172626974657212000000504c41
5945525f534849505f454e45524759040d000008000000010000000000000001
0000000a0000004d79737a6fc582c3b37712000000504c415945525f53484950
5f484152445f326b0c0000080000000000000000000000010000000f00000009
0000004a617374727ac4856210000000504c415945525f534849505f48415244
060f000008000000010000000000000001000000090000004a617374727ac485
6210000000504c415945525f534849505f484152448809000008000000000000
000000000000000000090000004a617374727ac4856210000000504c41594552
5f534849505f4841524405080000070000000000000000000000000000000a00
00004d79737a6fc582c3b37712000000504c415945525f534849505f48415244
5f326b0c00000800000000000000000000000100000005000000546f72757312
000000504c415945525f534849505f434952434c45500c000008000000000000
00000000000100000005000000546f72757312000000504c415945525f534849
505f434952434c45b90700000600000000000000000000000100000005000000
546f72757312000000504c415945525f534849505f434952434c45f803000004
00000000000000000000000000000005000000546f72757312000000504c4159
45525f534849505f434952434c456e0100000200000000000000000000000100
00000300000057697214000000504c415945525f534849505f434952434c455f
32e10a0000080000000000000000000000010000000300000057697214000000
504c415945525f534849505f434952434c455f32780500000500000000000000
00000000010000000300000057697214000000504c415945525f534849505f43
4952434c455f325c050000040000000000000000000000010000000a00000043
7a776f726f6bc4857414000000504c415945525f534849505f434952434c455f
33f20e000008000000010000000000000001000000090000005279626fc582c3
b3770f000000504c415945525f534849505f464544ef0e000008000000010000
000000000001000000070000004172626974657212000000504c415945525f53
4849505f454e45524759040d0000080000000100000000000000010000000700
00004e6f657468657214000000504c415945525f534849505f454e455247595f
3214000000010000000000000000000000010000002d0000004f010000620000
0037040000af0800006e4a00000b0000007f0000001200000004000000280000
000900000046726564657269636b04000000656e6769010000001a0000000300
00005a6173060000006d616e746973010000000a010000040000004a6f736505
00000068756d616e010000006a000000050000004e6f656d690500000068756d
616e00000000040000000900000046726564657269636b04000000656e676901
000000
[/code]

Also worth noting, I use a localized profile with unicode strings in character/ship names

**Comment by Vhati** [comment]
> I use a localized profile with unicode strings in character/ship names

I see. Interesting. I didn't realize FTL supported that.

The editor was warning that if you save, those characters will become question marks. You'll also notice that if you dismiss the warning and look in the "General Stats" or "Ship Stats" tab, the editor is not displaying those names correctly 

I did a save and compared bytes before & after. Functionally, you won't break anything in the game by using the editor, but those characters will be replaced, which I imagine would be irksome for you. Sorry about that.

**Comment by Vhati** [comment]
FTL has historically only accepted a few limited ANSI accents (ANSI extended ASCII a bit).

But your profile clearly contains unicode, such as
The 'a' in  "Jastrząb" and "Czworokąt".
The 'l' and second 'o' in "Rybołów" and "Myszołów".

I'll make a note. Thanks for bringing this to my attention!

**Comment by Vhati** [comment]
/Checks my modder readme for Slipstream Mod Manager...

> FTL 1.01-1.5.13 assumes text to be windows-1252 [ANSI]
> Since FTL 1.6.1, it assumes UTF-8

Looks like I forgot to update the profile parser when that happened.

**Comment by Vhati** [comment]
Fixed in commit 6f4c28609a90fec7249075c02f9405d2e13f016c
