### ISSUE TITLE
savedgame parser error

### ISSUE THREAD

**Issue by lordsosa** [Vhati/ftl-profile-editor#64]
[code]
SavedGame Parser Error

Exception: java.io.IOException: Unsupported room station direction flag: null

Stack Trace...
  net.blerf.ftl.parser.SavedGameParser.readRoom(SavedGameParser.java:1088)
  net.blerf.ftl.parser.SavedGameParser.readShip(SavedGameParser.java:565)
  net.blerf.ftl.parser.SavedGameParser.readSavedGame(SavedGameParser.java:129)
  net.blerf.ftl.ui.FTLFrame$11.actionPerformed(FTLFrame.java:778)
  javax.swing.AbstractButton.fireActionPerformed(Unknown Source)

Editor Version: 24
OS: Windows 8.1 6.3
VM: Java HotSpot(TM) Client VM, 1.7.0_67, x86
[/code]

File ("continue.sav")...
[code]
09000000000000000000000000000000010000008c000000040000000b000000
546865204b65737472656c10000000504c415945525f534849505f4841524401
000000000000000000000010000000504c415945525f534849505f484152440b
000000546865204b65737472656c070000006b65737472616c03000000050000
0068756d616e0d0000004c6f67616e204a6f686e736f6e0500000068756d616e
040000004b6172610500000068756d616e0b0000004a61636b20536869726169
01000000084c010000000000000000001e0000001a000000140000000d000000
aa000000040000000d0000004c6f67616e204a6f686e736f6e0500000068756d
616e0000000064000000fb0100009d0000000000000000000000010000000000
0000ffffffff0200000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000001000000000000000000
00000000000000000000000000000000000000000000ffffffffe80300000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000010000000000
00000000000000000000e8030000000000000000000000000000040000004b61
72610500000068756d616e000000006400000034000000c00000000e00000002
0000000100000000000000ffffffff0200000000000000010000000000000002
0000000e00000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000ff
ffffffe803000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
00000001000000000000000000000000000000e8030000000000000000000000
0000000b0000004a61636b205368697261690500000068756d616e0000000064
000000c00000009d0000000a000000010000000100000000000000ffffffff02
000000000000000200000000000000010000000a000000000000000000000000
0000000000000000000000000000000100000000000000000000000000000000
000000000000000000000000000000ffffffffe8030000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000001000000000000000000000000
000000e80300000000000000000000000000000b0000004a61736f6e20426f76
65650500000068756d616e000000006400000029010000c00000000500000000
0000000100000000000000ffffffff02000000000000000000000000000000ff
ffffffffffffff00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000ff
ffffffe803000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
00000001000000000000000000000000000000e8030000000000000000000000
0000000800000002000000020000000000000000000000000000000000000000
000000000000000000000000000000e803000000000000010000000200000002
0000000000000000000000000000000000000000000000000000000000000000
000000e803000000000000010000000100000001000000000000000000000000
0000000000000000000000000000000000000000000000e80300000000000001
0000000300000002000000000000000000000000000000000000000000000000
0000000000000000000000e80300000000000001000000040000000000000000
00000000000000000000000000000000000000000000000000000000000000e8
0300000000000001000000010000000100000000000000000000000000000000
00000000000000000000000000000000000000e8030000000000000100000001
0000000100000000000000000000000000000000000000000000000000000000
00000000000000e8030000000000000100000001000000010000000000000000
000000000000000000000000000000000000000000000000000000e803000000
0000000100000001000000010000000000000000000000000000000000000000
000000000000000000000000000000e803000000000000010000000000000000
0000000000000000000000000000000000000000000000010000000000000000
00000000000000000000000000000001000000e8030000000000000000000000
00000000000000640000000000000000000000ffffffff0000000000000000ff
ffffff0000000001000000640000000000000000000000ffffffff0000000000
000000ffffffff0000000000000000ffffffff0000000000000000ffffffffff
ffffff04000000640000000000000000000000ffffffff0000000000000000ff
ffffff00000000ffffffff640000000000000000000000ffffffff0000000000
000000ffffffff00000000ffffffff640000000000000000000000ffffffff00
00000000000000ffffffff0000000000000000ffffffff0000000000000000ff
ffffffffffffff04000000640000000000000000000000ffffffff0000000000
000000ffffffff0000000000000000ffffffff0000000000000000ffffffff00
00000003000000640000000000000000000000ffffffff0000000000000000ff
ffffffffffffff04000000640000000000000000000000ffffffff0000000000
000000ffffffff0000000000000000ffffffff0000000000000000ffffffffff
ffffff04000000640000000000000000000000ffffffff0000000000000000ff
ffffff0000000000000000ffffffff0000000000000000ffffffffffffffff04
000000640000000000000000000000ffffffff0000000000000000ffffffffff
ffffff04000000640000000000000000000000ffffffff0000000000000000ff
ffffff0000000000000000ffffffff0000000000000000ffffffff0100000002
000000640000000000000000000000ffffffff0000000000000000ffffffffff
ffffff04000000640000000000000000000000ffffffff0000000000000000ff
ffffffffffffff04000000640000000000000000000000ffffffff0000000000
000000ffffffffffffffff04000000640000000000000000000000ffffffff00
00000000000000ffffffff0000000000000000ffffffff0000000000000000ff
ffffff0200000000000000640000000000000000000000ffffffff0000000000
000000ffffffffffffffff04000000640000000000000000000000ffffffff00
00000000000000ffffffffffffffff0400000000000000040000000400000004
0000000000000000000000000000000000000004000000040000000400000000
0000000000000000000000000000000400000004000000040000000000000000
0000000000000000000000040000000400000004000000000000000000000000
0000000000000004000000040000000400000000000000000000000000000000
0000000400000004000000040000000000000000000000000000000000000004
0000000400000004000000000000000000000000000000000000000400000004
0000000400000000000000000000000000000000000000040000000400000004
0000000000000000000000000000000000000004000000040000000400000000
0000000000000000000000000000000400000004000000040000000000000000
0000000000000000000000040000000400000004000000000000000000000000
0000000000000004000000040000000400000000000000000000000000000000
0000000400000004000000040000000000000000000000000000000000000004
0000000400000004000000000000000000000000000000000000000400000004
0000000400000000000000000000000000000000000000040000000400000004
0000000000000000000000000000000000000004000000040000000400000000
0000000000000000000000000000000400000004000000040000000000000000
0000000000000000000000040000000400000004000000000000000000000000
0000000000000004000000040000000400000000000000000000000000000000
0000000400000004000000040000000000000000000000000000000000000004
0000000400000004000000000000000000000000000000000000000400000004
0000000400000000000000000000000000000000000000040000000400000004
0000000000000000000000000000000000000004000000040000000400000000
0000000000000000000000000000000000000000000000020000000d0000004c
415345525f42555253545f3301000000110000004d495353494c45535f325f50
4c4159455200000000020000000f00000044455f44524f4e455f48554c4c5f31
0000000000000000ffffffffffffffffffffffffffffffff010000000f000000
44455f44524f4e455f48554c4c5f320000000000000000ffffffffffffffffff
ffffffffffffff010000000000000000000000e0100000a33b000041fcffffb0
0000009cffffff0000000000000000ffffffff00000000000000000000000000
0000000000000000000000000000001200000001000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
00000017000000010000001a00000073746172732f62675f6c6f6e656c795265
64537461722e706e671600000073746172732f706c616e65745f62726f776e2e
706e671d01000083000000b40000000100000000000000000000000000000000
0000000000000001000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000100000000000000000000000000000000
0000000000000001000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000ff
ffffff0300000000000000000000000000000000000000000000000000000000
0000000200000000000000000000000000000000000000000000000000000000
0000000000000000000000ffffffff0000008000000080000000800000008018
fcffff18fcffff00000080000000800000008000000080000000800000008018
fcffff00000000e8030000e8f701000000000000000000ffffff7f0000000000
0000000000000018fcffff000000000000000000000000000000000000000000
00000000000000e803000000000000000000000000000000000000e803000000
0000800000008000000000000000000000000000000000ffffffff0000008000
000080000000800000008018fcffff18fcffff00000080000000800000008000
000080000000800000008018fcffff00000000e8030000581501000000000000
000000ffffff7f00000000000000000000000018fcffff000000000000000000
00000000000000000000000000000000000000e8030000000000000000000000
00000000000000e8030000fdffffffeeffffff020000001e1900002f2a000000
00000000000000000000000000000000000000000000000000000000000000ff
ffffff010000000000000002000000a6000000e80300000000000000000000e8
0300000000000000000000ffffffff00000000000000000000000000000000e8
03000018fcffff18fcffffffffffff0000000000000000ab2600000000000000
000000000000000000000000000000000000000000000000000000ffffffff01
000000000000000000000000000000e803000000000000000000000000000000
00000000000000ffffffff00000000000000000000000000000000e803000018
fcffff18fcffffffffffff000000000000000000000000000000000000000001
000000307500000000000000000000
[/code]

**Comment by Vhati** [comment]
Was that created while a mod was applied, then later opened in the editor when the mod was no longer present?
