### ISSUE TITLE
Save could not be parsed. Something about a bool.

### ISSUE THREAD

**Issue by filipecatraia** [Vhati/ftl-profile-editor#65]
[code]
Profile Parser Error

Exception: java.lang.RuntimeException: Not a bool: 16

Stack Trace...
  net.blerf.ftl.parser.Parser.readBool(Parser.java:21)
  net.blerf.ftl.parser.ProfileParser.readShipUnlocks(ProfileParser.java:266)
  net.blerf.ftl.parser.ProfileParser.readProfile(ProfileParser.java:49)
  net.blerf.ftl.ui.FTLFrame$4.actionPerformed(FTLFrame.java:379)
  javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)

Editor Version: 24
OS: Mac OS X 10.10.3
VM: Java HotSpot(TM) 64-Bit Server VM, 1.8.0_45, x86_64
[/code]

File ("continue.sav")...
[code]
0900000000000000000000001000000026000000a2020000060000000a000000
546865204f73707265790f000000504c415945525f534849505f464544030000
00000000000e0000000a000000626c75655f616c69656e010000000900000064
6561645f63726577010000000a000000656e765f64616e676572020000000a00
000066697265645f73686f74c500000006000000686967686f32010000000b00
00006b696c6c65645f637265770b000000090000006c6f73745f637265770100
00000f00000072656163746f725f75706772616465010000000e00000073746f
72655f7075726368617365290000000c00000073746f72655f72657061697202
0000000f000000737566666f63617465645f637265770f0700000e0000007379
7374656d5f757067726164650a0000000a00000074656c65706f727465640400
00000e000000776561706f6e5f75706772616465010000000f000000504c4159
45525f534849505f4645440a000000546865204f73707265790b000000666564
5f63727569736572040000000500000068756d616e0a0000004a656666204261
617273060000006d616e74697308000000566976696d6f726404000000726f63
6b080000004c6973616e64726104000000656e67690400000054616368010000
00084c010000000000000000001e00000018000000320000003a000000214600
00080000000a0000004a6566662042616172730500000068756d616e00000000
2b0000009d0000009d00000004000000000000000100000000000000ffffffff
0200000000000000030000000000000000000000040000001a00000000000000
000000000000000001000000010000000100000001000000010000001c000000
25000000000000000000000000000000ffffffffe8030000000000001f000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000010000000000000000000000
00000000e803000000000000000000000000000008000000566976696d6f7264
060000006d616e746973000000005700000057000000c0000000030000000200
00000100000000000000ffffffff010000000200000000000000020000000300
0000000000001e00000000000000000000000200000001000000010000000200
0000010000000000000025000000000000000000000000000000ffffffffe803
0000000000001f00000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000100
0000000000000000000000000000e80300000000000000000000000000000800
00004c6973616e64726104000000726f636b0000000096000000fb0100007a00
00000f000000010000000100000000000000ffffffff01000000030000000000
0000010000000f00000000000000000000000000000082000000000000000000
0000000000000000000000000000000000002500000000000000000000000000
0000ffffffffe8030000000000001f0000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
00000000000001000000000000000000000000000000e8030000000000000000
000000000000040000005461636804000000656e676900000000640000002901
00009d0000000b000000000000000100000000000000ffffffff000000000000
0000000000000b00000000000000000000006e00000000000000010000000000
0000010000000100000000000000000000002500000000000000000000000000
0000ffffffffe8030000000000001f0000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
00000000000001000000000000000000000000000000e8030000000000000000
000000000000070000004d7220427567610500000068756d616e000000006400
0000b50100009d0000000d000000010000000100000000000000ffffffff0200
0000000000000000000000000000ffffffffffffffff00000000000000000000
0000000000000000000000000000010000000000000000000000000000001c00
0000000000000000000000000000ffffffffe8030000000000001f0000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000100000000000000000000000000
0000e80300000000000000000000000000000b0000004a61636b205368697261
69060000006d616e7469730000000064000000e30000009d0000000a00000000
000000010000000000000000000000010000000200000000000000020000000a
0000000000000000000000000000000000000000000000030000000100000000
00000003000000000000001b00000000000000000000000000000000000000e8
030000000000001f000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000e803000018fcffff18fcffff0100000007
00000053746172676572070000006372797374616c000000007d000000c00000
007a000000080000000000000001000000000000000000000001000000010000
0000000000000000000a00000000000000000000000000000000000000000000
0000000000000000000000000000000000000000001b00000000000000000000
000000000000000000e8030000000000001f0000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
00000000000000000001000000000000000000000000000000e803000018fcff
ff18fcffff000000000000000000000000000000000700000047726f7a6f6c79
04000000726f636b00000000960000009d000000c00000000400000001000000
0100000000000000ffffffff010000000000000000000000ffffffffffffffff
0000000000000000000000000000000000000000000000000100000000000000
000000000000000004000000000000000000000000000000ffffffffe8030000
000000001f000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000e803000000000000000000000100000019000000
0800000008000000000000000000000000000000000000000000000000000000
0000000000000000e80300000000000001000000080000000800000000000000
00000000000000000000000000000000000000000000000000000000e8030000
0000000001000000030000000100000000000000000000000000000000000000
00000000000000000000000000000000e8030000000000000100000008000000
0400000000000000000000000000000000000000000000000000000000000000
00000000e8030000000000000100000000000000030000000000000000000000
00000000000000000000000000000000000000000000000000000000e8030000
0000000001000000030000000300000000000000000000000000000000000000
00000000000000000000000000000000e8030000000000000100000003000000
0300000000000000000000000000000000000000000000000000000000000000
00000000e8030000000000000100000003000000030000000000000000000000
000000000000000000000000000000000000000000000000e803000000000000
0100000001000000000000000000000000000000120000000000000000000000
000000000000000000000000e803000000000000010000000000000004000000
0400000000000000000000000000000000000000000000000000000000000000
00000000e8030000000000000100000000000000000000000000000000000000
04000000000000000000000000000000000000000000000001000000e8030000
0000000000000000ced6000039070600640000000000000000000000ffffffff
0000000000000000ffffffffffffffff04000000640000000000000000000000
ffffffff0000000000000000ffffffffffffffff040000006400000000000000
00000000ffffffff0000000000000000ffffffffffffffff0400000064000000
0000000000000000ffffffff0000000000000000ffffffff0000000000000000
ffffffff0000000000000000ffffffff02000000000000006400000000000000
00000000ffffffff0000000000000000ffffffff000000000100000064000000
0000000000000000ffffffff0000000000000000ffffffffffffffff04000000
640000000000000000000000ffffffff0000000000000000ffffffffffffffff
04000000640000000000000000000000ffffffff0000000000000000ffffffff
ffffffff04000000640000000000000000000000ffffffff0000000000000000
ffffffff0000000001000000640000000000000000000000ffffffff00000000
00000000ffffffffffffffff04000000640000000000000000000000ffffffff
0000000000000000ffffffff0000000000000000ffffffff0000000000000000
ffffffffffffffff04000000640000000000000000000000ffffffff00000000
00000000ffffffff0000000000000000ffffffff0000000000000000ffffffff
0000000003000000640000000000000000000000ffffffff0000000000000000
ffffffffffffffff04000000640000000000000000000000ffffffff00000000
00000000ffffffff0100000000000000640000000000000000000000ffffffff
0000000000000000ffffffffffffffff04000000640000000000000000000000
ffffffff0000000000000000ffffffff0000000000000000ffffffff00000000
00000000ffffffff0100000002000000640000000000000000000000ffffffff
0000000000000000ffffffff0000000000000000ffffffff0000000000000000
ffffffffffffffff04000000640000000000000000000000ffffffff00000000
00000000ffffffffffffffff0400000000000000140000001400000014000000
0000000000000000030000000000000014000000140000001400000000000000
0000000003000000000000001400000014000000140000000000000000000000
0300000000000000140000001400000014000000000000000000000003000000
0000000014000000140000001400000000000000000000000300000000000000
1400000014000000140000000000000000000000030000000000000014000000
1400000014000000000000000000000003000000000000001400000014000000
1400000000000000000000000300000000000000140000001400000014000000
0000000000000000030000000000000014000000140000001400000000000000
0000000003000000000000001400000014000000140000000000000000000000
0300000000000000140000001400000014000000000000000000000003000000
0000000014000000140000001400000000000000000000000300000000000000
1400000014000000140000000000000000000000030000000000000014000000
1400000014000000000000000000000003000000000000001400000014000000
1400000000000000000000000300000000000000140000001400000014000000
0000000000000000030000000000000014000000140000001400000000000000
0000000003000000000000001400000014000000140000000000000000000000
0300000000000000140000001400000014000000000000000000000003000000
0000000014000000140000001400000000000000000000000300000000000000
1400000014000000140000000000000000000000030000000000000014000000
1400000014000000000000000000000003000000000000001400000014000000
1400000000000000000000000300000000000000140000001400000014000000
0000000000000000030000000000000014000000140000001400000000000000
0000000003000000000000000000000000000000040000000d0000004c415345
525f42555253545f33010000000f0000004c415345525f42555253545f325f41
010000000c0000004c415345525f48554c4c5f31000000000a0000004d495353
494c45535f330000000000000000020000000d0000004155544f5f434f4f4c44
4f574e0e00000044524f4e455f5245434f564552590000000001c37e497ce60d
0b81fcffff590000000000000003000000000000008e62147500000000000000
0000000000000000000000000000000000000000001400000001000000000000
0001000000000000000000000000000000010000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000200000000000000150000000000000000000000000000
0000000000000000000000000000000000010000000000000000000000000000
0000000000010000001700000073746172732f62675f64756c6c737461727332
2e706e671600000073746172732f706c616e65745f70656163682e706e671b03
0000bd000000b400000001000000000000000000000000000000000000000100
00001700000073746172732f62675f6461726b6e6562756c612e706e67180000
0073746172732f706c616e65745f626967626c75652e706e6770010000130000
00b4000000010000000000000000000000000000000100000003000000040000
00010000000600000064726f6e6573010000000100000008000000636c6f616b
696e6700000000ffffffff00000000000000000c0000004c415345525f48554c
4c5f3100000000000000000a0000004d495353494c45535f3300000000010000
0006000000424f4d425f310000000002000000010000000a00000046544c5f4a
414d4d4552000000000100000009000000494f4e5f41524d4f52000000000000
00000d0000004155544f5f434f4f4c444f574e00000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000001
0000000000000000000000000000000000000000000000010000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
00000000000000f1f2fc7800000000000000001100000044455354524f594544
5f44454641554c5411000000444541445f435245575f44454641554c54000000
0000000000b800000041204d616e746973206372657720686572652068617320
68756e6b6572656420646f776e20696e20746865206162646f6d656e206f6620
61206c6f6e672d646561642073706163652d7768616c65202d20746865206f6e
6c79207761792c2070726573756d61626c792c20666f72207468656d20746f20
6f70657261746520746865697220626c61636b2d6d61726b6574207472616465
20776974686f757420646574656374696f6e2e20576f7274682061206c6f6f6b
3fffffffff010000000000000000000000000000000000000000000000020000
000000000000000000072500005a0b0000000000000400000056050000802500
0000000000000000000000000000000000000000000000000001000000000000
000100000001000000000000000000000000000000e803000000000000000000
00e80300000000000000000000ffffffff000000000000000000000000000000
00e803000018fcffff18fcffffffffffff000000005605000060220000000000
0000000000000000000000000000000000000000000100000000000000010000
0001000000000000000000000000000000e80300000000000000000000e80300
000000000000000000ffffffff00000000000000000000000000000000e80300
0018fcffff18fcffffffffffff0000000000000000c02b000000000000000000
00000000000000000000000000000000000000000000000000ffffffff010000
00000000000000000000000000e8030000000000000000000000000000000000
0000000000ffffffff00000000000000000000000000000000e803000018fcff
ff18fcffffffffffff0000000000000000c02b00000000000000000000000000
000000000000000000000000000000000000000000ffffffff01000000000000
000000000000000000e803000000000000000000000000000000000000000000
00ffffffff00000000000000000000000000000000e803000018fcffff18fcff
ffffffffff0000000056050000204e0000000000000000000000000000000000
0000000000020000001100000046000000e30000004600000000000000000000
000100000001000000000000000000000000000000e803000000000000000000
00e80300000000000000000000ffffffff000000000000000000000000000000
00e803000018fcffff18fcffffb4000000000000000000000004000000010000
0000000000010000001c5a0000001900000b0000000000000001000000000000
0000000000000000000000000000000000000000000000000000000000000000
00
[/code]

**Comment by taowa** [comment]
Do you have any FTL mods?

**Comment by filipecatraia** [comment]
@taowa 

Nope, it's the plain FTL you get from Steam. However, this never happened again :)

**Comment by taowa** [comment]
This issue should be closed.

**Comment by Codingale** [comment]
@taowa Along with a bunch of other issues.
