### ISSUE TITLE
Calculate the score at any point

### ISSUE THREAD

**Issue by Niels-NTG** [Vhati/ftl-profile-editor#67]
I was wondering if it was possible to get the players score at any point during the game. I can't find anything in this source code that refers to this. Is this because the formula for calculating the final/current score is unknown to the public? Or is just simply because I haven't looked in the right places?

**Comment by Vhati** [comment]
It's calculated at the end, AFAIK.
Neat idea. I hadn't considered doing that. (added to todo list)
.
.
[Article](http://ftl.wikia.com/wiki/Score): FTLWiki - Score

Score is determined with the following formula (rounded down to nearest integer):

Score = (s+10*b+20*d)*D 

* s = scrap collected. Initial scrap (30 on easy, 10 on normal, 0 on hard) and scrap gained by selling at stores or additional gains from Scrap Recovery Arms does not count toward this total. 
* b = beacons visited 
* d = ships defeated by reducing hull or crew to zero 
* D = difficulty modifier (1x Easy, 1.25x Normal, 1.5x Hard)

.
.
I haven't tested the math to confirm, but it sounds like these are what you want:
* gameState.getTotalScrapCollected()
* gameState.getTotalBeaconsExplored()
* gameState.getTotalShipsDefeated()
* gameState.getDifficulty()

**Comment by Vhati** [comment]
I'll add a convenience method in the next version of the editor. ; )

**Comment by Niels-NTG** [comment]
In retrospect I could have googled that myself.. Seems like I could implement that in a minute. I sort of assumed it was something very complicated involving RNG seeds or something last like time.

I will test the math next morning.

-----Oorspronkelijk bericht-----
Van: "Vhati" <notifications@github.com>
Verzonden: ‎26-‎8-‎2015 02:21
Aan: "Vhati/ftl-profile-editor" <ftl-profile-editor@noreply.github.com>
CC: "Niels NTG" <NTG999@gmail.com>
Onderwerp: Re: [ftl-profile-editor] Calculate the score at any point (#67)

It's calculated at the end, AFAIK.
Neat idea. I hadn't considered doing that. (added to todo list)
.
.
Article: FTLWiki - Score
Score is determined with the following formula (rounded down to nearest integer):
Score = (s+10b+20d)*D 
s = scrap collected. Initial scrap (30 on easy, 10 on normal, 0 on hard) and scrap gained by selling at stores or additional gains from Scrap Recovery Arms does not count toward this total. 
b = beacons visited 
d = ships defeated by reducing hull or crew to zero 
D = difficulty modifier (1x Easy, 1.25x Normal, 1.5x Hard) 
.
.
I haven't tested the math to confirm, but it sounds like these are what you want:
gameState.getTotalScrapCollected() 
gameState.getTotalBeaconsExplored() 
gameState.getTotalShipsDefeated() 
gameState.getDifficulty()

**Comment by Niels-NTG** [comment]
Yup, from this one test it seems to work as intended. Thanks you.
![schermafbeelding 2015-08-26 om 12 25 26](https://cloud.githubusercontent.com/assets/6061595/9491211/a8b075e8-4bed-11e5-98c3-7033589d7413.png)
