### ISSUE TITLE
Way to get and set the position of a beacon

### ISSUE THREAD

**Issue by Niels-NTG** [Vhati/ftl-profile-editor#70]
Presently there doesn't seem to be a way to get or set the x- and y-position of a separate beacon inside a sector. There doesn't seem to be anything in this repositories source code that could do such a thing. But could it be possible to retrieve this information somehow?

**Comment by Vhati** [comment]
If you're referring to beacons' layout as displayed FTL's sector map, they're essentially a grid (top-to-bottom, left to right). But there's a random seed involved in jostling them, deciding column sizes, and assigning events to trigger on arrival. It has not been reverse-engineered.

**Comment by Vhati** [comment]
You can blindly scramble them all with this.

SavedGameState.setSectorLayoutSeed(int)

**Comment by Vhati** [comment]
v26 has been released!

It adds the RandomSectorMapGenerator class, which takes the layout seed and reconstructs the beacons' scattering. This amounts to read-only access to their x, y positions.
