### ISSUE TITLE
Profile Parser Error

### ISSUE THREAD

**Issue by Mego** [Vhati/ftl-profile-editor#72]
[code]
Profile Parser Error

Exception: java.lang.RuntimeException: Not a bool: 5

Stack Trace...
  net.blerf.ftl.parser.Parser.readBool(Parser.java:21)
  net.blerf.ftl.parser.ProfileParser.readShipUnlocks(ProfileParser.java:320)
  net.blerf.ftl.parser.ProfileParser.readProfile(ProfileParser.java:84)
  net.blerf.ftl.ui.FTLFrame$4.actionPerformed(FTLFrame.java:403)
  javax.swing.AbstractButton.fireActionPerformed(Unknown Source)

Editor Version: 25
OS: Windows 8.1 6.3
VM: Java HotSpot(TM) 64-Bit Server VM, 1.8.0_51, amd64
[/code]

File ("continue.sav.pre")...
[code]
0900000001000000000000000100000005000000e7030000030000000b000000
546865204b65737472656c10000000504c415945525f534849505f4841524401
00000000000000030000000a00000066697265645f73686f7413000000060000
00686967686f32010000000c000000757365645f6d697373696c650100000010
000000504c415945525f534849505f484152440b000000546865204b65737472
656c070000006b65737472616c030000000500000068756d616e060000005475
72696e670500000068756d616e04000000546163680500000068756d616e0700
00004a6f726c61636b01000000084c010000000000000000001e000000630000
0063000000630000000f2700000300000006000000547572696e670500000068
756d616e0000000064000000fb0100009d000000000000000000000001000000
00000000ffffffff020000000000000001000000000000000000000000000000
0000000000000000000000000000000000000000000000000100000000000000
000000000000000004000000000000000000000000000000ffffffffe8030000
0000000002000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000001000000
000000000000000000000000e803000000000000000000000000000004000000
546163680500000068756d616e000000006400000034000000c00000000e0000
00020000000100000000000000ffffffff020000000000000002000000000000
00020000000e0000000000000000000000000000000000000000000000000000
0001000000000000000000000000000000040000000000000000000000000000
00ffffffffe80300000000000002000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
000000000001000000000000000000000000000000e803000000000000000000
0000000000070000004a6f726c61636b0500000068756d616e00000000640000
00c00000009d0000000a000000010000000100000000000000ffffffff020000
00000000000300000000000000010000000a0000000000000000000000000000
0007000000000000000000000001000000000000000000000000000000040000
00000000000000000000000000ffffffffe80300000000000002000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000010000000000000000000000000000
00e8030000000000000000000000000000080000000200000002000000000000
0000000000000000000000000000000000000000000000000000000000e80300
0000000000010000000200000002000000000000000000000000000000000000
0000000000000000000000000000000000e80300000000000001000000010000
0001000000000000000000000000000000000000000000000000000000000000
0000000000e80300000000000001000000030000000300000000000000000000
00000000000000000000000000000000000000000000000000e8030000000000
0001000000000000000100000000000000000000000000000000000000000000
0000000000000000000000000000000000e80300000000000001000000010000
0001000000000000000000000000000000000000000000000000000000000000
0000000000e80300000000000001000000010000000100000000000000000000
00000000000000000000000000000000000000000000000000e8030000000000
0001000000010000000100000000000000000000000000000000000000000000
00000000000000000000000000e8030000000000000100000000000000000000
0000000000000000000000000000000000000000000100000000000000000000
0000000000000000000000000001000000e80300000000000000000000be4802
00d0e40500640000000000000000000000ffffffff0000000000000000ffffff
ff0000000001000000640000000000000000000000ffffffff00000000000000
00ffffffff0000000000000000ffffffff0000000000000000ffffffffffffff
ff04000000640000000000000000000000ffffffff0000000000000000ffffff
ff0100000002000000640000000000000000000000ffffffff00000000000000
00ffffffff0100000000000000640000000000000000000000ffffffff000000
0000000000ffffffff0000000000000000ffffffff0000000000000000ffffff
ffffffffff04000000640000000000000000000000ffffffff00000000000000
00ffffffff0000000000000000ffffffff0000000000000000ffffffff000000
0003000000640000000000000000000000ffffffff0000000000000000ffffff
ffffffffff04000000640000000000000000000000ffffffff00000000000000
00ffffffff0000000000000000ffffffff0000000000000000ffffffffffffff
ff04000000640000000000000000000000ffffffff0000000000000000ffffff
ff0000000000000000ffffffff0000000000000000ffffffffffffffff040000
00640000000000000000000000ffffffff0000000000000000ffffffffffffff
ff04000000640000000000000000000000ffffffff0000000000000000ffffff
ff0000000000000000ffffffff0000000000000000ffffffff01000000020000
00640000000000000000000000ffffffff0000000000000000ffffffffffffff
ff04000000640000000000000000000000ffffffff0000000000000000ffffff
ffffffffff04000000640000000000000000000000ffffffff00000000000000
00ffffffffffffffff04000000640000000000000000000000ffffffff000000
0000000000ffffffff0000000000000000ffffffff0000000000000000ffffff
ff0200000000000000640000000000000000000000ffffffff00000000000000
00ffffffffffffffff04000000640000000000000000000000ffffffff000000
0000000000ffffffffffffffff04000000000000000400000004000000040000
0000000000000000000000000000000000040000000400000004000000000000
0000000000000000000000000004000000040000000400000000000000000000
0000000000000000000400000004000000040000000000000000000000000000
0000000000040000000400000004000000000000000000000000000000000000
0004000000040000000400000000000000000000000000000000000000040000
0004000000040000000000000000000000000000000000000004000000040000
0004000000000000000000000000000000000000000400000004000000040000
0000000000000000000000000000000000040000000400000004000000000000
0000000000000000000000000004000000040000000400000000000000000000
0000000000000000000400000004000000040000000000000000000000000000
0000000000040000000400000004000000000000000000000000000000000000
0004000000040000000400000000000000000000000000000000000000040000
0004000000040000000000000000000000000000000000000004000000040000
0004000000000000000000000000000000000000000400000004000000040000
0000000000000000000000000000000000040000000400000004000000000000
0000000000000000000000000004000000040000000400000000000000000000
0000000000000000000400000004000000040000000000000000000000000000
0000000000040000000400000004000000000000000000000000000000000000
0004000000040000000400000000000000000000000000000000000000040000
0004000000040000000000000000000000000000000000000004000000040000
0004000000000000000000000000000000000000000400000004000000040000
0000000000000000000000000000000000040000000400000004000000000000
00000000000000000000000000000000000000000003000000110000004d4953
53494c45535f325f504c41594552010000000d0000004c415345525f42555253
545f330100000005000000494f4e5f320000000000000000030000000c000000
4144565f5343414e4e45525311000000444546454e53455f534352414d424c45
520a00000046544c5f4a554d50455200000000825f0000177f000041fdffff18
010000000000000800000000000000ffffffff00000000000000000000000000
0000000000000000000000000000001300000001000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000018000000000000000100000000000000010000000000000000
0000000000000001000000000000000100000000000000000000000000000001
0000000000000001000000000000000000000001000000170000007374617273
2f62675f64756c6c7374617273322e706e671600000073746172732f706c616e
65745f62726f776e2e706e6774010000b6000000b40000000100000001000000
0a0000004c4f4e475f464c4545541100000053484950535f524542454c5f454c
495445a53b000001000000000000000000000000000000010000000000000000
0000000000000000000000010000001700000073746172732f62675f6c6f6e65
6c79737461722e706e671900000073746172732f706c616e65745f6761735f62
6c75652e706e672c010000ea0000000000000001000000000000000000000000
00000000000000010000001700000073746172732f62675f6461726b6e656275
6c612e706e672100000073746172732f706c616e65745f706f70756c61746564
5f6f72616e67652e706e67ac0000001d00000000000000010000000000000000
0000000000000000000000010000001700000073746172732f62675f6c6f6e65
6c79737461722e706e671f00000073746172732f706c616e65745f706f70756c
617465645f6461726b2e706e67aa0000007d0000000000000001000000000000
000000000000000000010000000400000004000000010000000600000064726f
6e6573000000000100000008000000636c6f616b696e67000000000100000008
000000636c6f6e6562617900000000030000000100000004000000656e676900
0000000100000004000000656e676900000000010000000500000068756d616e
00000000010000000100000009000000444546454e53455f3100000000010000
0009000000444546454e53455f32000000000100000006000000424154544c45
00000000020000000100000011000000444546454e53455f534352414d424c45
5200000000010000000e00000044524f4e455f5245434f564552590000000001
0000000f00000053435241505f434f4c4c4543544f5200000000050000000300
000002000000010000001700000073746172732f62675f6461726b6e6562756c
612e706e671800000073746172732f706c616e65745f626967626c75652e706e
6739010000b40000000000000001000000000000000000000000000000000000
0000000000010000000000000000000000000000000000000000000000010000
0000000000000000000000000000000000000000000100000000000000000000
0000000000000000000000000001000000000000000000000000000000000000
0000000000010000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000001000000404d000010000000504952
4154455f53555252454e4445520d0000005049524154455f4553434150451100
000044455354524f5945445f44454641554c5411000000444541445f43524557
5f44454641554c5400000000100000005049524154455f53555252454e444552
00000000ffffffff010000000000000001000000000000000900000052454245
4c5f4641541200000073686f756c64206e6f74206265207365656e0b00000072
6562656c5f7371756174030000000500000068756d616e080000005377616d70
736f6e0500000068756d616e060000004772616369650500000068756d616e08
00000054656c646172696e000000000000000000000000000000000200000010
000000020000000a000000af00000003000000080000005377616d70736f6e05
00000068756d616e000000006400000034000000110000000000000000000000
0000000000000000ffffffff02000000000000000100000000000000ffffffff
ffffffff00000000000000000000000000000000000000000000000001000000
00000000000000000000000000000000000000000000000000000000ffffffff
e803000000000000020000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
01000000000000000000000000000000e8030000000000000000000000000000
060000004772616369650500000068756d616e00000000640000005700000057
00000004000000000000000000000000000000ffffffff020000000000000001
00000000000000ffffffffffffffff0000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
00000000000000ffffffffe80300000000000002000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
000000000000000000000001000000000000000000000000000000e803000000
00000000000000000000000800000054656c646172696e0500000068756d616e
000000000a000000c00000007a00000006000000010000000000000000000000
ffffffff02000000000000000200000000000000ffffffffffffffff00000000
0000000000000000000000000000000000000000010000000200000000000000
0000000000000000000000000000000000000000ffffffffe803000000000000
0200000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000100000000000000
0000000000000000e80300000000000000000000000000000800000002000000
0200000000000000000000000000000000000000000000000000000000000000
00000000e8030000000000000100000002000000020000000000000000000000
000000000000000000000000000000000000000000000000e803000000000000
0100000001000000010000000000000000000000000000000000000000000000
000000000000000000000000e803000000000000010000000100000000000000
0100000000000000000000001000000000000000000000000000000000000000
e803000000000000010000000200000000000000000000000000000000000000
0000000000000000000000000000000000000000e80300000000000001000000
0000000001000000010000000000000000000000000000000000000000000000
000000000000000000000000e803000000000000010000000000000000000000
0000000000000000000000000000000000000000000000000000000001000000
000000000000000000000000000000000000000001000000e803000000000000
00000000b5f60100c6600400640000000000000000000000ffffffff00000000
00000000ffffffff0000000002000000640000000000000000000000ffffffff
0000000000000000ffffffffffffffff04000000640000000000000000000000
ffffffff0000000000000000ffffffffffffffff040000006400000000000000
00000000ffffffff0000000000000000ffffffffffffffff0400000064000000
0000000000000000ffffffff0000000000000000ffffffff0000000000000000
ffffffff0000000000000000ffffffff00000000020000006400000000000000
00000000ffffffff0000000000000000ffffffffffffffff0400000064000000
0000000000000000ffffffff0000000000000000ffffffff0100000000000000
640000000000000000000000ffffffff0000000000000000ffffffff00000000
0000000000000000040000000400000004000000000000000000000000000000
0000000004000000040000000400000000000000000000000000000000000000
0400000004000000040000000000000000000000000000000000000004000000
0400000004000000000000000000000000000000000000000400000004000000
0400000000000000000000000000000000000000040000000400000004000000
0000000000000000000000000000000004000000040000000400000000000000
0000000000000000000000000400000004000000040000000000000000000000
00000000000000000000000000000000010000000d0000004c415345525f4845
4156595f310000000002000000060000005245504149520000000001000000ff
ffffffffffffff0100000000000000190000000a000000414e54495f44524f4e
450000000001000000ffffffffffffffffffffffffffffffff01000000000000
000100000000000000000000000200000000000000983a000000000000000000
0000000000020000000000000000000000000000000200000000000000000000
0000000000000000000000000003000000ea200000ab26000000000000000000
0000000000000000000000000000000000000000000000000001000000010000
00000000000000000000000000e80300000000000000000000e8030000000000
0000000000ffffffff00000000000000000000000000000000e803000018fcff
ff18fcffffffffffff00000000150d00002f2a00000000000000000000000000
0000000000000000000000000001000000000000000100000001000000000000
000100000053000000e80300000000000000000000e803000000000000000000
00ffffffff00000000000000000000000000000000e803000018fcffff18fcff
ffffffffff0000000000000000b32d0000000000000000000000000000000000
0000000000000000000000000000000000ffffffff0100000000000000000000
0000000000e80300000000000000000000000000000000000000000000ffffff
ff00000000000000000000000000000000e803000018fcffff18fcffffffffff
ff00000000000000000100000000000000010000000000000000000000010000
00010000002e3804008fcf0200735304000792020041520400bb940200000000
800000008000000080000000800000008000000080000000000000000018fcff
ffe0690b000000000000000000ffffff7f00000000000000000000000018fcff
ff01000000000000000000000000000000000000000000000000000000e80300
0000000000000000000100000000000000282300000000000000000000000000
0000000000000000000000000000000000000000000000000001000000000000
000000000000000000e803000000000000000000000000000000000000000000
00ffffffff00000000000000000000000000000000e803000018fcffff18fcff
ffffffffff000000000000000000803a3c000000000100000000000000010000
00307500000000000000000000
[/code]

**Comment by Vhati** [comment]
FTL creates two different files: a profile ("ae_prof.sav") for high scores, and a saved game ("continue.sav") for the state of your last playthrough.

When you start the editor, you first need to choose the appropriate tab, then click open.
