### ISSUE TITLE
Profile Parser Error

### ISSUE THREAD

**Issue by IronCraftMan** [Vhati/ftl-profile-editor#74]
[code]
Profile Parser Error

Exception: java.io.IOException: Unsupported difficulty flag for achievement 26 ("PLAYER_SHIP_CRYSTAL_QUEST"): 286331137

Stack Trace...
  net.blerf.ftl.parser.ProfileParser.readAchievements(ProfileParser.java:141)
  net.blerf.ftl.parser.ProfileParser.readProfile(ProfileParser.java:82)
  net.blerf.ftl.ui.FTLFrame$4.actionPerformed(FTLFrame.java:403)
  javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2028)
  javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2351)

Editor Version: 25
OS: Mac OS X 10.11.2
VM: Java HotSpot(TM) 64-Bit Server VM, 1.6.0_65, x86_64
[/code]

File ("ae_prof.sav")...
[code]
09000000020000001b0000000e0000004143485f554e4c4f434b5f414c4c0000
0000150000004143485f554e495445445f46454445524154494f4e0100000010
0000004143485f46554c4c5f415253454e414c01000000120000004143485f45
4e455247595f534849454c445301000000100000004143485f454e455247595f
504f57455201000000130000004143485f535445414c54485f44455354524f59
01000000110000004143485f535445414c54485f41564f4944010000000b0000
004143485f524f424f544943010000000f0000004143485f4f4e4c595f44524f
4e4553010000000d0000004143485f524f434b5f464952450100000011000000
4143485f524f434b5f4d495353494c455301000000140000004143485f4d414e
5449535f435245575f4445414401000000140000004143485f4d414e5449535f
534c41554748544552010000000f0000004143485f534c55475f564953494f4e
010000000f0000004143485f534c55475f4e4542554c41010000001000000041
43485f4645445f50415449454e434501000000110000004143485f4645445f44
49504c4f4d41435901000000110000004143485f4352595354414c5f53484152
4401000000140000004143485f4352595354414c5f4c4f434b444f574e010000
00130000004143485f4c414e4955535f414456414e4345440000000010000000
4143485f4c414e4955535f53435241500000000019000000504c415945525f53
4849505f535445414c54485f51554553540100000018000000504c415945525f
534849505f4d414e5449535f51554553540100000017000000504c415945525f
534849505f4a454c4c595f51554553540100000016000000504c415945525f53
4849505f524f434b5f51554553540100000018000000504c415945525f534849
505f454e455247595f51554553540100000019000000504c415945525f534849
505f4352595354414c5f51554553540111111101000000010000000100000001
0000000100000001000000010000000100000001000000010000000100000001
0000000100000001000000010000000100000001000000000000000100000000
00000001000000010000000100000001000000050000000a000000546865204f
73707265790f000000504c415945525f534849505f4645449c02000004000000
0000000000000000000000000e00000054686520467265676174696461651100
0000504c415945525f534849505f4645445f33a5000000020000000000000000
000000010000000b000000546865205377616c6c6f7712000000504c41594552
5f534849505f484152445f335f00000001000000000000000000000001000000
08000000436572656e6b6f7614000000504c415945525f534849505f454e4552
47595f331e000000010000000000000000000000010000000a00000054686520
4f73707265790f000000504c415945525f534849505f46454414000000010000
00000000000000000000000000050000000b000000546865205377616c6c6f77
12000000504c415945525f534849505f484152445f335f000000010000000000
000000000000010000000a000000546865204f73707265790f000000504c4159
45525f534849505f4645449c020000040000000000000000000000000000000a
000000546865204f73707265790f000000504c415945525f534849505f464544
14000000010000000000000000000000000000000e0000005468652046726567
61746964616511000000504c415945525f534849505f4645445f33a500000002
00000000000000000000000100000008000000436572656e6b6f761400000050
4c415945525f534849505f454e455247595f331e000000010000000000000000
00000001000000070000000d0000001b0000003e00000002010000c601000008
0000001a000000060000000000000005000000040000004d6174740400000072
6f636b010000000300000005000000456d696c79060000006d616e7469730000
00001600000007000000526562656b61680500000068756d616e000000001a00
000007000000526562656b61680500000068756d616e00000000000000000000
00000000000001000000
[/code]

**Comment by Vhati** [comment]
Hmm. I have no clue how that happened. 
I manually replaced the weird 286331137 with a 1 (i.e. earned the quest in normal difficulty).

You can download the repaired profile below.
http://expirebox.com/download/29bf68e8be300506c03b4648b9421816.html
(The link will expire in 2 days.)

If you know steps that will recreate that problem, that would be helpful of course.  ; )
