### ISSUE TITLE
Editor says Adv Edition content is enabled when it isn't

### ISSUE THREAD

**Issue by contenteaten123** [Vhati/ftl-profile-editor#75]
I have the AE content disabled in the ship selection menu but on the editor is says it is enabled, so I can't edit my weapons or drones. Is there any way to fix this?

**Comment by Vhati** [comment]
Any saved game created after FTL 1.03.3 (1.5.x is called Advanced Edition) includes bytes that haven't been fully deciphered, and hence are unsafe to edit. This includes lots of added information about the state of weapons, drones, and systems. Toggling "AE Content" only changes the availability of items/enemies/etc. It does not actually revert to the old saved game file format.

Unrelated: The editor does not yet 'honor' that restriction, so currently it *should* be correctly reporting that the AE content is disabled under the "General" tab - but not hiding the *extra* choices (FTL will not like it if you pick them).

What you CAN do is edit your ship's cargo to give yourself new items. Then equip them in-game.

Store shelf editing has a bug that will be fixed soon. As of my next release, you'll be able to buy systems in-game.
