### ISSUE TITLE
SavedGame Parser Error

### ISSUE THREAD

**Issue by Champteach** [Vhati/ftl-profile-editor#76]
Drone Schematic Blueprint issue

**Comment by Vhati** [comment]
Can you elaborate?

**Comment by Champteach** [comment]
Actually I guess my copy paste never worked well. I apologize. 

Basically what happens, is that sometimes I save a game on the editor and then the save doesn't register properly. Thus disabling me from further accessing the game on the editor. If I try and play my game from FTL, the game runs very slowly and the drone system doesn't work. 

I have a macbook.  If I ever use the editor again, and it does the same I will try and further this convo.

Jan

**Comment by Champteach** [comment]
[code]
SavedGame Parser Error

Exception: java.lang.RuntimeException: End of stream reached before reading enough bytes for an int

Stack Trace...
  net.blerf.ftl.parser.Parser.readInt(Parser.java:43)
  net.blerf.ftl.parser.Parser.readBool(Parser.java:18)
  net.blerf.ftl.parser.SavedGameParser.readExtendedShipInfo(SavedGameParser.java:9321)
  net.blerf.ftl.parser.SavedGameParser.readZeus(SavedGameParser.java:9241)
  net.blerf.ftl.parser.SavedGameParser.readSavedGame(SavedGameParser.java:244)

Editor Version: 25
OS: Mac OS X 10.11.2
VM: Java HotSpot(TM) 64-Bit Server VM, 1.6.0_65, x86_64
[/code]

File ("continue.sav")...
[code]
090000000100000001000000280000006700000074070000090000000c000000
535320456e646561766f757210000000504c415945525f534849505f48415244
0800000000000000120000000a000000626c75655f616c69656e030000000e00
000064657374726f7965645f726f636b040000000a000000656e765f64616e67
6572080000000a00000066697265645f73686f74250500000600000068696768
6f32010000000b0000006b696c6c65645f6372657727000000090000006c6f73
745f6372657701000000060000006e6562756c61180000000f0000006f666665
6e736976655f64726f6e650d0000000f00000072656163746f725f7570677261
64650b0000000e00000073746f72655f7075726368617365190000000c000000
73746f72655f726570616972250000000f000000737566666f63617465645f63
726577f20100000e00000073797374656d5f75706772616465140000000a0000
00757365645f64726f6e650a0000000c000000757365645f6d697373696c653a
0000000e000000776561706f6e5f757067726164650500000005000000727577
656e0100000010000000504c415945525f534849505f484152440c0000005353
20456e646561766f7572070000006b65737472616c030000000500000068756d
616e0900000043617074204d6172730500000068756d616e08000000434f2053
657267650500000068756d616e06000000434e204a616e01000000084c010000
000000000000001e00000018000000160000000f000000020000000800000009
00000043617074204d6172730500000068756d616e0000000064000000fb0100
009d00000000000000000000000100000000000000ffffffff02000000000000
00000000000000000000000000000000001a0000000000000000000000000000
000c00000001000000010000000c000000000000008600000068000000020000
000000000000000000ffffffffe8030000000000009500000001000000010000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000001000000000000000000000000000000e80300
000000000000000000000000000900000043434f205365726765050000006875
6d616e0000000064000000c00000009d0000000a000000010000000100000000
000000ffffffff02000000000000000100000000000000010000000a00000001
0000000100000002000000740000001400000003000000010000001400000003
0000000200000068000000030000000000000000000000ffffffffe803000000
0000009500000000000000000000000000000000000000000000000000000001
0000000100000001000000000000000000000000000000000000000100000000
0000000000000000000000e80300000000000000000000000000000a00000043
4520436861726c696504000000736c756700000000260000006f0100009d0000
0002000000000000000100000000000000ffffffff0100000000000000000000
000100000003000000000000000000000004000000000000001f000000000000
00010000000d0000000000000000000000290000000000000000000000000000
00ffffffffe80300000000000095000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
000000000001000000000000000000000000000000e803000000000000000000
0000000000070000004345204d61616b0500000068756d616e00000000450000
00340000009d0000000e000000000000000100000000000000ffffffff020000
00000000000300000000000000000000000c00000000000000020000003d0000
0000000000040000000100000001000000040000000000000000000000230000
00000000000000000000000000ffffffffe80300000000000095000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000010000000000000000000000000000
00e80300000000000000000000000000000c0000004c742054656c6461617269
6e09000000616e6165726f6269630000000064000000290100007a0000000400
0000000000000100000000000000ffffffff0100000002000000000000000000
0000070000000000000002000000370000000000000002000000010000000100
00000200000001000000000000001f000000000000000000000000000000ffff
ffffe80300000000000095000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
000001000000000000000000000000000000e803000000000000000000000000
00000a000000536774204b617261746804000000726f636b0000000065000000
92010000c000000003000000010000000100000000000000ffffffff01000000
030000000000000001000000020000000f000000000000000000000002000000
0200000009000000010000000200000001000000000000001a00000000000000
0000000000000000ffffffffe803000000000000950000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000001000000000000000000000000000000e8030000
00000000000000000000000005000000527577656e070000006372797374616c
000000007d00000029010000c000000005000000000000000100000000000000
ffffffff01000000000000000000000000000000050000000000000000000000
5400000000000000010000000000000001000000010000000000000000000000
15000000000000000000000000000000ffffffffe80300000000000095000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000010000000000000000000000
00000000e803000000000000000000000000000050c3000050c3000000000000
070000004345204372696304000000656e6769000000001d00000034000000c0
0000000e000000020000000100000000000000ffffffff000000000000000002
0000000e000000000000001e0000000000000041000000020000000000000000
00000002000000000000000000000006000000000000000000000000000000ff
ffffffe803000000000000950000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
00000001000000000000000000000000000000e8030000000000000000000000
0000001900000006000000040000000000000000000000000000800000000000
000000020000000000000000000000e803000000000000010000000700000004
0000000000000000000000000000800000000000000000000000000000000000
000000e803000000000000010000000200000000000000000000000000000000
0000800000000000000000000000000000000000000000e80300000000000001
0000000800000008000000000000000000000000000080000000000000000000
0000000000000000000000e80300000000000001000000020000000200000000
00000000000000000000800000000000000000000000000000000000000000e8
0300000000000001000000020000000000000000000000000000000000008000
00000000000000000000000000000000000000e8030000000000000100000003
0000000300000000000000000000000000008000000000000000000000000000
00000000000000e8030000000000000100000002000000010000000000000000
000000000000800000000000000000000000000000000000000000e803000000
0000000100000002000000020000000000000000000000000000800000000000
000000000000000000000000000000e803000000000000010000000000000003
0000000300000000000000000000000000008000000000000000000000000000
00000000000000e8030000000000000100000000000000020000000100000000
00000000000000000000800000000000000000000000000000000000000000e8
0300000000000001000000000000000000000003000000030000000000000000
000000000000800000000000000000000000000000000000000000e803000000
00000001000000010000000200000095020000020000000000000000000000bb
070000000000000000000001000000e80300000000000000000000c7f601008c
b5ffff0000000000000000983a00007da00000640000000000000000000000ff
ffffff0000000000000000ffffffff0000000001000000640000000000000000
000000ffffffff0000000000000000ffffffff0000000000000000ffffffff00
00000000000000ffffffffffffffff04000000640000000000000000000000ff
ffffff0000000000000000ffffffff0100000002000000640000000000000000
000000ffffffff0000000000000000ffffffff01000000000000006400000000
00000000000000ffffffff0000000000000000ffffffff0000000000000000ff
ffffff0000000000000000ffffffffffffffff04000000640000000000000000
000000ffffffff0000000000000000ffffffff0000000000000000ffffffff00
00000000000000ffffffff0000000003000000640000000000000000000000ff
ffffff0000000000000000ffffffffffffffff04000000640000000000000000
000000ffffffff0000000000000000ffffffff0000000000000000ffffffff00
00000000000000ffffffffffffffff04000000640000000000000000000000ff
ffffff0000000000000000ffffffff0000000000000000ffffffff0000000000
000000ffffffffffffffff04000000640000000000000000000000ffffffff00
00000000000000ffffffffffffffff04000000640000000000000000000000ff
ffffff0000000000000000ffffffff0000000000000000ffffffff0000000000
000000ffffffff0100000002000000640000000000000000000000ffffffff00
0000002d000000ffffffffffffffff04000000640000000000000000000000ff
ffffff0000000000000000ffffffffffffffff04000000640000000000000000
000000ffffffff000000001f000000ffffffffffffffff040000006400000000
00000019000000ffffffff0000000000000000ffffffff0000000000000000ff
ffffff0000000011000000ffffffff0200000000000000640000000000000000
000000ffffffff0000000000000000ffffffffffffffff040000006400000000
00000000000000ffffffff0000000025000000ffffffffffffffff0400000000
0000000800000008000000080000000000000000000000010000000000000008
0000000800000008000000000000000000000001000000000000000800000008
0000000800000000000000000000000100000000000000080000000800000008
0000000000000000000000010000000000000008000000080000000800000000
0000000000000001000000000000000800000008000000080000000000000000
0000000100000000000000080000000800000008000000000000000000000001
0000000000000008000000080000000800000000000000000000000100000000
0000000800000008000000080000000000000000000000010000000000000008
0000000800000008000000000000000000000001000000000000000800000008
0000000800000000000000000000000100000000000000080000000800000008
0000000000000000000000010000000000000008000000080000000800000000
0000000000000001000000000000000800000008000000080000000000000000
0000000100000000000000080000000800000008000000000000000000000001
0000000000000008000000080000000800000000000000000000000100000000
0000000800000008000000080000000000000000000000010000000000000008
0000000800000008000000000000000000000001000000000000000800000008
0000000800000000000000000000000100000000000000080000000800000008
0000000000000000000000010000000000000008000000080000000800000000
0000000000000001000000000000000800000008000000080000000000000000
0000000100000000000000080000000800000008000000000000000000000001
0000000000000008000000080000000800000000000000000000000100000000
0000000800000008000000080000000000000000000000010000000000000008
0000000800000008000000000000000000000001000000000000000000000000
00000003000000100000004c415345525f434841494e47554e5f320100000009
00000053484f5447554e5f3201000000110000004d495353494c45535f325f50
4c41594552010000000100000008000000434f4d4241545f3101000000010000
00ffffffffffffffffffffffffffffffff01000000020000000b0000004e414e
4f5f4d45444241590f00000053435241505f434f4c4c4543544f5200000000a8
993727dc583d583c000000c8000000000000001100000000000000ffffffff00
0000000000000001000000020000000000000000000000000000001600000001
0000000100000000000000010000000000000000000000000000000100000000
0000000000000001000000000000000000000000000000010000000000000000
0000000100000000000000000000000000000001000000070000000000000018
000000000000000100000000000000030000000100000000000000010000001a
00000073746172732f62675f6c6f6e656c79526564537461722e706e67140000
0073746172732f706c616e65745f7265642e706e6758010000ba010000b40000
0001000000010000000a0000004c4f4e475f464c454554110000005348495053
5f524542454c5f454c495445387b5e3601000000000000000000000001000000
1700000073746172732f62675f6461726b6e6562756c612e706e671600000073
746172732f706c616e65745f70656163682e706e678c0200005f000000b40000
000100000000000000000000000000000000000000010000001a000000737461
72732f62675f6c6f6e656c79526564537461722e706e67160000007374617273
2f706c616e65745f62726f776e2e706e6713000000d000000000000000010000
00010000000a0000004c4f4e475f464c4545541100000053484950535f524542
454c5f454c495445d65d165b0100000000000000000000000000000000000000
0000000001000000000000000000000000000000010000000000000000000000
0000000000000000010000001700000073746172732f62675f6461726b6e6562
756c612e706e671600000073746172732f706c616e65745f70656163682e706e
67d902000052010000b400000001000000010000000a0000004c4f4e475f464c
4545541100000053484950535f524542454c5f454c4954455474e32a01000000
0000000000000000000000000100000000000000010000000000000000000000
0000000001000000000000000000000000000000000000000000000001000000
00000000010000000000000000000000010000001700000073746172732f6267
5f64756c6c7374617273322e706e672000000073746172732f706c616e65745f
706f70756c617465645f62726f776e2e706e6706020000d2000000b400000001
000000010000000a0000004c4f4e475f464c4545541100000053484950535f52
4542454c5f454c4954450a771e26010000000000000000000000000000000000
0000000000000000000001000000000000000000000001000000000000000100
00000000000000000000010000001700000073746172732f62675f6c6f6e656c
79737461722e706e671800000073746172732f706c616e65745f626967626c75
652e706e670e01000040000000b4000000010000000000000000000000000000
0000000000020000001700000073746172732f62675f6461726b6e6562756c61
2e706e671b00000073746172732f706c616e65745f6761735f79656c6c6f772e
706e676b00000071000000b40000000100000000000000000000000000000001
00000003000000000000000100000005000000494f4e5f320000000001000000
0c000000494f4e5f434841494e47554e000000000100000005000000494f4e5f
310000000004000000010000000a00000074656c65706f727465720000000001
00000008000000636c6f6e656261790200000001000000040000006d696e6402
00000003000000010000000500000068756d616e000000000100000004000000
726f636b00000000010000000500000068756d616e0000000004000000030000
0003000000000000000000000000000000010000000000000000000000000000
0001000000000000000100000000000000000000000100000017000000737461
72732f62675f6461726b6e6562756c612e706e671400000073746172732f706c
616e65745f7265642e706e6785020000cc000000b40000000100000001000000
0a0000004c4f4e475f464c4545541100000053484950535f524542454c5f454c
49544555ad995e01000000000000000000000001000000170000007374617273
2f62675f64756c6c7374617273322e706e671600000073746172732f706c616e
65745f62726f776e2e706e67e70100008c000000000000000100000001000000
0a0000004c4f4e475f464c4545541100000053484950535f524542454c5f454c
4954450f88f57d01000000000000000000000000000000010000000000000001
0000000000000000000000000000000000000000000000010000000000000000
0000000000000001000000000000000100000000000000000000000000000001
0000000000000001000000000000000000000000000000010000000000000001
0000000000000000000000000000000000000000000000015dcc0e0000000000
0000002400000053515541545f52454655454c5f53544154494f4e2064657374
726f7965642020313239352400000053515541545f52454655454c5f53544154
494f4e206465616420637265772020313239330000000000000000b600000059
6f7520636861736520646f776e2074686520666c61677368697020616e642064
6973636f7665722069742069732068656176696c792064616d61676564206672
6f6d207468652070726576696f75732066696768742e205363616e7320696e64
6963617465207468617420697420686173207265646972656374656420636f6e
736964657261626c6520706f77657220746f206974732064726f6e65732e2047
657420726561647920666f7220612066696768742effffffff01000000000000
00010000000100000011000000424f53535f325f4e4f524d414c5f444c431200
000073686f756c64206e6f74206265207365656e06000000626f73735f320000
0000010000000000000000000000000000000f00000010000000060000000a00
00000a00000009000000080000005377616d70736f6e0500000068756d616e00
000000550000007a0000001100000000000000000000000000000000000000ff
ffffff02000000000000000300000000000000ffffffffffffffff0000000000
0000000000000000000000000000000000000001000000010000000000000002
00000000000000000000000000000000000000ffffffffe80300000000000095
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000010000000000000000
00000000000000e8030000000000000000000000000000090000004672656465
7269636b0500000068756d616e0000000028000000a70000007a0000000c0000
00020000000000000000000000ffffffff020000000000000002000000000000
00ffffffffffffffff0000000000000000000000000000000000000000000000
0001000000010000000000000000000000000000000000000000000000000000
00ffffffffe80300000000000095000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
000000000001000000000000000000000000000000e803000000000000000000
0000000000070000004772616666696e0500000068756d616e00000000640000
00940000004e00000000000000010000000000000000000000ffffffff020000
00000000000200000000000000ffffffffffffffff0000000000000000000000
0000000000000000000000000001000000000000000000000000000000000000
00000000000000000000000000ffffffffe80300000000000095000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000010000000000000000000000000000
00e8030000000000000000000000000000040000004b7573790500000068756d
616e00000000280000007a000000570000000100000002000000000000000000
0000ffffffff02000000000000000300000000000000ffffffffffffffff0000
0000000000000000000000000000000000000000000001000000000000000000
00000000000000000000000000000000000000000000ffffffffe80300000000
0000950000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000010000000000
00000000000000000000e8030000000000000000000000000000050000004d61
78696d0500000068756d616e000000003f000000290100009d0000000c000000
000000000000000000000000ffffffff02000000000000000300000000000000
ffffffffffffffff000000000000000000000000000000000000000000000000
0100000000000000000000000000000000000000000000000000000000000000
ffffffffe8030000000000009500000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000001000000000000000000000000000000e80300000000000000000000
00000000060000004e617468616e0500000068756d616e00000000430000004c
0100009d0000000c000000010000000000000000000000ffffffff0200000000
0000000300000000000000ffffffffffffffff00000000000000000000000000
0000000000000000000000010000000000000000000000000000000000000000
0000000000000000000000ffffffffe803000000000000950000000000000000
0000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000001000000000000000000000000000000e8
030000000000000000000000000000070000004b6170616c6b61050000006875
6d616e0000000064000000340000003400000009000000000000000000000000
000000ffffffff02000000000000000200000000000000ffffffffffffffff00
0000000000000000000000000000000000000000000000010000000000000000
0000000000000000000000000000000000000000000000ffffffffe803000000
0000009500000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000100000000
0000000000000000000000e80300000000000000000000000000000d0000004c
6f67616e204a6f686e736f6e0500000068756d616e0000000064000000e30000
00340000000a000000000000000000000000000000ffffffff02000000000000
000200000000000000ffffffffffffffff000000000000000000000000000000
0000000000000000000100000000000000000000000000000000000000000000
000000000000000000ffffffffe8030000000000009500000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000001000000000000000000000000000000e80300
00000000000000000000000000060000004d612046616e0500000068756d616e
00000000640000004c010000570000000e000000010000000000000000000000
ffffffff02000000000000000100000000000000ffffffffffffffff00000000
0000000000000000000000000000000000000000010000000000000000000000
0000000000000000000000000000000000000000ffffffffe803000000000000
9500000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000100000000000000
0000000000000000e80300000000000000000000000000002c00000008000000
0400000003000000000000000000000021000000000000000000000001000000
01000000e8030000000000000100000003000000030000000000000000000000
000000000000000000000000000000000000000000000000e803000000000000
0100000002000000020000000000000000000000000000000000000000000000
000000000000000000000000e803000000000000010000000000000008000000
0400000003000000000000000000000019000000000000000000000000000000
00000000e8030000000000000100000003000000030000000000000000000000
000000000000000000000000000000000000000000000000e803000000000000
0100000003000000030000000000000000000000000000000000000000000000
000000000000000000000000e803000000000000010000000000000000000000
0000000000000000030000000300000000000000000000000000000000000000
00000000000000000000000000000000e8030000000000000100000003000000
0300000000000000000000000000000000000000000000000000000000000000
00000000e8030000000000000100000003000000030000000000000000000000
000000000000000000000000000000000000000000000000e803000000000000
0100000000000000000000000000000000000000010000000000000000000000
a5010000010000004a03000001000000e803000000000000000000009bdd0400
66d50500640000000000000000000000ffffffff0000000000000000ffffffff
0000000002000000640000000000000000000000ffffffff0000000000000000
ffffffff0000000000000000ffffffff0000000000000000ffffffff01000000
01000000640000000000000000000000ffffffff0000000000000000ffffffff
ffffffff04000000640000000000000000000000ffffffff0000000000000000
ffffffffffffffff04000000640000000000000000000000ffffffff00000000
00000000ffffffffffffffff04000000640000000000000000000000ffffffff
0000000000000000ffffffff0000000000000000ffffffff0000000000000000
ffffffffffffffff04000000640000000000000000000000ffffffff00000000
00000000ffffffff0000000000000000ffffffff0000000000000000ffffffff
ffffffff04000000640000000000000000000000ffffffff0000000000000000
ffffffffffffffff04000000640000000000000000000000ffffffff00000000
00000000ffffffff0000000000000000ffffffff0000000000000000ffffffff
0200000003000000640000000000000000000000ffffffff0000000000000000
ffffffff0000000002000000640000000000000000000000ffffffff00000000
00000000ffffffff0000000002000000640000000000000000000000ffffffff
0000000000000000ffffffffffffffff04000000640000000000000000000000
ffffffff0000000000000000ffffffff0000000000000000ffffffff00000000
00000000ffffffffffffffff04000000640000000000000000000000ffffffff
0000000000000000ffffffffffffffff04000000640000000000000000000000
ffffffff0000000000000000ffffffff01000000020000000000000004000000
0400000004000000000000000000000000000000000000000400000004000000
0400000000000000000000000000000000000000040000000400000004000000
0000000000000000000000000000000004000000040000000400000000000000
0000000000000000000000000400000004000000040000000000000000000000
0000000000000000040000000400000004000000000000000000000000000000
0000000004000000040000000400000000000000010000000000000000000000
040000000400000004000000000000000000000000000000000000000c000000
0c0000000c000000000000000000000002000000010000000c0000000c000000
0c00000000000000000000000200000001000000040000000400000004000000
0000000000000000000000000000000004000000040000000400000000000000
0000000000000000000000000400000004000000040000000000000000000000
0000000000000000000000000000000000000000040000000900000044454645
4e53455f310100000001000000ffffffffffffffffffffffffffffffff010000
0008000000434f4d4241545f310100000001000000ffffffffffffffffffffff
ffffffffff010000000b000000434f4d4241545f4245414d0000000001000000
ffffffffffffffffffffffffffffffff010000000c000000424f41524445525f
424f53530000000001000000ffffffffffffffffffffffffffffffff01000000
000000000000000000000000000000009cffffff9bffffff0000000000000000
0000000000000000090000000000000000000000000000000200000000000000
00000000ec5f00006f0c00001100000001000000133c0500c2c9fdffdd550500
97b1fdff906500008b1c0200e5b600009f16020000000000b002000000000000
00000000000000000000000000000000000000000000000000000000ffffffff
b002000000000000000000000000000000000000d00700000100000001000000
0100000000000000120000006578706c6f73696f6e5f6d697373696c65310c00
00006465627269735f736d616c6c00000000000000000000000000000000fa00
0000000000000000000000000000000000000000000000000000e80300000000
00000000000036e6ffff2a18000000000000000000000b000000666c616b496d
70616374340a000000686974536869656c6433040000006d6973732e01000000
000000000000000200000000000000d81c0f0080fc0a0001000000bd2f050095
f0fdff07490500e5d7fdff90650000a41e0200f9ee00000a12020000000000af
0200000000000000000000000000000000000000000000000000000000000000
000000ffffffffaf02000000000000000000000000000000000000d007000001
000000010000000100000000000000120000006578706c6f73696f6e5f6d6973
73696c65310c0000006465627269735f736d616c6c0000000000000000000000
0000000000fa0000000000000000000000000000000000000000000000000000
00e80300000000000000000000b6e6ffffb018000000000000000000000b0000
00666c616b496d70616374310a000000686974536869656c6432040000006d69
73732e0100000000000000000000020000000000000031c40f0080fc0a000100
0000330a0500dec7fdffdb240500a9b0fdff90650000d107020099660000cb1e
020000000000ae02000000000000000000000000000000000000000000000000
00000000000000000000ffffffffae0200000000000000000000000000000000
0000d007000001000000010000000100000000000000120000006578706c6f73
696f6e5f6d697373696c65310c0000006465627269735f736d616c6c00000000
000000000000000000000000fa00000000000000000000000000000000000000
0000000000000000e8030000000000000000000059e5ffff3517000000000000
000000000b000000666c616b496d70616374330a000000686974536869656c64
31040000006d6973732e0100000000000000000000020000000000000088cd12
0080fc0a0001000000f765050047f4fdff427e05006adafdff90650000064a02
008b4301005a08020000000000ad020000000000000000000000000000000000
0000000000000000000000000000000000ffffffffad02000000000000000000
000000000000000000d007000001000000010000000100000000000000120000
006578706c6f73696f6e5f6d697373696c65310c0000006465627269735f736d
616c6c01000000000000000000000024000000fa000000000000000000000000
000000000000000000000000000000e80300000000000000000000b5e7ffffdc
19000000000000000000000b000000666c616b496d70616374340a0000006869
74536869656c6432040000006d6973732e010000010000000000000002000000
00000000f092120080fc0a00010000006a1a050007dafdff7b34050029c2fdff
90650000520402007fad00003019020000000000ac0200000000000000000000
000000000000000000000000000000000000000000000000ffffffffac020000
00000000000000000000000000000000d0070000010000000100000001000000
00000000120000006578706c6f73696f6e5f6d697373696c65310c0000006465
627269735f736d616c6c00000000000000000000000000000000fa0000000000
00000000000000000000000000000000000000000000e8030000000000000000
0000f0e5ffffde17000000000000000000000b000000666c616b496d70616374
340a000000686974536869656c6433040000006d6973732e0100000000000000
00000002000000000000001170100080fc0a0001000000697005000e2dfeff59
8705002b12feff9065000044b0020064660100a5fd010000000000ab02000000
00000000000000000000000000000000000000000000000000000000000000ff
ffffffab02000000000000000000000000000000000000d00700000100000001
0000000100000000000000120000006578706c6f73696f6e5f6d697373696c65
310c0000006465627269735f736d616c6c000000000000000000000000000000
00fa000000000000000000000000000000000000000000000000000000e80300
00000000000000000010e9ffffe21a000000000000000000000b000000666c61
6b496d70616374310a000000686974536869656c6432040000006d6973732e01
00000000000000000000020000000000000010db130080fc0a0001000000e64b
0500470cfeff2a64050095f2fdff90650000886902001d1a0100f20802000000
0000aa0200000100000000000000000000000000000000000000000000000000
000000000000ffffffffaa02000000000000000000000000000000000000d007
000001000000010000000100000000000000120000006578706c6f73696f6e5f
6d697373696c65310a0000006465627269735f6d656400000000000000000000
000000000000e803000000000000000000000000000000000000000000000000
0000e80300000000000000000000bce7ffffb119000000000000000000000b00
0000666c616b496d70616374310a000000686974536869656c6431040000006d
6973732e0100000000000000000000020000000100000061b0110080fc0a0001
000000cc510500ce11feffd9690500e9f7fdff90650000921a02002688010015
07020000000000a9020000010000000000000000000000000000000000000000
0000000000000000000000ffffffffa902000000000000000000000000000000
000000d007000001000000010000000100000000000000120000006578706c6f
73696f6e5f6d697373696c65310a0000006465627269735f6d65640000000000
0000000000000000000000e80300000000000000000000000000000000000000
00000000000000e80300000000000000000000f3e7ffffe51900000000000000
0000000b000000666c616b496d70616374320a000000686974536869656c6431
040000006d6973732e0100000000000000000000020000000100000030291400
80fc0a0001000000e37705005f33feff8d8e05004118feff90650000ac980200
e8a2010064fb010000000000a802000001000000000000000000000000000000
00000000000000000000000000000000ffffffffa80200000000000000000000
0000000000000000d00700000100000001000000010000000000000012000000
6578706c6f73696f6e5f6d697373696c65310a0000006465627269735f6d6564
00000000000000000000000000000000e8030000000000000000000000000000
000000000000000000000000e8030000000000000000000056e9ffff1d1b0000
00000000000000000b000000666c616b496d70616374340a0000006869745368
69656c6432040000006d6973732e010000000000000000000002000000010000
0011e7110080fc0a0001000000cb4b05002e0cfeff106405007df2fdff906500
00f3dc01007cae0100fa08020000000000a70200000100000000000000000000
000000000000000000000000000000000000000000ffffffffa7020000000000
00000000000000000000000000d0070000010000000100000001000000000000
00120000006578706c6f73696f6e5f6d697373696c65310a0000006465627269
735f6d656400000000000000000000000000000000e803000000000000000000
0000000000000000000000000000000000e80300000000000000000000bbe7ff
ffb019000000000000000000000b000000666c616b496d70616374320a000000
686974536869656c6432040000006d6973732e01000000000000000000000200
000001000000f1270f0080fc0a00010000005b5d05005e1cfefffc7405001602
feff90650000e49902001c2f01007a03020000000000a6020000010000000000
0000000000000000000000000000000000000000000000000000ffffffffa602
000000000000000000000000000000000000d007000001000000010000000100
000000000000120000006578706c6f73696f6e5f6d697373696c65310c000000
6465627269735f6c6172676500000000000000000000000000000000e8030000
000000000000000000000000000000000000000000000000e803000000000000
000000005fe8ffff471a000000000000000000000b000000666c616b496d7061
6374330a000000686974536869656c6433040000006d6973732e010000000000
0000000000020000000100000068f6130080fc0a000100000080fb040094b6fd
ffb016050000a0fdff9065000080b20100f47000000524020000000000a50200
0001000000000000000000000000000000000000000000000000000000000000
00ffffffffa502000000000000000000000000000000000000d0070000010000
00010000000100000000000000120000006578706c6f73696f6e5f6d69737369
6c65310c0000006465627269735f6c6172676500000000000000000000000000
000000e8030000000000000000000000000000000000000000000000000000e8
0300000000000000000000d0e4ffff9416000000000000000000000b00000066
6c616b496d70616374330a000000686974536869656c6433040000006d697373
2e01000000000000000000000200000001000000b1850f0080fc0a0001000000
98490500180afefff26105007bf0fdff9065000051bd020045b80000ad090200
00000000a4020000010000000000000000000000000000000000000000000000
0000000000000000ffffffffa402000000000000000000000000000000000000
d007000001000000010000000100000000000000120000006578706c6f73696f
6e5f6d697373696c65310c0000006465627269735f6c61726765000000000000
00000000000000000000e8030000000000000000000000000000000000000000
000000000000e80300000000000000000000a7e7ffff9d190000000000000000
00000b000000666c616b496d70616374310a000000686974536869656c643304
0000006d6973732e01000000000000000000000200000001000000b1fc100080
fc0a00010000009bdd040066d5050083070500901e060060ea0000e022020070
110100072cfeff00000000b10200000100000000000000010000000000000000
000000000000000000000000000000ffffffffb1020000000000000000000000
00000000000000d0070000010000000100000001000000000000001200000065
78706c6f73696f6e5f6d697373696c65310c0000006c617365725f6c69676874
3101000000000000000500000098020000e80300000000000000000000010000
000100000000000000ae000000e8030000000000000000000019d6ffffd6b6ff
ff00000000010000000800000068697448756c6c330a00000068697453686965
6c6432040000006d6973733b0000000100000000000000040000000000000000
00000000000000010000008e690500b115feff726505005267feff60ea0000f6
6b0500f1e5fdffb3abfeff01000000b402000001000000000000000100000000
00000000000000000000000000000000000000ffffffffb40200000000000000
0000000000000000000000d00700000100000001000000010000000000000012
0000006578706c6f73696f6e5f6d697373696c65310c0000006c617365725f6c
696768743101000000000000000000000048000000e803000000000000000000
0001000000010000000000000082000000e803000000000000000000001c0400
005faeffff01000000000000000800000068697448756c6c320a000000686974
536869656c6431040000006d697373ffffffff01000000000000000400000000
0000000000000000000000010000000ab10300dbceffff8d990300f51c000060
ea000098ab020050340300d0e1feff00000000b5020000010000000000000001
0000000000000000000000000000000000000000000000ffffffffb502000000
000000000000000000000000000000d007000001000000010000000100000000
000000120000006578706c6f73696f6e5f6d697373696c65310c0000006c6173
65725f6c696768743100000000000000000000000000000000e8030000000000
000000000001000000010000000000000057000000e803000000000000000000
007c170000e6b1ffff01000000000000000800000068697448756c6c330a0000
00686974536869656c6431040000006d697373ffffffff000000000100000004
00000000000000000000000000000003000000999d0900683c0100066e090068
3c0100b8880000e0220200701101000000000000000000b30200000200000005
000000010000000100000000000000000000000000000000000000ffffffffb3
02000000000000000000000100000000000000d0070000010000000000000001
000000000000000e0000006578706c6f73696f6e5f62696732090000006d6973
73696c655f3200000000000000000000000000000000e8030000000000000000
000000000000000000000000000000000000e80300000000000000000000932f
00000000000000000000000000000e000000736d616c6c4578706c6f73696f6e
0a000000686974536869656c6431040000006d69737341010000000000000000
00000100000000000000
[/code]

**Comment by Vhati** [comment]
Sorry about that. I believe this is a bug that will be fixed in the next version.

For saved games created while any missiles/asteroids/explosions were on-screen, v25 of the editor may corrupt 'continue.sav' when writing changes back to disk. Thereafter, attempting to open that file will cause errors.

**Comment by Champteach** [comment]
Thank you very much

**Comment by Vhati** [comment]
Fixed in v26.
