### ISSUE TITLE
SavedGame Parser Error

### ISSUE THREAD

**Issue by efalder413** [Vhati/ftl-profile-editor#77]
[code]
SavedGame Parser Error

Exception: java.lang.RuntimeException: End of stream reached before reading enough bytes for an int

Stack Trace...
  net.blerf.ftl.parser.Parser.readInt(Parser.java:43)
  net.blerf.ftl.parser.SavedGameParser.readProjectile(SavedGameParser.java:1646)
  net.blerf.ftl.parser.SavedGameParser.readZeus(SavedGameParser.java:9238)
  net.blerf.ftl.parser.SavedGameParser.readSavedGame(SavedGameParser.java:244)
  net.blerf.ftl.ui.FTLFrame$11.actionPerformed(FTLFrame.java:802)

Editor Version: 25
OS: Windows 10 10.0
VM: Java HotSpot(TM) 64-Bit Server VM, 1.8.0_66, amd64
[/code]

File ("continue.sav")...
[code]
070000000100000000000000170000004e000000680500000b0000000a000000
546865204f73707265790f000000504c415945525f534849505f464544080000
00000000000f0000000a000000626c75655f616c69656e020000000900000064
6561645f63726577010000000a000000656e765f64616e676572060000000a00
000066697265645f73686f744c01000006000000686967686f32020000000b00
00006b696c6c65645f6372657715000000090000006c6f73745f637265770400
0000060000006e6562756c610c0000000f00000072656163746f725f75706772
616465010000000e00000073746f72655f7075726368617365830000000c0000
0073746f72655f726570616972060000000e00000073797374656d5f75706772
6164650c0000000a000000757365645f64726f6e65120000000c000000757365
645f6d697373696c650d0000000e000000776561706f6e5f7570677261646501
0000000f000000504c415945525f534849505f4645440a000000546865204f73
707265790b0000006665645f63727569736572040000000500000068756d616e
0d0000004c6f67616e204a6f686e736f6e060000006d616e746973070000004a
756e70656e6704000000726f636b06000000547572696e6704000000656e6769
050000004d616e6f6e01000000084c01000000000000000000100000002f0000
00340000001f0000001c1c000008000000070000004a756e70656e6706000000
6d616e746973000000005500000057000000c000000003000000020000000100
000001000000ffffffff01000000010000000000000002000000030000000000
00001e0000000000000000000000010000000000000001000000010000000000
0000000000004f000000020000000000000000000000ffffffffe80300000000
0000420000000000000001000000000000000000000000000000e80300000000
0000000000000000000006000000547572696e6704000000726f636b00000000
96000000fb0100007a0000000f000000010000000100000001000000ffffffff
010000000100000000000000010000000f000000000000000000000000000000
820000000200000002000000010000000200000002000000000000004f000000
020000000000000000000000ffffffffe8030000000000004200000000000000
01000000000000000000000000000000e8030000000000000000000000000000
050000004d616e6f6e04000000656e67690000000064000000b50100009d0000
000d000000010000000100000001000000ffffffff0000000000000000010000
000d000000000000000000000008000000000000000000000002000000000000
000000000002000000000000004f000000000000000000000000000000ffffff
ffe8030000000000004200000000000000010000000000000000000000000000
00e80300000000000000000000000000000400000052656d6f04000000656e67
69000000002b0000009d0000009d000000040000000000000001000000010000
00ffffffff000000000000000000000000040000001e00000000000000000000
000000000003000000000000000100000003000000000000003d0000004b0000
00020000000000000000000000ffffffffe80300000000000042000000000000
0001000000000000000000000000000000e80300000000000000000000000000
000f0000004d696b61656c204f6c6f6673736f6e0500000068756d616e000000
0046000000c00000007a00000008000000000000000100000001000000ffffff
ff02000000000000000000000000000000000000000800000000000000000000
0000000000000000000100000001000000010000000100000001000000000000
004b000000000000000000000000000000ffffffffe803000000000000420000
000000000001000000000000000000000000000000e803000000000000000000
00000000000700000056696e63656e74060000006d616e746973000000006400
0000570000000601000006000000000000000100000001000000ffffffff0100
0000020000000000000000000000060000000000000000000000000000000000
00000100000000000000010000000100000001000000000000003d0000000000
00000000000000000000ffffffffe80300000000000042000000000000000100
0000000000000000000000000000e80300000000000000000000000000000400
00004c69616d04000000656e67690000000055000000c0000000c00000000900
0000000000000100000001000000ffffffff0000000000000000000000000900
0000000000000000000000000000000000000300000000000000010000000300
0000000000000000000037000000000000000000000000000000ffffffffe803
000000000000420000000000000001000000000000000000000000000000e803
000000000000000000000000000007000000436861726c69650500000068756d
616e0000000055000000290100009d0000000b00000000000000010000000100
0000ffffffff02000000000000000300000000000000000000000b0000000000
0000000000003700000000000000010000000700000001000000010000000000
0000000000002a000000010000000000000000000000ffffffffe80300000000
0000420000000000000001000000000000000000000000000000e80300000000
0000000000000000000019000000080000000800000000000000000000000000
00000000000000000000000000000000000000000000e8030000000000000100
0000080000000100000000000000000000000000000000000000000000000000
00000000000000000000e8030000000000000100000003000000010000000000
000000000000000000000000000000000000000000000000000000000000e803
0000000000000100000008000000080000000000000000000000000000000000
000000000000000000000100000001000000e803000000000000010000000800
0000010000000000000000000000000000000000000000000000000000000000
000000000000e803000000000000010000000000000003000000030000000000
000000000000000000000000000000000000000000000000000000000000e803
0000000000000100000003000000020000000000000000000000000000000000
0000000000000000000000000000000000000200000000000000010000000300
0000020000000100000000000000000000000900000000000000000000000000
000000000000e803000000000000010000000000000000000000040000000200
0000000000000000000000000000000000000000000000000000000000000000
0000e80300000000000001000000020000000200000000000000000000000000
00000000000000000000000000000000000000000000e8030000000000000100
0000030000000100000001000000000000000000000000000000000000000000
00000000000000000000e8030000000000000100000003000000000000000000
000000000000000000000000000000000000000000000000000000000000e803
000000000000010000000000000000000000e02e000018fcffff000000000000
0000000000000400000000000000000000000000000000000000000000000100
0000e80300000000000000000000b1210900c61c010064000000000000000000
0000ffffffff0000000000000000ffffffffffffffff04000000640000000000
000000000000ffffffff0000000000000000ffffffffffffffff040000006400
00000000000000000000ffffffff0000000000000000ffffffffffffffff0400
0000640000000000000000000000ffffffff0000000000000000ffffffff0000
000000000000ffffffff0000000000000000ffffffff02000000000000006400
00000000000000000000ffffffff0000000000000000ffffffff000000000100
0000640000000000000000000000ffffffff0000000000000000ffffffffffff
ffff04000000640000000000000000000000ffffffff0000000000000000ffff
ffffffffffff04000000640000000000000000000000ffffffff000000000000
0000ffffffffffffffff04000000640000000000000000000000ffffffff0000
000000000000ffffffff0000000001000000640000000000000000000000ffff
ffff0000000000000000ffffffffffffffff0400000000000000000000000000
0000ffffffff0000000000000000ffffffff0000000000000000ffffffff0000
000000000000ffffffffffffffff04000000640000000000000000000000ffff
ffff0000000000000000ffffffff0000000000000000ffffffff000000000000
0000ffffffff0000000003000000640000000000000000000000ffffffff0000
000000000000ffffffffffffffff04000000640000000000000000000000ffff
ffff0000000000000000ffffffff010000000000000064000000000000000000
0000ffffffff0000000000000000ffffffffffffffff04000000640000000000
000000000000ffffffff0000000000000000ffffffff0000000000000000ffff
ffff0000000000000000ffffffff010000000200000064000000000000000000
0000ffffffff0000000000000000ffffffff0000000000000000ffffffff0000
000000000000ffffffffffffffff04000000640000000000000000000000ffff
ffff0000000000000000ffffffffffffffff0400000001000000070000000500
0000640000000c0000000c0000000c0000000000000000000000010000000000
00000c0000000c0000000c000000000000000000000001000000000000000c00
00000c0000000c000000000000000000000001000000000000000c0000000c00
00000c000000000000000000000001000000000000000c0000000c0000000c00
0000000000000000000001000000000000000c0000000c0000000c0000000000
00000000000001000000000000000c0000000c0000000c000000000000000000
000001000000000000000c0000000c0000000c00000000000000000000000100
0000000000000c0000000c0000000c0000000000000000000000010000000000
00000c0000000c0000000c000000000000000000000001000000000000000c00
00000c0000000c000000000000000000000001000000000000000c0000000c00
00000c000000000000000000000001000000000000000c0000000c0000000c00
0000000000000000000001000000000000001000000010000000100000000000
00000000000002000000010000000c0000000c0000000c000000000000000000
000001000000000000000c0000000c0000000c00000000000000000000000100
0000000000001000000010000000100000000000000000000000020000000100
00000c0000000c0000000c000000000000000000000001000000000000000c00
00000c0000000c00000000000000000000000100000000000000100000001000
000010000000000000000000000002000000010000000c0000000c0000000c00
0000000000000000000001000000000000000c0000000c0000000c0000000000
00000000000001000000000000000c0000000c0000000c000000000000000000
000001000000000000000c0000000c0000000c00000000000000000000000100
0000000000000c0000000c0000000c0000000000000000000000010000000000
00000c0000000c0000000c000000000000000000000001000000000000000000
0000030000000e0000004c415345525f434841494e47554e0100000010000000
4c415345525f434841494e47554e5f3201000000090000004245414d5f4c4f4e
4701000000020000000600000052455041495201000000010000006f010000bd
0000000c000000000000001900000009000000444546454e53455f3200000000
00000000ffffffffffffffffffffffffffffffff01000000030000000a000000
4241434b55505f444e410b0000004e414e4f5f4d45444241590f000000534849
454c445f524543484152474500000000bc7f0000b70b00003c000000c8000000
000000000e00000000000000ffffffff00000000000000000100000002000000
0000000000000000000000001200000001000000000000000100000000000000
0000000001000000000000000000000001000000000000000100000000000000
0000000001000000000000000100000000000000010000000700000000000000
18000000010000001700000073746172732f62675f6c6f6e656c79737461722e
706e671400000073746172732f706c616e65745f7265642e706e67050000000b
0000000000000001000000000000000200000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000100000000000000000000000000000000000000000000000000000000
000000010000001700000073746172732f62675f6461726b6e6562756c612e70
6e671b00000073746172732f706c616e65745f6761735f79656c6c6f772e706e
67a9010000f8000000b400000001000000000000000200000000000000000000
0000000000010000000000000000000000000000000000000000000000000000
0000000000030000000000000000000000000000000000000000000000010000
000000000000000000010000001700000073746172732f62675f6c6f6e656c79
737461722e706e671600000073746172732f706c616e65745f70656163682e70
6e67e9010000ae000000b400000001000000010000000a0000004c4f4e475f46
4c4545541100000053484950535f524542454c5f454c495445401b0000010000
000000000000000000010000001a00000073746172732f62675f6c6f6e656c79
526564537461722e706e671400000073746172732f706c616e65745f7265642e
706e6787030000dd000000b40000000100000000000000000000000000000000
0000000000000001000000000000000000000000000000000000000000000001
0000000000000000000000000000000000000000000000010000000000000000
0000000000000000000000000000000100000000000000000000000000000000
000000010000001700000073746172732f62675f6461726b6e6562756c612e70
6e671600000073746172732f706c616e65745f62726f776e2e706e67df000000
1d0000000000000001000000010000000a0000004c4f4e475f464c4545541100
000053484950535f524542454c5f454c495445ec1d0000010000000000000000
0000000000000001000000000000000000000000000000000000000000000000
0000000000000001000000000000000000000000000000000000000000000001
0000000000000000000000000000000100000000000000010000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000002000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000010000000000000000
0000000000000000000000000000000000000001000000000000000000000000
0000000000000027790000100000005049524154455f53555252454e4445520d
0000005049524154455f4553434150451100000044455354524f5945445f4445
4641554c5411000000444541445f435245575f44454641554c54150000005049
5241544520676f742061776179202031323132000000009d0000005468697320
69732069742e2e2e2054686520526562656c20666c6167736869702e20496620
796f75206172652061626c6520746f2064657374726f792074686973206d6f6e
7374726f736974792c207468652046656465726174696f6e20666c6565742077
696c6c20686176652061206368616e6365206f6620737572766976696e672e20
54686572652773206e6f207475726e696e67206261636b21ffffffff01000000
0000000001000000010000000f000000424f53535f315f454153595f444c4312
00000073686f756c64206e6f74206265207365656e06000000626f73735f310b
0000000500000068756d616e060000004d61726b656c0500000068756d616e06
000000417274796f6d0500000068756d616e0e00000053746576656e2044656e
676c65720500000068756d616e0400000059656f7a0500000068756d616e0500
00004e696b6d690500000068756d616e05000000526f7065720500000068756d
616e050000004265726b6f0500000068756d616e06000000446176696f6e0500
000068756d616e08000000566976696d6f72640500000068756d616e09000000
4a616e204d61676e650500000068756d616e060000004e617468616e01000000
0000000000000000000000000a00000010000000030000000a0000001e000000
16000000060000004d61726b656c0500000068756d616e0000000000000000c0
00000011000000ffffffffffffffff0000000000000000430000000200000000
0000000300000000000000ffffffffffffffff00000000000000000000000000
0000000000000000000000010000000000000000000000000000000000000000
000000000000000000000043000000e803000000000000420000000000000001
000000000000000000000000000000e803000000000000000000000000000006
000000417274796f6d0500000068756d616e00000000000000007a0000003400
0000ffffffffffffffff00000000000000004400000002000000000000000100
000000000000ffffffffffffffff000000000000000000000000000000000000
0000000000000100000000000000000000000000000000000000000000000000
00000000000044000000e8030000000000004200000000000000010000000000
00000000000000000000e80300000000000000000000000000000e0000005374
6576656e2044656e676c65720500000068756d616e0000000000000000290100
0034000000ffffffffffffffff00000000000000004500000002000000000000
000100000000000000ffffffffffffffff000000000000000000000000000000
0000000000000000000100000000000000000000000000000000000000000000
00000000000000000045000000e8030000000000004200000000000000010000
00000000000000000000000000e8030000000000000000000000000000040000
0059656f7a0500000068756d616e0000000000000000c000000034000000ffff
ffffffffffff0000000000000000460000000200000000000000010000000000
0000ffffffffffffffff00000000000000000000000000000000000000000000
0000010000000000000000000000000000000000000000000000000000000000
000046000000e803000000000000420000000000000001000000000000000000
000000000000e8030000000000000000000000000000050000004e696b6d6905
00000068756d616e0000000000000000c00000004c010000ffffffffffffffff
00000000000000004700000002000000000000000000000000000000ffffffff
ffffffff00000000000000000000000000000000000000000000000001000000
0000000000000000000000000000000000000000000000000000000047000000
e803000000000000420000000000000001000000000000000000000000000000
e803000000000000000000000000000005000000526f7065720500000068756d
616e0000000000000000c000000006010000ffffffffffffffff000000000000
00004800000002000000000000000000000000000000ffffffffffffffff0000
0000000000000000000000000000000000000000000001000000000000000000
0000000000000000000000000000000000000000000048000000e80300000000
0000420000000000000001000000000000000000000000000000e80300000000
00000000000000000000050000004265726b6f0500000068756d616e00000000
0000000057000000c0000000ffffffffffffffff000000000000000049000000
02000000000000000200000000000000ffffffffffffffff0000000000000000
0000000000000000000000000000000001000000000000000000000000000000
0000000000000000000000000000000049000000e80300000000000042000000
0000000001000000000000000000000000000000e80300000000000000000000
0000000006000000446176696f6e0500000068756d616e000000000000000011
0000009d000000ffffffffffffffff00000000000000004a0000000200000000
0000000200000000000000ffffffffffffffff00000000000000000000000000
0000000000000000000000010000000000000000000000000000000000000000
00000000000000000000004a000000e803000000000000420000000000000001
000000000000000000000000000000e803000000000000000000000000000008
000000566976696d6f72640500000068756d616e00000000000000009d000000
c0000000ffffffffffffffff00000000000000004b0000000200000000000000
0000000000000000ffffffffffffffff00000000000000000000000000000000
0000000000000000010000000000000000000000000000000000000000000000
00000000000000004b000000e803000000000000420000000000000001000000
000000000000000000000000e803000000000000000000000000000009000000
4a616e204d61676e650500000068756d616e00000000000000009d0000007a00
0000ffffffffffffffff00000000000000004c00000002000000000000000100
000000000000ffffffffffffffff000000000000000000000000000000000000
0000000000000100000000000000000000000000000000000000000000000000
0000000000004c000000e8030000000000004200000000000000010000000000
00000000000000000000e8030000000000000000000000000000060000004e61
7468616e0500000068756d616e00000000000000009201000057000000ffffff
ffffffffff00000000000000004d000000020000000000000002000000000000
00ffffffffffffffff0000000000000000000000000000000000000000000000
0001000000000000000000000000000000000000000000000000000000000000
004d000000e80300000000000042000000000000000100000000000000000000
0000000000e8030000000000000000000000000000060000004d61726b656c05
00000068756d616e0000000064000000c0000000110000000000000000000000
0000000000000000ffffffff02000000000000000200000000000000ffffffff
ffffffff00000000000000000000000000000000000000000000000001000000
00000000000000000b00000000000000000000000000000000000000ffffffff
e803000000000000420000000000000001000000000000000000000000000000
e803000000000000000000000000000006000000417274796f6d050000006875
6d616e0000000064000000c0000000c000000005000000010000000000000000
000000ffffffff02000000000000000200000000000000ffffffffffffffff00
0000000000000000000000000000000000000000000000010000000100000000
0000000000000000000000000000000000000000000000ffffffffe803000000
000000420000000000000001000000000000000000000000000000e803000000
00000000000000000000000e00000053746576656e2044656e676c6572050000
0068756d616e0000000064000000110000009d0000000f000000000000000000
000000000000ffffffff02000000000000000100000000000000ffffffffffff
ffff000000000000000000000000000000000000000000000000010000000100
0000000000000000000000000000000000000000000000000000ffffffffe803
000000000000420000000000000001000000000000000000000000000000e803
00000000000000000000000000000400000059656f7a0500000068756d616e00
00000064000000c00000005700000001000000020000000000000000000000ff
ffffff02000000000000000200000000000000ffffffffffffffff0000000000
0000000000000000000000000000000000000001000000010000000000000000
00000000000000000000000000000000000000ffffffffe80300000000000042
0000000000000001000000000000000000000000000000e80300000000000000
00000000000000050000004e696b6d690500000068756d616e00000000640000
00c00000000601000007000000000000000000000000000000ffffffff020000
00000000000300000000000000ffffffffffffffff0000000000000000000000
0000000000000000000000000001000000010000000000000000000000000000
00000000000000000000000000ffffffffe80300000000000042000000000000
0001000000000000000000000000000000e80300000000000000000000000000
0005000000526f7065720500000068756d616e0000000064000000e30000004c
01000008000000030000000000000000000000ffffffff020000000000000000
00000000000000ffffffffffffffff0000000000000000000000000000000000
0000000000000001000000020000000000000000000000000000000000000000
00000000000000ffffffffe80300000000000042000000000000000100000000
0000000000000000000000e80300000000000000000000000000000500000042
65726b6f0500000068756d616e000000006400000057000000c0000000110000
00000000000000000000000000ffffffff020000000000000000000000000000
00ffffffffffffffff0000000000000000000000000000000000000000000000
0001000000000000000000000000000000000000000000000000000000000000
00ffffffffe80300000000000042000000000000000100000000000000000000
0000000000e803000000000000000000000000000006000000446176696f6e05
00000068756d616e00000000640000007a000000340000000900000000000000
0000000000000000ffffffff02000000000000000000000000000000ffffffff
ffffffff00000000000000000000000000000000000000000000000001000000
00000000000000000000000000000000000000000000000000000000ffffffff
e803000000000000420000000000000001000000000000000000000000000000
e803000000000000000000000000000008000000566976696d6f726405000000
68756d616e000000006400000029010000340000000a00000000000000000000
0000000000ffffffff02000000000000000200000000000000ffffffffffffff
ff00000000000000000000000000000000000000000000000001000000020000
00000000000000000000000000000000000000000000000000ffffffffe80300
0000000000420000000000000001000000000000000000000000000000e80300
00000000000000000000000000090000004a616e204d61676e65050000006875
6d616e000000006400000092010000570000000e000000010000000000000000
000000ffffffff02000000000000000000000000000000ffffffffffffffff00
0000000000000000000000000000000000000000000000010000000000000000
0000000000000000000000000000000000000000000000ffffffffe803000000
000000420000000000000001000000000000000000000000000000e803000000
0000000000000000000000060000004e617468616e0500000068756d616e0000
000064000000110000005700000012000000000000000000000000000000ffff
ffff02000000000000000300000000000000ffffffffffffffff000000000000
0000000000000000000000000000000000000100000001000000000000000000
000000000000000000000000000000000000ffffffffe8030000000000004200
00000000000001000000000000000000000000000000e8030000000000000000
0000000000002a00000008000000080000000000000000000000000000000000
000000000000000000000000000000000000e803000000000000010000000200
0000020000000000000000000000000000000000000000000000000000000000
000000000000e803000000000000010000000200000002000000000000000000
0000000000000000000000000000000000000000000000000000e80300000000
0000010000000000000000000000030000000300000000000000000000000000
00000000000000000000000000000000000000000000e8030000000000000100
0000030000000300000000000000000000000000000000000000000000000000
00000000000000000000e8030000000000000100000000000000030000000300
0000000000000000000000000000000000000000000000000000000000000000
0000e8030000000000000100000000000000020000000200000000000000ffff
ffff000000000000000000000000000000000000000000000000e80300000000
0000010000000300000003000000000000000000000000000000000000000000
0000000000000000000000000000e80300000000000001000000030000000300
0000000000000000000000000000000000000000000000000000000000000000
0000e80300000000000001000000030000000300000000000000000000000000
00000000000000000000000000000000000000000000e8030000000000000100
0000030000000300000000000000000000000000000000000000000000000000
00000000000000000000e8030000000000000100000000000000000000000000
0000030000000300000000000000040000006658000000000000000000000000
00000000000000000000e8030000000000000100000004000000000000000000
000000000000000000000000000001000000e803000000000000000000000000
0000000000000100000001000000102700006003000064000000640000000000
0000ffffffff6400000000000000ffffffff0000000002000000640000006400
000000000000ffffffff6400000000000000ffffffff6400000000000000ffff
ffff6400000000000000ffffffff020000000000000064000000640000000000
0000ffffffff6400000000000000ffffffffffffffff04000000640000006400
000000000000ffffffff6400000000000000ffffffffffffffff040000006400
00006400000000000000ffffffff6400000000000000ffffffffffffffff0400
0000640000006400000000000000ffffffff6400000000000000ffffffff0000
000000000000ffffffff6400000000000000ffffffffffffffff040000006400
00006400000000000000ffffffff6400000000000000ffffffff640000000000
0000ffffffff6400000000000000ffffffffffffffff04000000640000006400
000000000000ffffffff6400000000000000ffffffffffffffff040000006400
00006400000000000000ffffffff6400000000000000ffffffff640000000000
0000ffffffff6400000000000000ffffffff0300000001000000640000006400
000000000000ffffffff6400000000000000ffffffff00000000020000006400
00006400000000000000ffffffff6400000000000000ffffffff000000000200
0000640000006400000000000000ffffffff6400000000000000ffffffffffff
ffff04000000640000006400000000000000ffffffff6400000000000000ffff
ffff6400000000000000ffffffff6400000000000000ffffffffffffffff0400
0000640000006400000000000000ffffffff6400000000000000ffffffffffff
ffff04000000640000006400000000000000ffffffff6400000000000000ffff
ffff0100000002000000640000006400000000000000ffffffff640000000000
0000ffffffff6400000000000000ffffffff6400000000000000ffffffffffff
ffff04000000640000006400000000000000ffffffff6400000000000000ffff
ffffffffffff04000000640000006400000000000000ffffffff640000000000
0000ffffffff0000000002000000640000006400000000000000ffffffff6400
000000000000ffffffff00000000020000000000000014000000140000001400
0000000000000000000003000000000000001400000014000000140000000000
0000000000000300000000000000140000001400000014000000000000000000
0000030000000000000014000000140000001400000000000000000000000300
0000000000001400000014000000140000000000000000000000030000000000
0000140000001400000014000000000000000000000003000000000000001400
0000140000001400000000000000000000000300000000000000140000001400
0000140000000000000000000000030000000000000014000000140000001400
0000000000000000000003000000000000001400000014000000140000000000
0000000000000300000000000000140000001400000014000000000000000000
0000030000000000000014000000140000001400000000000000000000000300
0000000000001400000014000000140000000000000000000000030000000000
0000140000001400000014000000000000000000000003000000000000001400
0000140000001400000000000000000000000300000000000000f40100000000
000000000000000000000000000000000000000000009cffffff9bffffff0000
00000000000000000000000000000b0000000000000000000000000000000200
00000000000000000000623f0000000000000800000001000000d8d00100eb9f
f5ffd8d001006dbef5ff60ea0000289a010098ab0200b01e0400010000007c00
0000010000000000000001000000010000000000000000000000000000000000
0000ffffffffffffffff00000000000000000000000000000000d00700000000
0000010000000000000000000000120000006578706c6f73696f6e5f6d697373
696c65310c0000006c617365725f686561767931000000000000000000000000
00000000e803000000000000000000000100000001000000010000006f010000
e80300000000000000000000000000007ee1ffff000000000000000008000000
68697448756c6c310a000000686974536869656c6433040000006d697373c100
000000000000000000000400000000000000000000000000000001000000007d
00001ed6faff007d000075eafaff409c000000ee020050340300b01e04000100
00007f0000000000000000000000000000000000000001000000000000000000
000000000000ffffffffffffffff00000000000000000000000000000000d007
000000000000010000000000000000000000120000006578706c6f73696f6e5f
6d697373696c65310a000000696f6e5f345f73686f7400000000000000000000
000000000000e803000000000000000000000100000001000000070000007803
0000e8030000000000000000000000000000aaebffff00000000000000000700
0000696f6e486974330b000000696f6e536869656c647332040000006d697373
e700000000000000000000000400000000000000000000000000000001000000
d8d001004b5df9ffd8d00100cd7bf9ff60ea0000a068060048650200b01e0400
010000007b000000010000000000000001000000010000000000000000000000
0000000000000000ffffffffffffffff00000000000000000000000000000000
d007000000000000010000000000000000000000120000006578706c6f73696f
6e5f6d697373696c65310c0000006c617365725f686561767931000000000000
00000000000000000000e8030000000000000000000001000000010000000300
000064030000e80300000000000000000000000000007ee1ffff000000000000
00000800000068697448756c6c310a000000686974536869656c643204000000
6d697373c1000000000000000000000004000000000000000000000000000000
01000000007d0000c953fdff007d00002068fdff409c000000ee0200e0220200
b01e0400010000007e0000000000000000000000000000000000000001000000
000000000000000000000000ffffffffffffffff000000000000000000000000
00000000d007000000000000010000000000000000000000120000006578706c
6f73696f6e5f6d697373696c65310a000000696f6e5f345f73686f7400000000
000000000000000000000000e803000000000000000000000100000001000000
0000000037000000e8030000000000000000000000000000aaebffff00000000
0000000007000000696f6e486974330b000000696f6e536869656c6473320400
00006d697373e700000000000000000000000400000000000000000000000000
000003000000e09304006b46fdffe09304003758fdffb8880000107a0700e022
0200b01e04000100000082000000010000000500000003000000020000000000
0000000000000000000000000000ffffffffffffffff00000000000000000000
000000000000d0070000000000000100000000000000000000000e0000006578
706c6f73696f6e5f62696734090000006d697373696c655f3100000000000000
000000000000000000e803000000000000000000000000000000000000000000
0000000000e803000000000000000000000000000035eeffff00000000000000
000e000000736d616c6c4578706c6f73696f6e0a000000686974536869656c64
32040000006d6973735d01000000000000000000000100000000000000
[/code]

**Comment by efalder413** [comment]
FTL also crashes when loading this save. All I changed was adding fires to the Flagship.

**Comment by Vhati** [comment]
For saved games created while any missiles/asteroids/explosions were on-screen, v25 of the editor may corrupt 'continue.sav' when writing changes back to disk. Thereafter, attempting to open that file will cause errors.

This will be corrected in the next version. Thank you for reporting. Sorry about that.

**Comment by Vhati** [comment]
Fixed in v26.
