### ISSUE TITLE
Saved Game Parser Error

### ISSUE THREAD

**Issue by teepee2345** [Vhati/ftl-profile-editor#78]
This is what happened when i was editing my ship during the boss level. It gave me an error message saying the issue was the line: "Projectile Info:             N/A"

[code]
SavedGame Parser Error

Exception: java.lang.RuntimeException: End of stream reached before reading enough bytes for an int

Stack Trace...
  net.blerf.ftl.parser.Parser.readInt(Parser.java:43)
  net.blerf.ftl.parser.SavedGameParser.readProjectile(SavedGameParser.java:1646)
  net.blerf.ftl.parser.SavedGameParser.readZeus(SavedGameParser.java:9238)
  net.blerf.ftl.parser.SavedGameParser.readSavedGame(SavedGameParser.java:244)
  net.blerf.ftl.ui.FTLFrame$11.actionPerformed(FTLFrame.java:802)

Editor Version: 25
OS: Windows 10 10.0
VM: Java HotSpot(TM) Client VM, 1.8.0_60, x86
[/code]

File ("continue.sav")...
[code]
090000000100000000000000110000003d0000009a0400000700000012000000
73686f756c64206e6f74206265207365656e0f000000424f53535f315f454153
595f444c4308000000000000001000000009000000646561645f637265770800
00000e00000064657374726f7965645f726f636b010000000a000000656e765f
64616e676572020000000a00000066697265645f73686f748f01000006000000
686967686f32010000000b0000006b696c6c65645f6372657726000000090000
006c6f73745f6372657703000000060000006e6562756c610a0000000f000000
6f6666656e736976655f64726f6e65090000000f00000072656163746f725f75
706772616465010000000e00000073746f72655f70757263686173650d000000
0c00000073746f72655f726570616972040000000f000000737566666f636174
65645f63726577d10c00000e00000073797374656d5f757067726164650e0000
000a000000757365645f64726f6e651d0000000e000000776561706f6e5f7570
6772616465020000000f000000424f53535f315f454153595f444c4312000000
73686f756c64206e6f74206265207365656e06000000626f73735f3100000000
01000000084c0100000000000000000014000000803e00000f27000010270000
e0740000080000000600000053636f6f70730500000068756d616e0000000064
000000e30000003400000001000000010000000100000000000000ffffffff02
0000000000000001000000000000000000000001000000000000000000000064
00000000000000200000000e0000000100000000000000000000000000000000
000000000000000000000000000000ffffffffe8030000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000001000000000000000000000000
000000e803000018fcffff18fcffff0000000005000000426967627905000000
68756d616e0000000064000000c0000000110000000000000000000000010000
0000000000ffffffff0200000000000000020000000000000001000000000000
001a000000000000000000000000000000200000000e00000001000000000000
00000000000b00000000000000000000000000000000000000ffffffffe80300
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000010000
00000000000000000000000000e803000018fcffff18fcffff00000000070000
005368656c746f6e0500000068756d616e0000000064000000e3000000290100
0008000000010000000100000000000000ffffffff0200000000000000010000
00000000000100000008000000000000001a0000000000000000000000200000
000e000000010000000000000000000000000000000000000000000000000000
0000000000ffffffffe803000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
00000000000000000001000000000000000000000000000000e803000018fcff
ff18fcffff0000000007000000427574746572730500000068756d616e000000
004200000092010000570000000e000000010000000100000000000000ffffff
ff02000000000000000000000000000000000000000e00000000000000000000
000000000074000000200000000e000000010000000100000000000000000000
0000000000000000000000000000000000ffffffffe803000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000100000000000000000000
0000000000e803000018fcffff18fcffff0000000008000000566976696d6f72
640500000068756d616e000000006400000029010000340000000a0000000000
00000100000000000000ffffffff020000000000000002000000000000000100
00000a00000000000000000000000000000074000000200000000e0000000100
000000000000000000000000000000000000000000000000000000000000ffff
ffffe80300000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
000001000000000000000000000000000000e803000018fcffff18fcffff0000
0000070000004d6f6e7376696b0500000068756d616e00000000d00700007a00
00003400000009000000000000000100000000000000ffffffff020000000000
0000010000000000000001000000090000000000000000000000000000007400
0000200000000e00000001000000000000000000000000000000000000000000
00000000000000000000ffffffffe80300000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000001000000000000000000000000000000e803
000018fcffff18fcffff0000000005000000537469636b0500000068756d616e
00000000d0070000110000005700000012000000000000000100000000000000
ffffffff02000000000000000300000000000000010000001200000000000000
000000000000000074000000200000000e000000010000000000000000000000
0000000000000000000000000000000064000000ffffffffe803000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000100000000000000
0000000000000000e803000018fcffff18fcffff00000000060000004d61726b
75730500000068756d616e0000000064000000060100009d0000000400000001
0000000100000000000000ffffffff0000000000000000010000000400000000
000000000000000000000000000000000000000e000000010000000000000000
0000000000000000000000000000000000000000000000ffffffffe803000000
0000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000a0860100a0860100000000000000000000
0000000000000000000000e803000018fcffff18fcffff000000002a00000008
0000000400000000000000000000000000008000000000000000000000000002
00000001000000e8030000000000000100000002000000020000000000000000
000000000000800000000000000000000000000000000000000000e803000000
0000000100000002000000010000000000000000000000000000800000000000
000000000000000000000000000000e803000000000000010000000000000000
0000000300000003000000000000000000000000000080000000000000000000
0000000000000000000000e80300000000000001000000030000000300000000
00000000000000000000800000000000000000000000000000000000000000e8
0300000000000001000000000000000300000003000000000000000000000000
0000800000000000000000000000000000000000000000e80300000000000001
0000000000000002000000000000000000000000000000000000800000000000
000000000000000000000000000000e803000000000000010000000300000003
0000000000000000000000000000800000000000000000000000000000000000
000000e803000000000000010000000300000003000000000000000000000000
0000800000000000000000000000000000000000000000e80300000000000001
0000000300000003000000000000000000000000000080000000000000000000
0000000000000000000000e80300000000000001000000030000000300000000
00000000000000000000800000000000000000000000000000000000000000e8
0300000000000001000000000000000000000000000000030000000300000000
00000000000000000000800000000000000000000000000000000000000000e8
030000000000000100000000000000000000000500000000000000010000000c
00000001000000e80300000000000000000000d83a0000701804000000000000
0000000000000000000080640000000000000000000000ffffffff0000000000
000000ffffffff0000000002000000640000000000000000000000ffffffff00
00000000000000ffffffff0000000000000000ffffffff0000000000000000ff
ffffff0100000002000000640000000000000000000000ffffffff000000001e
000000ffffffffffffffff04000000640000000000000000000000ffffffff00
00000003000000ffffffffffffffff04000000620000000000000000000000ff
ffffff0000000000000000ffffffffffffffff04000000640000000000000000
000000ffffffff0000000000000000ffffffff0000000000000000ffffffff00
00000000000000ffffffffffffffff04000000640000000000000000000000ff
ffffff0000000000000000ffffffff0000000017000000ffffffff0000000000
000000ffffffffffffffff040000005a0000000000000000000000ffffffff00
00000000000000ffffffffffffffff04000000640000000000000000000000ff
ffffff0000000000000000ffffffff0000000000000000ffffffff0000000000
000000ffffffff0100000002000000640000000000000000000000ffffffff00
00000000000000ffffffff0000000002000000640000000000000000000000ff
ffffff0000000000000000ffffffff000000000200000064000000000000001f
000000ffffffff0000000000000000ffffffffffffffff040000006400000000
00000000000000ffffffff0000000000000000ffffffff0000000000000000ff
ffffff0000000000000000ffffffffffffffff04000000640000000000000000
000000ffffffff0000000000000000ffffffffffffffff040000006400000000
00000000000000ffffffff0000000000000000ffffffff010000000200000060
0000000000000000000000ffffffff0000000000000000ffffffff0000000017
000000ffffffff0000000000000000ffffffffffffffff040000006200000000
00000000000000ffffffff0000000000000000ffffffffffffffff0400000064
0000000000000015000000ffffffff0000000000000000ffffffff0100000000
000000640000000000000000000000ffffffff0000000000000000ffffffff00
0000000200000000000000140000001400000014000000000000000000000003
0000000000000014000000140000001400000000000000000000000300000000
0000001400000014000000140000000000000000000000030000000000000014
0000001400000014000000000000000000000003000000000000001400000014
0000001400000000000000000000000300000000000000100000001000000010
0000000000000000000000020000000200000010000000100000001000000000
0000000000000002000000020000001400000014000000140000000000000000
0000000300000000000000140000001400000014000000000000000000000003
0000000000000014000000140000001400000000000000000000000300000000
0000001400000014000000140000000000000000000000030000000000000014
0000001400000014000000000000000000000003000000000000001400000014
0000001400000000000000000000000300000000000000140000001400000014
0000000000000000000000030000000000000014000000140000001400000000
0000000000000003000000000000000000000000000000000000000000000003
0000000a000000434c4f414b5f464952450d000000454e455247595f53484945
4c4408000000534c55475f47454c0100000006000000424154544c45e8280000
046100003c000000c8000000000000000900000000000000ffffffff00000000
0000000001000000030000000000000000000000000000001300000001000000
0000000001000000000000000000000001000000000000000100000000000000
0100000000000000000000000100000000000000000000000000000001000000
0000000001000000070000000000000016000000000000000000000000000000
0100000000000000000000000000000000000000000000000100000000000000
0000000000000000010000000000000001000000000000000000000001000000
1a00000073746172732f62675f6c6f6e656c79526564537461722e706e671600
000073746172732f706c616e65745f62726f776e2e706e67b80200008f000000
0000000001000000000000000200000000000000000000000000000000000000
0000000001000000000000000000000000000000010000000000000001000000
0000000000000000000000000100000000000000010000000000000000000000
010000001700000073746172732f62675f6461726b6e6562756c612e706e6716
00000073746172732f706c616e65745f70656163682e706e67af0000001a0000
0000000000010000000100000011000000424f53535f464c454554535f524542
454c0b00000053484950535f524542454ccb4a00000300000000000000000000
00000000000000000000000000010000000000000000000000010000001a0000
0073746172732f62675f6c6f6e656c79526564537461722e706e671b00000073
746172732f706c616e65745f6761735f79656c6c6f772e706e67450100007f00
0000000000000100000000000000020000000000000000000000010000001700
000073746172732f62675f6c6f6e656c79737461722e706e6718000000737461
72732f706c616e65745f626967626c75652e706e67af01000055000000b40000
000100000000000000000000000000000000000000010000001a000000737461
72732f62675f6c6f6e656c79526564537461722e706e67190000007374617273
2f706c616e65745f6761735f626c75652e706e671600000019010000b4000000
01000000010000000a0000004c4f4e475f464c4545541100000053484950535f
524542454c5f454c495445af2300000100000000000000000000000000000000
0000000000000000000000010000000000000000000000010000000000000001
0000000000000000000000000000000000000000000000010000000000000000
0000000000000000000000000000000100000000000000000000000000000000
0000000000000001000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000001000000000000000000000000000000000000000000000000
0000000100000000000000000000000000000000000000f82e00001000000050
49524154455f53555252454e4445520d0000005049524154455f455343415045
1100000044455354524f5945445f44454641554c5411000000444541445f4352
45575f44454641554c5400000000000000009d00000054686973206973206974
2e2e2e2054686520526562656c20666c6167736869702e20496620796f752061
72652061626c6520746f2064657374726f792074686973206d6f6e7374726f73
6974792c207468652046656465726174696f6e20666c6565742077696c6c2068
6176652061206368616e6365206f6620737572766976696e672e205468657265
2773206e6f207475726e696e67206261636b21ffffffff010000000000000001
000000010000000f000000424f53535f315f454153595f444c43120000007368
6f756c64206e6f74206265207365656e06000000626f73735f310b0000000500
000068756d616e090000004d6f7274726176656e0500000068756d616e0b0000
00456e7a6f204d617274696e0500000068756d616e050000004d616e6f6e0500
000068756d616e07000000546565204c656b0500000068756d616e0e00000053
746576656e2044656e676c65720500000068756d616e070000004c6f6d626172
640500000068756d616e030000005a61730500000068756d616e050000005427
74656e0500000068756d616e040000004c69616d0500000068756d616e0e0000
005374657068656e2045636b6d616e0500000068756d616e070000004d696b68
61696c010000000000000000000000000000000100000010000000090000000a
0000001e000000000000002a0000000800000008000000000000000000000000
0000000000000000000000000000000100000001000000e80300000000000001
0000000200000002000000000000000000000000000000000000000000000000
0000000000000000000000e80300000000000001000000020000000200000000
00000000000000000000000000000000000000000000000000000000000000e8
0300000000000001000000000000000000000003000000030000000000000000
000000000000000000000000000000000000000000000000000000e803000000
0000000100000003000000030000000000000000000000000000000000000000
000000000000000000000000000000e803000000000000010000000000000003
0000000300000000000000000000000000000000000000000000000000000000
00000000000000e8030000000000000100000000000000020000000200000000
000000ffffffff000000000000000000000000000000000000000000000000e8
0300000000000001000000030000000300000000000000000000000000000000
00000000000000000000000000000000000000e8030000000000000100000003
0000000300000000000000000000000000000000000000000000000000000000
00000000000000e8030000000000000100000003000000030000000000000000
000000000000000000000000000000000000000000000000000000e803000000
0000000100000003000000030000000000000000000000000000000000000000
000000000000000000000000000000e803000000000000010000000000000000
00000000000000030000000300000000000000ffffffff000000000000000000
000000000000000000000000000000e803000000000000010000000400000000
0000000000000000000000000000000000000001000000e80300000000000000
000000ab0e06003b140000010000000100000010270000ea1e00006400000064
00000000000000ffffffff6400000000000000ffffffff000000000200000064
0000000000000000000000ffffffff0000000000000000ffffffff0000000000
000000ffffffff0000000000000000ffffffff02000000030000006400000000
00000000000000ffffffff0000000000000000ffffffffffffffff0400000064
0000000000000000000000ffffffff0000000000000000ffffffffffffffff04
000000640000000000000000000000ffffffff0000000000000000ffffffffff
ffffff04000000640000000000000000000000ffffffff0000000000000000ff
ffffff0000000000000000ffffffff0000000000000000ffffffffffffffff04
000000640000000000000000000000ffffffff0000000000000000ffffffff00
00000000000000ffffffff0000000000000000ffffffffffffffff0400000064
0000000000000000000000ffffffff0000000000000000ffffffffffffffff04
000000640000000000000000000000ffffffff0000000000000000ffffffff00
00000000000000ffffffff0000000000000000ffffffff000000000300000064
0000000000000000000000ffffffff0000000000000000ffffffff0000000002
000000640000000000000000000000ffffffff0000000000000000ffffffff00
00000002000000640000000000000000000000ffffffff0000000000000000ff
ffffffffffffff04000000640000000000000000000000ffffffff0000000000
000000ffffffff0000000000000000ffffffff0000000000000000ffffffffff
ffffff04000000640000000000000000000000ffffffff0000000000000000ff
ffffffffffffff04000000640000000000000000000000ffffffff0000000000
000000ffffffff0100000002000000640000000000000000000000ffffffff00
00000000000000ffffffff0000000000000000ffffffff0000000000000000ff
ffffffffffffff04000000640000000000000000000000ffffffff0000000000
000000ffffffffffffffff04000000640000000000000000000000ffffffff00
00000000000000ffffffff0000000001000000640000000000000000000000ff
ffffff0000000000000000ffffffff0000000002000000000000001400000014
0000001400000000000000000000000300000000000000140000001400000014
0000000000000000000000030000000000000014000000140000001400000000
0000000000000003000000000000001400000014000000140000000000000000
0000000300000000000000140000001400000014000000000000000000000003
0000000000000010000000050000001000000000000000000000000200000001
000000100000000e000000100000000000000000000000020000000100000014
0000001400000014000000000000000000000003000000000000001400000014
0000001400000000000000000000000300000000000000140000001400000014
0000000000000000000000030000000000000014000000140000001400000000
0000000000000003000000000000001400000014000000140000000000000000
0000000300000000000000140000001400000014000000000000000000000003
0000000000000014000000140000001400000000000000000000000300000000
00000014000000140000001400000000000000000000000300000000000000f4
010000000000000000000000000000000000000000000000000000000000009c
ffffff9bffffff000000000000000000000000000000000b0000000000000000
0000000100000001000000000000000000000000000000000000000600000003
0000009d4af8ffa774faff2756f8fffa7bfaffb888000078ce04004865020069
bffdff01000000b8000000010000000500000003000000020000000000000000
0000000000000000000000ffffffffb800000000000000000000000000000000
000000d0070000000000000000000000000000000000000e0000006578706c6f
73696f6e5f62696732090000006d697373696c655f3100000000000000000000
000000000000e803000000000000000000000000000000000000000000000000
0000e8030000000000000000000076f4ffffaef8ffff01000000000000000e00
0000736d616c6c4578706c6f73696f6e0a000000686974536869656c64310400
00006d6973731700000000000000010000000100000000000000
[/code]

**Comment by Niels-NTG** [comment]
Could you give us some more information about the situation? Do you run the latest version of FTL? Have you tried to edit the file with with another editor? Use any mods?

**Comment by teepee2345** [comment]
I am using the latest version and I have no other editors. I also don't use
mods unless advanced edition counts as a mod

On Saturday, March 12, 2016, Niels NTG <notifications@github.com> wrote:

> Could you give us some more information about the situation? Do you run
> the latest version of FTL? Have you tried to edit the file with with
> another editor? Use any mods?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Vhati/ftl-profile-editor/issues/78#issuecomment-195819841>
> .
>


-- 
From: Tyler Burns

**Comment by teepee2345** [comment]
Also, it only happens during the boss level

On Saturday, March 12, 2016, Tyler Kerman <tylerb830@gmail.com> wrote:

> I am using the latest version and I have no other editors. I also don't
> use mods unless advanced edition counts as a mod
>
> On Saturday, March 12, 2016, Niels NTG <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Could you give us some more information about the situation? Do you run
>> the latest version of FTL? Have you tried to edit the file with with
>> another editor? Use any mods?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Vhati/ftl-profile-editor/issues/78#issuecomment-195819841>
>> .
>>
>
>
> --
> From: Tyler Burns
>
>

-- 
From: Tyler Burns

**Comment by Niels-NTG** [comment]
Oh, that explains quite a lot. Savedata begins to act unpredictable during the Final Stand. Sometimes the number of total explored beacons doesn't go up, amongst other things. Even after all these years we still haven't figured out what every byte in the savefile means. [Just most of them](https://github.com/Vhati/ftl-profile-editor/blob/master/src/main/java/net/blerf/ftl/parser/SavedGameParser.java), but not everything about the boss.

**Comment by teepee2345** [comment]
It does not happen if i wait unti A: no weapons are fired and B: im not
taking damage. Maybe it has issues with projectiles in flight?

On Saturday, March 12, 2016, Niels NTG <notifications@github.com> wrote:

> Oh, that explains quite a lot. Savedata begins to act unpredictable during
> the Final Stand. Sometimes the number of total explored beacons doesn't go
> up, amongst other things. Even after all these years we still haven't
> figured out what every byte in the savefile means. Just most of them
> <https://github.com/Vhati/ftl-profile-editor/blob/master/src/main/java/net/blerf/ftl/parser/SavedGameParser.java>,
> but not everything about the boss.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Vhati/ftl-profile-editor/issues/78#issuecomment-195821123>
> .
>


-- 
From: Tyler Burns

**Comment by Niels-NTG** [comment]
Do you first save your game by exiting to the menu or quiting the game before you load the file into the editor?

**Comment by teepee2345** [comment]
I hit Esc then Save+Exit and then launch the editor

On Saturday, March 12, 2016, Niels NTG <notifications@github.com> wrote:

> Do you first save your game by exiting to the menu or quiting the game
> before you load the file into the editor?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Vhati/ftl-profile-editor/issues/78#issuecomment-195821440>
> .
>


-- 
From: Tyler Burns

**Comment by teepee2345** [comment]
Games don't seem to like Alt F4

On Saturday, March 12, 2016, Tyler Kerman <tylerb830@gmail.com> wrote:

> I hit Esc then Save+Exit and then launch the editor
>
> On Saturday, March 12, 2016, Niels NTG <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Do you first save your game by exiting to the menu or quiting the game
>> before you load the file into the editor?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Vhati/ftl-profile-editor/issues/78#issuecomment-195821440>
>> .
>>
>
>
> --
> From: Tyler Burns
>
>

-- 
From: Tyler Burns

**Comment by teepee2345** [comment]
Thanks to the editor, i have discovered the joys of having Two PDS SHOTS
and two Swarm Missiles

On Saturday, March 12, 2016, Tyler Kerman <tylerb830@gmail.com> wrote:

> Games don't seem to like Alt F4
>
> On Saturday, March 12, 2016, Tyler Kerman <tylerb830@gmail.com
> <javascript:_e(%7B%7D,'cvml','tylerb830@gmail.com');>> wrote:
>
>> I hit Esc then Save+Exit and then launch the editor
>>
>> On Saturday, March 12, 2016, Niels NTG <notifications@github.com> wrote:
>>
>>> Do you first save your game by exiting to the menu or quiting the game
>>> before you load the file into the editor?
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/Vhati/ftl-profile-editor/issues/78#issuecomment-195821440>
>>> .
>>>
>>
>>
>> --
>> From: Tyler Burns
>>
>>
>
> --
> From: Tyler Burns
>
>

-- 
From: Tyler Burns

**Comment by Niels-NTG** [comment]
With "B: I'm not taking damage" I assume you mean the frames when you're getting hit?

**Comment by teepee2345** [comment]
Ja

On Saturday, March 12, 2016, Niels NTG <notifications@github.com> wrote:

> With "B: I'm not taking damage" I assume you mean the frames when you're
> getting hit?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Vhati/ftl-profile-editor/issues/78#issuecomment-195821782>
> .
>


-- 
From: Tyler Burns

**Comment by Niels-NTG** [comment]
Okay. That explains quite a lot. There are methods in the code to [read](https://github.com/Vhati/ftl-profile-editor/blob/master/src/main/java/net/blerf/ftl/parser/SavedGameParser.java#L1642) and [write](https://github.com/Vhati/ftl-profile-editor/blob/master/src/main/java/net/blerf/ftl/parser/SavedGameParser.java#L1739), these aren't actually implemented in the editor. Not wanting to speak for @Vhati , but my guess is that these are quite tricky values to edit without completely corrupting your savegame. For the record, I don't develop ftl-profile-editor myself, but do use a lot of its code.

**Comment by Niels-NTG** [comment]
…Or I could just have referred you to issue #77

**Comment by Vhati** [comment]
Heh. Thanks for the assist Niels-NG.  ; )

**Comment by Vhati** [comment]
The projectile bug has been fixed in v26.
