### ISSUE TITLE
glitch

### ISSUE THREAD

**Issue by palymygame** [Vhati/ftl-profile-editor#79]
i turned off avanced Edishen and i still can't alter the systems on my ship

**Comment by Niels-NTG** [comment]
Could you provide us with the contents of the log file? This would help a lot in fixing your problem.

**Comment by teepee2345** [comment]
This has happened to me as well. it seems that it thinks every saved game is an AE game
it might have to due with the profile editor showing AE-only ships and non-AE ships as well?

**Comment by Niels-NTG** [comment]
You mean the box "DLC" is ticked?
![schermafbeelding 2016-03-12 om 23 45 19](https://cloud.githubusercontent.com/assets/6061595/13725801/89312e36-e8ac-11e5-9c4f-2e04cf175c55.png)

**Comment by teepee2345** [comment]
Yea

On Saturday, March 12, 2016, Niels NTG <notifications@github.com> wrote:

> You mean the box "DLC" is ticked?
> [image: schermafbeelding 2016-03-12 om 23 45 19]
> <https://cloud.githubusercontent.com/assets/6061595/13725801/89312e36-e8ac-11e5-9c4f-2e04cf175c55.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Vhati/ftl-profile-editor/issues/79#issuecomment-195821265>
> .
>


-- 
From: Tyler Burns

**Comment by teepee2345** [comment]
I started a new game with AE disabled, and DLC box is uncheck but i still cannot edit systems

**Comment by Vhati** [comment]
Systems are only editable in saved games created by early versions of FTL. Since FTL:AE (1.5.4), things got more complicated. The AE/DLC option does NOT downgrade to the old format. It only swaps out some game elements to to mimic original gameplay.

The old format was 100% understood. The new format currently has a number of lingering unknowns, which make it dangerous to let the editor mess with systems.

**Comment by teepee2345** [comment]
When I look at the text readout of the game file, AE is always set to
"true" even if DLC is unchecked

On Tuesday, March 15, 2016, Vhati <notifications@github.com> wrote:

> Systems are only editable in saved games created by early versions of FTL.
> Since FTL:AE (1.5.4), things got more complicated. The AE/DLC option does
> NOT downgrade to the old format. It only swaps out some game elements to to
> mimic original gameplay.
>
> The old format was 100% understood. The new format currently has a number
> of lingering unknowns, which make it dangerous to let the editor mess with
> systems.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/Vhati/ftl-profile-editor/issues/79#issuecomment-197103969>
>


-- 
From: Tyler Burns

**Comment by Vhati** [comment]
> When I look at the text readout of the game file, AE is always set to "true" even if DLC is unchecked
Ha, good one!

That was supposed to say "Enabled"/"Disabled", but the words were being interpreted as boolean, so the both printed as "true".

**Comment by Vhati** [comment]
Fixed in v26.
