### ISSUE TITLE
saved game

### ISSUE THREAD

**Issue by starpae** [Vhati/ftl-profile-editor#82]
the ftl profile editor isn't letting me edit my saved game and I don't have any idea why

**Comment by Niels-NTG** [comment]
Are there any kind of error messages? If so, what do they say?

**Comment by starpae** [comment]
never mind, I was being  stupid and didn't know what I was doing. sorry for
wasting your time

**Comment by Niels-NTG** [comment]
Ok. Please close this issue if you're done.
