### ISSUE TITLE
SavedGame Parser Error

### ISSUE THREAD

**Issue by djubre7** [Vhati/ftl-profile-editor#83]
[code]
SavedGame Parser Error

Exception: java.lang.RuntimeException: End of stream reached before reading enough bytes for an int

Stack Trace...
  net.blerf.ftl.parser.Parser.readInt(Parser.java:43)
  net.blerf.ftl.parser.SavedGameParser.readProjectile(SavedGameParser.java:1646)
  net.blerf.ftl.parser.SavedGameParser.readZeus(SavedGameParser.java:9238)
  net.blerf.ftl.parser.SavedGameParser.readSavedGame(SavedGameParser.java:244)
  net.blerf.ftl.ui.FTLFrame$11.actionPerformed(FTLFrame.java:802)

Editor Version: 25
OS: Windows 8.1 6.3
VM: Java HotSpot(TM) 64-Bit Server VM, 1.8.0_60, amd64
[/code]

File ("continue.sav - Copy.bak")...
[code]
0900000000000000010000000a000000380000001d0200000b00000006000000
4e61676f796110000000504c415945525f534849505f48415244070000000000
00000f0000000a000000626c75655f616c69656e010000000900000064656164
5f63726577040000000a000000656e765f64616e676572010000000a00000066
697265645f73686f74d200000006000000686967686f32010000000b0000006b
696c6c65645f6372657719000000090000006c6f73745f637265770100000006
0000006e6562756c61120000000f00000072656163746f725f75706772616465
010000000e00000073746f72655f7075726368617365880000000c0000007374
6f72655f726570616972010000000f000000737566666f63617465645f637265
77a00000000e00000073797374656d5f757067726164650b0000000c00000075
7365645f6d697373696c655a0000000e000000776561706f6e5f757067726164
650100000010000000504c415945525f534849505f48415244060000004e6167
6f7961070000006b65737472616c030000000500000068756d616e0600000041
7274796f6d0500000068756d616e0f0000004e6f7277796e20536368756c747a
650500000068756d616e09000000546f6d2042616e6b7301000000084c010000
00000000000000190000000d0100007a000000df00000046540000080000000f
0000004e6f7277796e20536368756c747a650500000068756d616e0000000055
00000034000000c00000000e000000020000000100000000000000ffffffff02
000000000000000100000000000000020000000e0000001a0000001a00000064
00000074000000200000000e000000010000001a000000190000001900000050
0000000c0000000000000000000000ffffffffe8030000000000002b00000001
0000000100000001000000010000000100000001000000010000000100000001
0000000100000001000000010000000000000001000000000000000000000000
000000e803000000000000000000000000000009000000546f6d2042616e6b73
0500000068756d616e000000005300000029010000c000000005000000000000
000100000000000000ffffffff02000000000000000200000000000000010000
000a0000001a0000001a0000006400000074000000200000000e000000010000
00190000001900000019000000500000000c0000000000000000000000ffffff
ffe8030000000000002b00000001000000010000000100000001000000010000
0001000000010000000100000001000000010000000100000001000000000000
0001000000000000000000000000000000e80300000000000000000000000000
000c0000004e69636b20427265636b6f6e060000006d616e7469730000000064
000000290100007a00000004000000000000000100000000000000ffffffff01
0000000000000000000000ffffffffffffffff1e0000001e0000006e00000082
000000240000001000000001000000190000001c000000190000004a0000000c
0000000000000000000000ffffffffe8030000000000002b0000000100000001
0000000100000001000000010000000100000001000000010000000100000001
00000001000000010000000000000001000000000000000000000000000000e8
030000000000000000000000000000070000004a756e70656e6706000000656e
6572677900000000240000009d0000009d0000000a0000000000000001000000
00000000ffffffff010000000000000000000000ffffffffffffffff1e000000
1e0000006e000000820000002400000010000000010000001900000019000000
190000004a0000000c0000000000000000000000ffffffffe803000000000000
2b00000001000000010000000100000001000000010000000100000001000000
0100000001000000010000000100000001000000000000000100000000000000
0000000000000000e8030000000000000000000000000000090000005761692d
5368696e6704000000726f636b0000000096000000fb0100009d000000000000
00000000000100000000000000ffffffff010000000000000000000000ffffff
ffffffffff1e0000001e0000006e000000820000002400000010000000010000
00190000001900000039000000400000000c0000000000000000000000ffffff
ffe8030000000000002b00000001000000010000000100000001000000010000
0001000000010000000100000001000000010000000100000001000000000000
0001000000000000000000000000000000e80300000000000000000000000000
000b0000004f2e2057696c6c69616d73070000006372797374616c0000000078
000000290100009d00000004000000020000000100000000000000ffffffff01
0000000300000000000000ffffffffffffffff1e0000001e0000006e00000082
000000240000001000000001000000190000001900000019000000400000000c
0000000000000000000000ffffffffe8030000000000002b0000000100000001
0000000100000001000000010000000100000001000000010000000100000001
00000001000000010000000000000001000000000000000000000000000000e8
030000000000000000000000000000000000000000000000000000060000004e
617468616e06000000656e657267790000000024000000c00000009d0000000a
000000010000000100000000000000ffffffff01000000010000000000000001
000000080000001e0000001e0000006e00000082000000240000001000000001
0000001a0000001900000019000000400000000c0000000000000000000000ff
ffffffe8030000000000002b0000000100000001000000010000000100000001
0000000100000001000000010000000100000001000000010000000100000000
00000001000000000000000000000000000000e803000018fcffff18fcffff00
0000000400000059656f7a06000000656e6572677900000000240000009d0000
00c00000000a000000020000000100000000000000ffffffff01000000010000
0000000000ffffffffffffffff1e0000001e0000006e00000082000000240000
0010000000010000001900000019000000190000002e0000000c000000000000
0000000000ffffffffe8030000000000002b0000000100000001000000010000
0001000000010000000100000001000000010000000100000001000000010000
00010000000000000001000000000000000000000000000000e8030000000000
0000000000000000001900000008000000060000000000000000000000000000
800000000000000000000000000000000000000000e803000000000000010000
0008000000070000000000000000000000000000800000000000000000000000
000000000000000000e803000000000000010000000300000001000000000000
0000000000000000800000000000000000000000000000000000000000e80300
0000000000010000000800000003000000000000000000000000000080000000
0000000000000000000000000000000000e80300000000000001000000080000
0000000000000000000000000000000080000000000000000000000000000000
0000000000e80300000000000001000000030000000100000000000000000000
00000000800000000000000000000000000000000000000000e8030000000000
0001000000030000000300000000000000000000000000008000000000000000
00000000000000000000000000e8030000000000000100000003000000030000
0000000000000000000000008000000000000000000000000000000000000000
00e8030000000000000100000003000000020000000000000000000000000000
800000000000000000000000000000000000000000e803000000000000010000
0003000000000000000000000000000000000000800000000000000000000000
000000000000000000e803000000000000010000000300000002000000000000
0000000000000000800000000000000000000000000000000000000000e80300
0000000000010000000000000000000000000000000000000000000000030000
00000000000000000000000000000000000000000001000000e8030000000000
00000000005f1c000010580000000000000000000010270000cdfdadaa640000
000000000000000000ffffffff0000000000000000ffffffff00000000010000
00640000000000000000000000ffffffff0000000000000000ffffffff000000
0000000000ffffffff0000000000000000ffffffffffffffff04000000640000
000000000000000000ffffffff0000000000000000ffffffff01000000020000
00640000000000000000000000ffffffff0000000000000000ffffffff010000
0000000000640000000000000000000000ffffffff0000000000000000ffffff
ff0000000000000000ffffffff000000000b000000ffffffffffffffff040000
0064000000000000002a000000ffffffff0000000000000000ffffffff000000
0000000000ffffffff0000000028000000ffffffff0000000003000000640000
000000000000000000ffffffff0000000000000000ffffffffffffffff040000
00640000000000000000000000ffffffff0000000000000000ffffffff000000
002f000000ffffffff0000000000000000ffffffffffffffff04000000640000
000000000000000000ffffffff0000000000000000ffffffff00000000000000
00ffffffff0000000012000000ffffffffffffffff0400000064000000000000
0000000000ffffffff0000000000000000ffffffffffffffff04000000640000
000000000000000000ffffffff0000000000000000ffffffff00000000000000
00ffffffff0000000000000000ffffffff010000000200000064000000000000
0000000000ffffffff0000000000000000ffffffffffffffff04000000640000
000000000000000000ffffffff0000000000000000ffffffffffffffff040000
00640000000000000000000000ffffffff0000000000000000ffffffffffffff
ff04000000640000000000000000000000ffffffff0000000000000000ffffff
ff0000000000000000ffffffff0000000000000000ffffffff02000000000000
00640000000000000000000000ffffffff0000000000000000ffffffffffffff
ff04000000640000000000000000000000ffffffff0000000000000000ffffff
ffffffffff040000000000000008000000080000000800000000000000000000
0001000000000000000800000008000000080000000000000000000000010000
0000000000080000000800000008000000000000000000000001000000000000
0008000000050000000800000000000000000000000100000000000000080000
0008000000080000000000000000000000010000000000000008000000080000
0008000000000000000000000001000000000000000800000008000000080000
0000000000000000000100000000000000080000000800000008000000000000
0000000000010000000000000008000000080000000800000000000000000000
0001000000000000000800000008000000080000000000000000000000010000
0000000000080000000800000008000000000000000000000001000000000000
0008000000080000000800000000000000000000000100000000000000080000
0008000000080000000000000000000000010000000000000008000000080000
0008000000000000000000000001000000000000000800000008000000080000
0000000000000000000100000000000000080000000800000008000000000000
0000000000010000000000000008000000080000000800000000000000000000
0001000000000000000800000008000000080000000000000000000000010000
0000000000080000000800000008000000000000000000000001000000000000
0008000000080000000800000000000000000000000100000000000000080000
0008000000080000000000000000000000010000000000000008000000080000
0008000000000000000000000001000000000000000800000008000000080000
0000000000000000000100000000000000080000000800000008000000000000
0000000000010000000000000008000000080000000800000000000000000000
0001000000000000000800000008000000080000000000000000000000010000
00000000000000000000000000040000000d000000424f4d425f425245414348
5f320100000009000000424f4d425f4c4f434b010000000d0000004c41534552
5f48454156595f320100000009000000424f4d425f4649524500000000020000
0008000000434f4d4241545f310000000000000000ffffffffffffffffffffff
ffffffffff010000000b000000434f4d4241545f4245414d0000000000000000
ffffffffffffffffffffffffffffffff010000000300000009000000494f4e5f
41524d4f520f000000534849454c445f52454348415247451000000057454150
4f4e5f50524549474e4954450400000006000000424f4d425f3105000000494f
4e5f340d0000004c415345525f42555253545f33110000004d495353494c4553
5f325f504c41594552123a00007c05000081fcffffad00000000000000010000
0000000000ffffffff0000000000000000000000000000000000000000000000
0000000000130000000100000000000000010000000000000001000000000000
0001000000000000000000000001000000000000000000000001000000000000
0000000000000000000100000000000000000000000600000000000000140000
00010000001a00000073746172732f62675f6c6f6e656c79526564537461722e
706e671600000073746172732f706c616e65745f62726f776e2e706e67710000
00f1000000b40000000100000000000000000000000000000000000000010000
001700000073746172732f62675f64756c6c7374617273322e706e671b000000
73746172732f706c616e65745f6761735f79656c6c6f772e706e67600200007f
000000b400000001000000010000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000100000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000001
0000003e64000000000000000000001a000000464c4147534849505f434f4e53
5452554354494f4e5f444f4e452a000000464c415348534849505f434f4e5354
52554354494f4e5f534849502064656164206372657720203836340000000000
000000470100005761726e696e67206c696768747320666c6173682061732073
63616e73206964656e746966792074686520676967616e746963207368697020
756e64657220636f6e737472756374696f6e202d20697427732061207365636f
6e6420526562656c20466c616773686970212054686973206d75737420626520
7468652073656372657420736869707961726473207768657265207468652066
69727374206f6e6520776173206275696c742c20616e6420796f752776652061
63636964656e74616c6c79207374756d626c6564206163726f73732069742120
4576656e20696e20697473207765616b656e65642073746174652c2074686520
526562656c207368697020706f776572732075702e2e2e206765742072656164
792c20796f7527766520676f7420612068656c6c206f66206120666967687420
6f6e20796f75722068616e64732effffffff0200000000000000000000000100
0000000000000c000000424f53535f5350454349414c1200000073686f756c64
206e6f74206265207365656e06000000626f73735f3306000000050000006875
6d616e0b000000437261696720446f6c616e0500000068756d616e070000004c
6167617264690500000068756d616e070000004d756c6c657474050000006875
6d616e060000005461692059690500000068756d616e050000004e6f656d6905
00000068756d616e0b0000004a6f73682043756262696e010000000000000000
0000000000000010000000100000000000000014000000d4030000040000000b
000000437261696720446f6c616e0500000068756d616e000000006400000057
0000001100000000000000000000000000000000000000ffffffff0200000000
0000000100000000000000ffffffffffffffff00000000000000000000000000
0000000000000000000000010000000000000000000000050000000000000000
0000000000000000000000ffffffffe8030000000000002b0000000000000000
0000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000001000000000000000000000000000000e8
030000000000000000000000000000070000004c616761726469050000006875
6d616e0000000064000000570000003400000001000000000000000000000000
000000ffffffff02000000000000000000000000000000ffffffffffffffff00
0000000000000000000000000000000000000000000000010000000000000000
0000000000000000000000000000000000000000000000ffffffffe803000000
0000002b00000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000100000000
0000000000000000000000e8030000000000000000000000000000070000004d
756c6c6574740500000068756d616e000000004c000000c0000000340000000a
000000000000000000000000000000ffffffff02000000000000000000000000
000000ffffffffffffffff000000000000000000000000000000000000000000
0000000100000000000000000000000000000000000000000000000000000000
000000ffffffffe8030000000000002b00000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000001000000000000000000000000000000e80300000000000000
00000000000000060000005461692059690500000068756d616e000000003600
0000970000003500000003000000000000000000000000000000ffffffff0200
0000000000000100000000000000ffffffffffffffff00000000000000000000
0000000000000000000000000000010000000100000000000000000000000000
0000000000000000000000000000ffffffffe8030000000000002b0000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000100000000000000000000000000
0000e80300000000000000000000000000001d00000008000000060000000200
000000000000000000006000000000000000000000000000000000000000e803
0000000000000100000005000000050000000000000000000000000000000000
000000000000000000000000000000000000e803000000000000010000000100
0000010000000000000000000000000000000000000000000000000000000000
000000000000e803000000000000010000000000000000000000010000000100
0000000000000000000000000000000000000000000000000000000000000000
0000e80300000000000001000000030000000300000000000000000000000000
00000000000000000000000000000000000000000000e8030000000000000100
0000000000000000000001000000010000000000000000000000000000000000
000000000000000000000000000000000000e803000000000000010000000000
0000040000000400000000000000000000000000000000000000000000000000
00000000000000000000e8030000000000000100000004000000040000000000
000000000000000000000000000000000000000000000000000000000000e803
0000000000000100000000000000000000000000000000000000010000000000
000000000000f303000001000000e803000001000000e8030000000000000000
0000ab34ffffd11b0000640000006400000000000000ffffffff640000000000
0000ffffffff0000000002000000480000006400000000000000ffffffff6400
000000000000ffffffff6400000000000000ffffffff6400000000000000ffff
ffff0200000000000000640000006400000000000000ffffffff640000000000
0000ffffffffffffffff04000000640000006400000000000000ffffffff6400
000000000000ffffffffffffffff04000000640000006400000000000000ffff
ffff6400000000000000ffffffffffffffff0400000064000000640000000000
0000ffffffff6400000000000000ffffffff0000000000000000ffffffff6400
000000000000ffffffffffffffff04000000640000006400000000000000ffff
ffff6400000000000000ffffffff6400000000000000ffffffff640000000000
0000ffffffffffffffff04000000640000006400000000000000ffffffff6400
000000000000ffffffffffffffff04000000640000006400000000000000ffff
ffff6400000000000000ffffffff6400000000000000ffffffff640000000000
0000ffffffff0200000000000000640000006400000000000000ffffffff6400
000000000000ffffffff0000000002000000640000006400000000000000ffff
ffff6400000000000000ffffffff000000000200000064000000640000000000
0000ffffffff6400000000000000ffffffffffffffff04000000640000006400
000000000000ffffffff6400000000000000ffffffffffffffff040000001900
0000030000000200000064000000030000000100000064000000020000000200
0000640000000200000001000000640000000500000001000000640000000100
0000050000006400000002000000060000006400000001000000060000006400
0000020000000700000064000000030000000800000064000000020000000800
0000640000000300000009000000640000000200000009000000640000000300
0000060000006400000003000000050000006400000004000000050000006400
0000040000000600000064000000040000000300000064000000010000000300
0000640000000100000001000000640000000000000001000000640000000200
0000000000006400000002000000030000006400000003000000040000006400
0000040000000100000064000000320000003200000004000000000000000000
0000000000000000000032000000320000000400000000000000000000000000
0000000000000400000004000000040000000000000000000000000000000000
0000040000000400000004000000000000000000000000000000000000000400
0000040000000400000000000000000000000000000000000000040000000400
0000040000000000000000000000000000000000000004000000040000000400
0000000000000000000000000000000000000400000004000000040000000000
0000000000000000000000000000040000000400000004000000000000000000
0000000000000000000032000000320000000400000000000000000000000000
0000000000000400000004000000040000000000000000000000000000000000
0000320000002c00000004000000000000000000000000000000000000000400
0000040000000400000000000000000000000000000000000000040000000400
0000040000000000000000000000000000000000000004000000040000000400
000000000000000000000000000000000000000000001c000000e0280100b888
0000e0280100b88800001c0600000100000000000000a2200000000000000100
0000010000004a01000080380100289a010080380100289a0100470400000100
000000000000a22000000000000001000000010000004f010000486b0100b888
0000486b0100b8880000530500000100000000000000a2200000000000000100
00000100000049010000f04f0100289a0100f04f0100289a01004b0600000100
000000000000a220000000000000010000000100000048010000e87a0100b888
0000e87a0100b8880000e30600000100000000000000a2200000000000000100
0000010000004601000040960100289a010040960100289a0100630400000100
000000000000a22000000000000001000000010000004c01000050bd0100b888
000050bd0100b8880000bd0600000100000000000000a2200000000000000100
0000010000004601000050bd0100289a010050bd0100289a0100c10500000100
000000000000a22000000000000001000000010000004801000018f00100b888
000018f00100b8880000320500000100000000000000a2200000000000000100
0000010000004c01000030ec0100289a010030ec0100289a01009b0700000100
000000000000a22000000000000001000000010000004601000040130200b888
000040130200b8880000c70600000100000000000000a2200000000000000100
00000100000049010000580f0200289a0100580f0200289a01009d0500000100
000000000000a22000000000000001000000010000004c01000070110100a08c
000070110100a08c00001f0600000100000000000000a2200000000000000100
0000010000004c010000e0220200a08c0000e0220200a08c0000e20500000100
000000000000a22000000000000001000000010000004c0100007011010008cf
00007011010008cf00009f0500000100000000000000a2200000000000000100
00000100000049010000e022020090e20000e022020090e20000870700000100
000000000000a22000000000000001000000010000004601000070110100880d
010070110100880d0100cf0600000100000000000000a2200000000000000100
00000100000046010000e022020060ea0000e022020060ea0000a00500000100
000000000000a22000000000000001000000010000004801000070110100c82c
010070110100c82c0100580500000100000000000000a2200000000000000100
00000100000049010000e022020010210100e0220200102101005d0500000100
000000000000a22000000000000001000000010000004801000070110100306f
010070110100306f01002e0400000100000000000000a2200000000000000100
0000010000004f010000e0220200f04f0100e0220200f04f0100cc0700000100
000000000000a22000000000000001000000010000004601000070110100888a
010070110100888a0100d70500000100000000000000a2200000000000000100
0000010000004c010000e0220200e87a0100e0220200e87a0100ff0400000100
000000000000a22000000000000001000000010000004d010000d8530100b888
0000d8530100b8880000d60400000100000000000000a2200000000000000100
0000010000004c01000090dc0100289a010090dc0100289a0100e80400000100
000000000000a22000000000000001000000010000004b0100007011010020cb
00007011010020cb0000810500000100000000000000a2200000000000000100
00000100000049010000e022020020cb0000e022020020cb0000ab0600000100
000000000000a220000000000000010000000100000047010000000000000000
0000000000000000000000000000000000000300000002000000983a00000000
0000000000000000000003000000000000000000000000000000020000000000
000000000000000000000000000002000000030000007815010058a402006f27
010011840200b88800007011010098ab020039d1010001000000420100000100
000005000000030000000200000000000000000000000000000000000000ffff
ffff4201000000000000000000000000000000000000d0070000000000000000
000000000000000000000e0000006578706c6f73696f6e5f6269673309000000
6d697373696c655f31010000000000000008000000dd020000e80300000083ff
ff0083ffff00000000000000000000000000000000e803000000000000000000
000aeeffff4720000000000000010000000e000000736d616c6c4578706c6f73
696f6e0a000000686974536869656c6432040000006d6973731f010000010000
00000000000100000000000000
[/code]

**Comment by Niels-NTG** [comment]
Did you happen to save your game (i.e. you quitted to the menu or you quitted the game) while you where in a combat situation? If so, you're not the only one having this issue ( #78 , #77 , #76 ). Long story short: FTL Profile Editor is able to make sense of most of the contents of `continue.sav` (your FTL save game), but not all of it. If you quit in the mids of a combat encounter FTL introduces a whole lot of new bytes to the save game file, most likely things about the position of missiles, combat drones, etc. FTL Profile Editor can't deal with these mysterieus bytes at this time. This will be addressed in future releases. Until then I recommend you try editing your save file when your ship is not in any danger.

**Comment by Vhati** [comment]
The projectile bug has been fixed in v26.
