### ISSUE TITLE
Unable to run project in Eclipse

### ISSUE THREAD

**Issue by Pysis868** [Vhati/ftl-profile-editor#85]
Downloaded the project's source code as a zip archive, extracted it, imported it into Eclipse Kepler (4.3.1?).

In the Problems pane I noticed this error:

```
Project 'ftl-profile-editor' is missing required source folder: 'src/test/resources'
```

**Comment by Niels-NTG** [comment]
There must be something wrong we your project creation settings. This project doesn't come with such a folder. I personally use IntelliJ IDEA (highly recommend btw), which has an option to import a *[Maven](http://docs.codehaus.org/display/MAVENUSER/Getting+Started+with+Maven)* project, the build tool used for this and many other Java projects. You should look if you can find something similar for Eclipse.

**Comment by Pysis868** [comment]
Ok, I'll look into it some more.  Was playing with getting the M2Eclipse plug-in installed last night, and that should also have a Maven import feature.  Maybe it is a generated directory as I can see in the [.classpath](https://github.com/Vhati/ftl-profile-editor/blob/master/.classpath) file it, like many others, are marked as "maven.pomderived".  I just half-expected tests to be manually created by the developers and exist in the project.

**Comment by Pysis868** [comment]
So, I did get it working eventually.

Using Eclipse and its Maven plugin, and also IntelliJ IDEA, I was able to get the project running.  It had a host of errors complaining about the run method not overriding any existing implementation, but the project still runs.  Maybe take those out?

**Comment by Vhati** [comment]
> errors complaining about the run method not overriding any existing implementation

I've never used your dev environment, but it sounds like you might be compiling with Java 1.5?

Java 1.5 did not recognize @Override annotations on interface methods.
That was introduced in Java 1.6.

You may need to adjust Eclipse's compiler compliance level to 1.6?
http://stackoverflow.com/questions/2335655/why-is-javac-failing-on-override-annotation
