### ISSUE TITLE
Profile Parser Error

### ISSUE THREAD

**Issue by samoutyout** [Vhati/ftl-profile-editor#87]
[code]
Profile Parser Error

Hashes did not match after a mock write.

Editor Version: 25
OS: Windows 10 10.0
VM: Java HotSpot(TM) Client VM, 1.8.0_91, x86
[/code]

File ("ae_prof.sav")...
[code]
09000000020000001a0000000c0000004143485f534543544f525f3501000000
0c0000004143485f534543544f525f38000000000c0000004143485f57494e5f
45415359000000000e0000004143485f554e4c4f434b5f414c4c000000000900
00004143485f534352415000000000090000004143485f534849505300000000
0f0000004143485f4e4f5f5550475241444553000000000c0000004143485f50
41434946495354000000000d0000004143485f4e4f5f52455041495200000000
0f0000004143485f4e4f5f4d495353494c4553000000000d0000004143485f4e
4f5f44524f4e4553000000000c0000004143485f4e4f5f444541544800000000
0f0000004143485f4241445f444f4447494e47000000000e0000004143485f4f
4e455f564f4c4c4559000000000f0000004143485f494e564144455f53484950
000000000e0000004143485f534c4943455f44494345000000000d0000004143
485f535546464f4341544500000000150000004143485f554e495445445f4645
4445524154494f4e00000000100000004143485f46554c4c5f415253454e414c
000000000e0000004143485f544f5547485f5348495000000000120000004143
485f454e455247595f534849454c445302000000100000004143485f454e4552
47595f504f57455200000000130000004143485f454e455247595f4d414e504f
57455200000000130000004143485f535445414c54485f44455354524f590000
0000110000004143485f535445414c54485f41564f4944000000001400000041
43485f535445414c54485f544143544943414c00000000010000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000
[/code]

**Comment by Vhati** [comment]
Fixed in v26.
