### ISSUE TITLE
SavedGame Parser Error

### ISSUE THREAD

**Issue by jay182** [Vhati/ftl-profile-editor#89]
[code]
SavedGame Parser Error

Exception: java.lang.RuntimeException: End of stream reached before reading enough bytes for an int

Stack Trace...
  net.blerf.ftl.parser.Parser.readInt(Parser.java:43)
  net.blerf.ftl.parser.SavedGameParser.readExtendedShipInfo(SavedGameParser.java:9367)
  net.blerf.ftl.parser.SavedGameParser.readZeus(SavedGameParser.java:9241)
  net.blerf.ftl.parser.SavedGameParser.readSavedGame(SavedGameParser.java:244)
  net.blerf.ftl.ui.FTLFrame$11.actionPerformed(FTLFrame.java:802)

Editor Version: 25
OS: Windows 10 10.0
VM: Java HotSpot(TM) 64-Bit Server VM, 1.8.0_91, amd64
[/code]

File ("continue.sav")...
[code]
090000000100000000000000110000004a000000a60400000600000005000000
3537362e3217000000504c415945525f534849505f414e4145524f4249435f32
08000000000000000f0000000a000000626c75655f616c69656e040000000900
0000646561645f63726577050000000a000000656e765f64616e676572030000
000a00000066697265645f73686f748702000006000000686967686f32010000
000b0000006b696c6c65645f6372657732000000090000006c6f73745f637265
7715000000060000006e6562756c61020000000f00000072656163746f725f75
706772616465030000000e00000073746f72655f707572636861736578000000
0c00000073746f72655f726570616972030000000f000000737566666f636174
65645f63726577ec0700000e00000073797374656d5f757067726164650d0000
000a00000074656c65706f72746564220000000e000000776561706f6e5f7570
67726164650100000017000000504c415945525f534849505f414e4145524f42
49435f32050000003537362e3213000000616e6165726f6269635f6372756973
65725f320300000004000000656e6769050000004b6972627909000000616e61
65726f6269630900000046726564657269636b09000000616e6165726f626963
0400000057696c6c01000000084c010000000000000000001e00000026000000
2600000042000000660a000006000000050000004b6972627904000000656e67
69000000005a0000002901000034000000040000000000000001000000010000
00ffffffff0000000000000000000000000d0000000000000000000000000000
0082000000050000000000000001000000050000000000000000000000490000
00020000000000000000000000ffffffffe8030000000000006b000000000000
0000000000000000000000000000000000000000000100000001000000000000
0000000000000000000000000000000000010000000000000000000000000000
00e80300000000000000000000000000000400000057696c6c09000000616e61
65726f6269630000000064000000c00000004c01000010000000000000000100
00000100000069000000010000000100000000000000010000000c0000000000
0000000000000000000000000000000000000500000001000000010000000700
0000000000004700000001000000000000000000000069000000e80300000000
00006b0000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000010000000000000000000000000000000000
00000000000000000000e8030000000000000000000001000000040000004b75
7379060000006d616e7469730000000064000000c00000001100000000000000
0000000001000000010000001d00000001000000000000000000000000000000
0000000000000000000000000000000000000000010000000200000001000000
010000000300000000000000490000000000000000000000000000001d000000
e8030000000000006b0000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000e803000018fcffff18fcffff01000000
050000004e6f7463680500000068756d616e00000000000000006f0100009d00
0000ffffffffffffffff01000000010000006b00000002000000000000000200
00000000000000000000090000001a0000000000000000000000000000000200
0000000000000100000002000000000000005000000049000000020000000000
0000000000006b000000e8030000000000006b00000001000000010000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000001000000000000000000000000000000e803000018fc
ffff18fcffff00000000060000005374656c6c790500000068756d616e000000
0055000000e3000000c000000008000000020000000100000001000000ffffff
ff020000000000000003000000000000000200000008000000000000001a0000
0000000000000000000300000000000000010000000300000000000000000000
0049000000020000000000000000000000ffffffffe8030000000000006b0000
0000000000000000000100000001000000000000000000000000000000000000
0000000000000000000000000000000000000000000100000000000000000000
0000000000e803000018fcffff18fcffff00000000080000005965766f6e2053
6904000000736c75670000000020000000290100005700000004000000020000
000100000001000000ffffffff010000000500000000000000ffffffffffffff
ff0f000000000000001500000000000000000000000000000001000000000000
0000000000000000000d000000000000000000000000000000ffffffffe80300
00000000006b0000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000e8030000000000000000000001000000190000
0008000000010000000000000000000000000000800000000000000000000000
000000000000000000e803000000000000010000000800000003000000000000
0000000000000000800000000000000000000000000000000000000000e80300
0000000000010000000300000001000000000000000000000000000080000000
0000000000000000000000000000000000e80300000000000001000000080000
0007000000000000000000000000000080000000000000000000000000000000
0000000000e80300000000000001000000000000000000000003000000000000
0000000000000000000000008000000000000000000000000000000000000000
00e8030000000000000100000003000000020000000000000000000000000000
800000000000000000000000000000000000000000e803000000000000010000
0003000000010000000000000000000000000000800000000000000000000000
000000000000000000e803000000000000010000000300000003000000000000
0000000000000000800000000000000000000000000000000000000000e80300
0000000000010000000300000003000000000000000000000000000080000000
0000000000000000000100000001000000e80300000000000001000000000000
0002000000020000000000000000000000000000800000000000000000000000
000000000000000000e803000000000000010000000300000002000000000000
0000000000000000800000000000000000000000000000000000000000e80300
0000000000010000000300000000000000000000000000000000000080000000
0000000000000000000000000000000000e80300000000000001000000000000
00321a00002823000018fcffff0000000000000000e803000000000000000000
0005000000000000000000000000000000010000000000000000000000000000
00c96308004f0204000000000000000000983a0000b157000064000000000000
0000000000ffffffff0000000000000000ffffffff0000000002000000640000
000000000000000000ffffffff0000000000000000ffffffffffffffff040000
00640000000000000000000000ffffffff0000000000000000ffffffff000000
0000000000ffffffff0000000000000000ffffffffffffffff04000000640000
000000000000000000ffffffff0000000000000000ffffffffffffffff040000
00640000000000000000000000ffffffff0000000000000000ffffffff000000
0000000000ffffffff0000000000000000ffffffff0200000003000000640000
000000000000000000ffffffff0000000000000000ffffffffffffffff040000
00640000000000000000000000ffffffff0000000000000000ffffffffffffff
ff04000000640000000000000000000000ffffffff0000000000000000ffffff
ff0000000000000000ffffffff0000000001000000ffffffffffffffff040000
00640000000000000000000000ffffffff0000000000000000ffffffff000000
0000000000ffffffff0000000000000000ffffffff0200000000000000640000
000000000000000000ffffffff0000000000000000ffffffff00000000010000
00640000000000000000000000ffffffff0000000000000000ffffffff000000
0002000000ffffffff0000000021000000ffffffffffffffff04000000640000
000000000000000000ffffffff0000000000000000ffffffff00000000000000
00ffffffff0000000000000000ffffffffffffffff0400000064000000000000
0000000000ffffffff0000000000000000ffffffffffffffff04000000640000
000000000000000000ffffffff000000000f000000ffffffff00000000000000
00ffffffff0000000000000000ffffffff000000000200000064000000000000
0000000000ffffffff0000000000000000ffffffffffffffff04000000640000
000000000000000000ffffffff0000000000000000ffffffffffffffff040000
00640000000000000000000000ffffffff0000000014000000ffffffff000000
0000000000640000000000000000000000ffffffff0000000027000000ffffff
ffffffffff040000000000000004000000040000000400000000000000000000
0000000000000000000400000004000000040000000000000000000000000000
0000000000040000000400000004000000000000000000000000000000000000
0004000000040000000400000000000000000000000000000000000000040000
0004000000040000000000000000000000000000000000000004000000040000
0004000000000000000000000000000000000000000400000004000000040000
0000000000000000000000000000000000040000000400000004000000000000
0000000000000000000000000004000000040000000400000000000000000000
0000000000000000000400000004000000040000000000000000000000000000
0000000000040000000400000004000000000000000000000000000000000000
0004000000040000000400000000000000000000000000000000000000040000
0004000000040000000000000000000000000000000000000004000000040000
0004000000000000000000000000000000000000000400000004000000040000
0000000000000000000000000000000000040000000400000004000000000000
0000000000000000000000000004000000040000000400000000000000000000
0000000000000000001000000010000000100000000000000000000000020000
0001000000100000000f00000010000000000000000000000002000000010000
0004000000040000000400000000000000000000000000000000000000040000
0004000000040000000000000000000000000000000000000004000000040000
0004000000000000000000000000000000000000000400000004000000040000
0000000000000000000000000000000000040000000400000004000000000000
0000000000000000000000000004000000040000000400000000000000000000
0000000000000000000400000004000000040000000000000000000000000000
0000000000040000000400000004000000000000000000000000000000000000
0004000000040000000400000000000000000000000000000000000000040000
0004000000040000000000000000000000000000000000000004000000040000
0004000000000000000000000000000000000000000400000004000000040000
0000000000000000000000000000000000040000000400000004000000000000
0000000000000000000000000004000000040000000400000000000000000000
0000000000000000000400000004000000040000000000000000000000000000
00000000000000000000000000040000000d0000004c415345525f4255525354
5f35010000000e00000053484f5447554e5f504c41594552010000000f000000
4c415345525f42555253545f325f4101000000080000004245414d5f42494f00
00000000000000030000000a000000435245575f5354494d530d000000454e45
5247595f534849454c440d00000054454c45504f52545f4845414c040000000f
0000004c415345525f42555253545f325f410f0000004c415345525f43484152
474547554e0c0000004c415345525f48554c4c5f3108000000494f4e5f535455
4e302c0000604f00003c000000c8000000000000000800000000000000ffffff
ff00000000000000000100000003000000000000000000000001000000120000
0001000000000000000100000000000000000000000100000000000000000000
0000000000010000000000000001000000000000000000000001000000000000
0001000000010000000700000000000000180000000000000001000000000000
00000000000100000000000000010000001700000073746172732f62675f6c6f
6e656c79737461722e706e671400000073746172732f706c616e65745f726564
2e706e67480100000d0100000000000001000000010000000a0000004c4f4e47
5f464c4545541100000053484950535f524542454c5f454c4954451f14000001
0000000000000000000000010000001a00000073746172732f62675f6c6f6e65
6c79526564537461722e706e671600000073746172732f706c616e65745f7065
6163682e706e670b03000047000000b400000001000000010000000a0000004c
4f4e475f464c4545541100000053484950535f524542454c5f454c495445fa25
0000010000000000000000000000000000000100000000000000000000000000
0000000000000000000001000000000000000000000000000000000000000100
00001700000073746172732f62675f64756c6c7374617273322e706e67180000
0073746172732f706c616e65745f626967626c75652e706e67a5010000030000
0000000000010000000000000000000000010000000000000000000000010000
0000000000010000000000000000000000000000000100000000000000000000
000000000000000000010000001a00000073746172732f62675f6c6f6e656c79
526564537461722e706e671400000073746172732f706c616e65745f7265642e
706e6701000000c5000000b40000000100000000000000000000000000000000
0000000000000001000000000000000100000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000001
0000000000000000000000000000000100000000000000010000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000001
0000000000000000000000000000000000000000000000010000000000000000
0000000000000000000000000000000100000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000001
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000100000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000ed2c00000000000000
0000001100000044455354524f5945445f44454641554c541100000044454144
5f435245575f44454641554c5400000000000000009d00000054686973206973
2069742e2e2e2054686520526562656c20666c6167736869702e20496620796f
75206172652061626c6520746f2064657374726f792074686973206d6f6e7374
726f736974792c207468652046656465726174696f6e20666c6565742077696c
6c20686176652061206368616e6365206f6620737572766976696e672e205468
6572652773206e6f207475726e696e67206261636b21ffffffff010000000000
000001000000010000000f000000424f53535f315f454153595f444c43120000
0073686f756c64206e6f74206265207365656e06000000626f73735f310b0000
000500000068756d616e0f0000004e6f7277796e20536368756c747a65050000
0068756d616e07000000486173736966610500000068756d616e050000004665
7272790500000068756d616e0b000000456e7a6f204d617274696e0500000068
756d616e0e0000005374657068656e2045636b6d616e0500000068756d616e06
0000004465636c616e0500000068756d616e070000004d6f6e7376696b050000
0068756d616e0700000058696e2058696e0500000068756d616e0b0000004f2e
2057696c6c69616d730500000068756d616e070000004d722042756761050000
0068756d616e05000000542774656e010000000000000000000000000000000a
00000010000000090000000a0000001e0000000c000000090000004672656465
7269636b09000000616e6165726f6269630000000022000000c0000000060100
0007000000000000000100000001000000670000000100000000000000000000
00000000000c0000000000000000000000000000000000000001000000090000
0001000000060000000600000000000000480000000100000000000000000000
0067000000e8030000000000006b000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000001000000000000
000000000000000000000000000000000000000000e803000000000000000000
00010000000b0000004d696b6520576573746f6e070000006372797374616c00
0000005c000000e3000000060100000700000001000000010000000100000068
0000000100000000000000000000000000000010000000000000000000000000
0000000000000000000000000000000100000001000000000000000000000049
00000000000000000000000000000068000000e8030000000000006b00000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
000000e803000018fcffff18fcffff0100000000000000000000000100000007
000000486173736966610500000068756d616e000000006400000051000000c0
00000011000000000000000000000000000000ffffffff020000000000000002
00000000000000ffffffffffffffff0000000000000000000000000000000000
0000000000000001000000040000000000000000000000000000000000000000
00000000000000ffffffffe8030000000000006b000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
000000000000000000000001000000000000000000000000000000e803000000
00000000000000000000000500000046657272790500000068756d616e000000
0064000000c00000001100000000000000000000000000000000000000ffffff
ff02000000000000000100000000000000ffffffffffffffff00000000000000
0000000000000000000000000000000000010000000100000000000000070000
0000000000000000000000000000000000ffffffffe8030000000000006b0000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000100000000000000000000
0000000000e80300000000000000000000000000000b000000456e7a6f204d61
7274696e0500000068756d616e000000003f000000e300000006010000070000
00010000000000000000000000ffffffff020000000000000000000000000000
00ffffffffffffffff0000000000000000000000000000000000000000000000
0001000000000000000000000000000000000000000000000000000000000000
00ffffffffe8030000000000006b000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
000000000001000000000000000000000000000000e803000000000000000000
00000000000e0000005374657068656e2045636b6d616e0500000068756d616e
0000000055000000c00000005700000001000000020000000000000000000000
ffffffff02000000000000000300000000000000ffffffffffffffff00000000
0000000000000000000000000000000000000000010000000100000000000000
0000000000000000000000000000000000000000ffffffffe803000000000000
6b00000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000100000000000000
0000000000000000e8030000000000000000000000000000060000004465636c
616e0500000068756d616e0000000055000000c0000000060100000700000000
0000000000000000000000ffffffff02000000000000000200000000000000ff
ffffffffffffff00000000000000000000000000000000000000000000000001
00000001000000000000000300000000000000000000000000000000000000ff
ffffffe8030000000000006b0000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
00000001000000000000000000000000000000e8030000000000000000000000
000000070000004d6f6e7376696b0500000068756d616e0000000064000000e3
0000002901000008000000010000000000000000000000ffffffff0200000000
0000000100000000000000ffffffffffffffff00000000000000000000000000
0000000000000000000000010000000300000000000000000000000000000000
0000000000000000000000ffffffffe8030000000000006b0000000000000000
0000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000001000000000000000000000000000000e8
0300000000000000000000000000000700000058696e2058696e050000006875
6d616e00000000640000007a0000003400000009000000000000000000000000
000000ffffffff02000000000000000200000000000000ffffffffffffffff00
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000ffffffffe803000000
0000006b00000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000100000000
0000000000000000000000e80300000000000000000000000000000b0000004f
2e2057696c6c69616d730500000068756d616e00000000640000002901000034
0000000a000000000000000000000000000000ffffffff020000000000000000
00000000000000ffffffffffffffff0000000000000000000000000000000000
0000000000000001000000000000000000000000000000000000000000000000
00000000000000ffffffffe8030000000000006b000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
000000000000000000000001000000000000000000000000000000e803000000
0000000000000000000000070000004d7220427567610500000068756d616e00
0000006400000092010000570000000e000000010000000000000000000000ff
ffffff02000000000000000300000000000000ffffffffffffffff0000000000
0000000000000000000000000000000000000001000000000000000000000000
00000000000000000000000000000000000000ffffffffe8030000000000006b
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000010000000000000000
00000000000000e803000000000000000000000000000005000000542774656e
0500000068756d616e0000000064000000110000005700000012000000000000
000000000000000000ffffffff02000000000000000300000000000000ffffff
ffffffffff000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000ffffff
ffe8030000000000006b00000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0001000000000000000000000000000000e80300000000000000000000000000
002a000000080000000800000000000000000000000000000000000000000000
00000000000000000000000000e8030000000000000100000002000000020000
0000000000000000000000000000000000000000000000000000000000000000
00e8030000000000000100000002000000020000000000000000000000000000
00000000002a000000000000000000000000000000e803000000000000010000
0000000000000000000300000003000000000000000000000000000000000000
0000000000000000000000000000000000e80300000000000001000000030000
0003000000000000000000000000000000000000000000000000000000000000
0000000000e80300000000000001000000000000000300000003000000000000
0000000000000000000000000000000000000000000000000000000000e80300
00000000000100000000000000020000000200000000000000040000008f2a00
000000000000000000000000000000000000000000e803000000000000010000
0003000000030000000000000000000000000000000000000000000000000000
000000000000000000e803000000000000010000000300000003000000000000
0000000000000000000000000000000000000000000000000000000000e80300
0000000000010000000300000003000000000000000000000000000000000000
0000000000000000000000000000000000e80300000000000001000000030000
0003000000000000000000000000000000000000000000000000000000000000
0000000000e80300000000000001000000000000000000000000000000030000
0003000000000000000400000083410000000000000000000000000000000000
0000000000e80300000000000001000000040000000000000000000000000000
00000000000000000001000000e803000000000000000000002e46040018c306
0000000000000000001027000018270000640000000000000000000000ffffff
ff0000000000000000ffffffff00000000020000006400000000000000000000
00ffffffff0000000000000000ffffffff0000000000000000ffffffff000000
0000000000ffffffff0200000000000000640000000000000000000000ffffff
ff0000000000000000ffffffffffffffff040000006400000000000000000000
00ffffffff0000000000000000ffffffffffffffff0400000064000000000000
0000000000ffffffff0000000000000000ffffffffffffffff04000000220000
000000000000000000ffffffff0000000000000000ffffffff00000000000000
00ffffffff0000000000000000ffffffffffffffff0400000064000000000000
0000000000ffffffff0000000000000000ffffffff0000000000000000ffffff
ff0000000000000000ffffffffffffffff040000001000000000000000000000
00ffffffff0000000000000000ffffffffffffffff0400000064000000000000
0000000000ffffffff0000000000000000ffffffff0000000000000000ffffff
ff0000000000000000ffffffff01000000020000006400000000000000000000
00ffffffff0000000000000000ffffffff000000000200000064000000000000
0000000000ffffffff0000000000000000ffffffff0000000002000000640000
000000000000000000ffffffff0000000000000000ffffffffffffffff040000
00640000000000000000000000ffffffff0000000000000000ffffffff000000
0000000000ffffffff0000000000000000ffffffffffffffff04000000640000
000000000000000000ffffffff0000000000000000ffffffffffffffff040000
00640000000000000000000000ffffffff0000000000000000ffffffff010000
0002000000640000000000000000000000ffffffff0000000000000000ffffff
ff0000000000000000ffffffff0000000000000000ffffffffffffffff040000
00640000000000000000000000ffffffff0000000000000000ffffffffffffff
ff04000000640000000000000000000000ffffffff0000000000000000ffffff
ff0000000002000000640000000000000000000000ffffffff00000000000000
00ffffffff000000000200000000000000100000001000000010000000000000
0000000000020000000000000010000000100000001000000000000000000000
0002000000000000001000000010000000100000000000000000000000020000
0000000000100000001000000010000000000000000000000002000000000000
0010000000100000001000000000000000000000000200000000000000100000
0010000000100000000000000000000000020000000000000010000000100000
0010000000000000000000000002000000000000001000000010000000100000
0000000000000000000200000000000000100000001000000010000000010000
0000000000020000000000000010000000100000001000000000000000000000
000200000000000000100000000f000000100000000000000000000000020000
0000000000100000001000000010000000000000000100000002000000000000
0010000000100000001000000000000000000000000200000000000000100000
0010000000100000000000000000000000020000000000000010000000100000
0010000000000000000000000002000000000000000000000000000000000000
0000000000000000000000000000000000000000009cffffff9bffffff000000
000000000000000000000000000b000000000000000000000000000000020000
00000000000000000017170000220300000100000003000000e09304007228ff
ffe0930400113cffffb8880000e8df0500d8530100b01e0400010000006d0900
0001000000050000000300000002000000000000000000000000000000000000
00ffffffffffffffff00000000000000000000000000000000d0070000000000
000100000000000000000000000e0000006578706c6f73696f6e5f6269673309
0000006d697373696c655f3100000000000000000000000000000000e8030000
000000000000000000000000000000000000000000000000e803000000000000
000000000000000061ecffff00000000000000000e000000736d616c6c457870
6c6f73696f6e0a000000686974536869656c6431040000006d697373ee000000
00000000000000000100000000000000
[/code]

**Comment by Niels-NTG** [comment]
Where you playing FTL while trying to open the save file?

Or did you quit the game while you where in combat? If so, try quitting the game at a "safe" spot and try to load the save game again. I'm curious to see if the problem persists.

**Comment by Vhati** [comment]
The projectile bug has been fixed in v26.
