### ISSUE TITLE
Support IOS game save files?

### ISSUE THREAD

**Issue by Thunder33345** [Vhati/ftl-profile-editor#90]
Current issue with IOS version is there only continue.sav and profile.sav also a setting.ini(which is just setting in plain text) but the required data.dat is nowhere to be found

**Comment by Niels-NTG** [comment]
So how exactly do you obtain the `continue.sav` and `profile.sav` files from the iOS version? I personally don't own this version of the game. Is there an export button? Can you obtain them via Game Center? Do you use a jailbroken version of iOS?

**Comment by Thunder33345** [comment]
@Niels-NTG Well i personally use jailbroken device by using a file manager and entering the save file location and transfer the save files to my PC

I think there other ways to do that without jailbreak but external tools on a PC but i am not very sure about it

**Comment by Niels-NTG** [comment]
If the general file structure of MacOS is anything to go by I would guess the `data.dat` is located inside the FTL application package.

**Comment by Thunder33345** [comment]
@Niels-NTG I would wish i could look into dat.dat and make a mockup replica of it so it could load IOS (maybe even android) but i dont have PC copies of it

**Comment by Vhati** [comment]
There have been threads investigating iPad modding.
http://www.ftlgame.com/forum/viewtopic.php?t=26855

Unfortunately it would be impractical to add support for that platform's resources. And the editor can't open a savedgame/profile if it can't see the resources that FTL used to generate them.

**Comment by Vhati** [comment]
A mockup might *technically* work (if the *.sav formats aren't also different), but distributing complete resources is forbidden on copyright grounds.

**Comment by Thunder33345** [comment]
oh ok thanks
i guess i dont have much i could do then try making a mockup data.dat or just purchase the PC version of the game

**Comment by Niels-NTG** [comment]
Just by the PC version. It's amazing.
