### ISSUE TITLE
SavedGame Parser Error

### ISSUE THREAD

**Issue by SirWoofie** [Vhati/ftl-profile-editor#91]
FTL: Advanced Captains Edition (Modded)
Saved and exited game while a modded missile weapon was fired, then opened the editor. Tried to save, but it couldn't, so I restarted the editor and it couldn't read the save.
Mods:
Shiny! UI Overhaul v0.991 CE.ftl
Better Planets and Backgrounds_v1.3.1.ftl
CE Resource Pack 1.265.ftl
FTL Captains Edition 1.265.ftl
CE Vanilla Portraits Patch.ftl
CE BPaB Compatibility Patch 1.0.ftl
CE Additional Music Addon 1.266.ftl
CE Infinite Addon 1.264.ftl
CE Additional Music Infinite Compatibility Patch 1.0.ftl
CE Endless Loot Addon for CE Infinite 1.264b.ftl
EL Texture Pack 1.261.ftl

[code]
SavedGame Parser Error

Exception: java.lang.RuntimeException: End of stream reached before reading enough bytes for an int

Stack Trace...
  net.blerf.ftl.parser.Parser.readInt(Parser.java:43)
  net.blerf.ftl.parser.SavedGameParser.readProjectile(SavedGameParser.java:1646)
  net.blerf.ftl.parser.SavedGameParser.readZeus(SavedGameParser.java:9238)
  net.blerf.ftl.parser.SavedGameParser.readSavedGame(SavedGameParser.java:244)
  net.blerf.ftl.ui.FTLFrame$11.actionPerformed(FTLFrame.java:802)

Editor Version: 25
OS: Windows 10 10.0
VM: Java HotSpot(TM) 64-Bit Server VM, 1.8.0_91, amd64
[/code]

File ("continue.sav")...
[code]
090000000100000001000000390000008c000000520600000700000001000000
5711000000504c415945525f534849505f4645445f3204000000000000000f00
00000a000000626c75655f616c69656e120000000e00000064657374726f7965
645f726f636b020000000a000000656e765f64616e6765720c0000000a000000
66697265645f73686f74d503000006000000686967686f32010000000b000000
6b696c6c65645f637265772d000000090000006c6f73745f6372657702000000
060000006e6562756c61160000000f00000072656163746f725f757067726164
65010000000e00000073746f72655f7075726368617365130000000c00000073
746f72655f726570616972450000000f000000737566666f63617465645f6372
6577861400000e00000073797374656d5f75706772616465050000000c000000
757365645f6d697373696c65180000000e000000776561706f6e5f7570677261
64650200000011000000504c415945525f534849505f4645445f320100000057
0d0000006665645f637275697365725f32030000000500000068756d616e0500
00004875736b7906000000656e6572677904000000536e6f7704000000736c75
6705000000446f676779010000005710010000000000000000000c0000000200
0000290000004f000000dd01000005000000050000004875736b790500000068
756d616e00000000640000007a000000c0000000070000000100000001000000
00000000ffffffff02000000080000000e000000000000000100000007000000
1a0000000000000000000000000000000b00000004000000010000000b000000
02000000790000008a000000020000000000000000000000ffffffffe8030000
00000000c6000000010000000100000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000001000000
000000000000000000000000e803000000000000000000000000000004000000
536e6f7706000000656e65726779000000002800000034000000290100000f00
0000020000000100000000000000ffffffff020000000c000000060000000000
0000020000000f000000000000001e00000000000000000000000f0000000300
0000010000000f00000002000000000000008a00000002000000000000000000
0000ffffffffe803000000000000c60000000000000000000000010000000100
0000000000000000000000000000000000000000000000000000000000000000
00000000000001000000000000000000000000000000e8030000000000000000
00000000000005000000446f67677904000000736c75670000000028000000d8
0100007a00000004000000010000000100000000000000ffffffff020000000f
0000000000000000000000010000000400000000000000000000000000000082
0000001d00000003000000010000001d00000003000000000000008a00000003
0000000000000000000000ffffffffe803000000000000c60000000000000000
0000000000000000000000000000000000000001000000010000000100000000
00000000000000000000000000000001000000000000000000000000000000e8
03000000000000000000000000000003000000536f6e060000006d616e746973
0000000064000000d8010000e30000000e000000010000000100000000000000
ffffffff010000000700000000000000010000000e0000000000000000000000
1a00000000000000020000000800000000000000020000000600000000000000
7b000000010000000000000000000000ffffffffe803000000000000c6000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000010000000000000000000000010000000000000000000000
00000000e8030000000000000000000000000000050000004b6172656e060000
006d616e74697300000000640000005700000034000000000000000100000001
00000000000000ffffffff010000000100000000000000010000000000000000
000000000000000000000000000000010000000b000000010000000100000002
0000000000000006000000000000000000000000000000ffffffffe803000000
000000c600000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000100000000
0000000000000000000000e80300000000000000000000000000000e00000004
0000000400000000000000000000000000000000000000000000000000000000
00000000000000e8030000000000000100000003000000010000000000000000
000000000000000000000000000000000000000000000000000000e803000000
0000000100000002000000010000000100000000000000000000000000000000
000000000000000000000000000000e803000000000000010000000500000003
0000000100000000000000000000004700000000000000000000000000000000
000000e803000000000000010000000000000001000000010000000000000000
000000000000000000000000000000000000000000000000000000e803000000
0000000100000001000000010000000000000000000000000000000000000000
000000000000000000000000000000e803000000000000010000000100000001
0000000000000000000000000000000000000000000000000000000000000000
000000e803000000000000010000000200000002000000000000000000000000
0000000000000000000000000000000000000000000000e80300000000000001
0000000000000000000000020000000200000000000000000000000000000000
00000000000000000000000000000000000000e8030000000000000100000000
0000000000000000000000000000000200000000000000000000000000000000
0000000000000001000000e80300000000000000000000559b0400a82dffff64
0000000000000000000000ffffffff0000000000000000ffffffff0100000000
000000640000000000000000000000ffffffff0000000000000000ffffffffff
ffffff04000000640000000000000000000000ffffffff0000000000000000ff
ffffff0000000000000000ffffffff0000000000000000ffffffffffffffff04
000000640000000000000000000000ffffffff0000000000000000ffffffffff
ffffff04000000640000000000000000000000ffffffff0000000000000000ff
ffffff0000000000000000ffffffff0000000000000000ffffffff0100000002
000000640000000000000000000000ffffffff0000000000000000ffffffffff
ffffff04000000640000000000000000000000ffffffff0000000000000000ff
ffffffffffffff04000000640000000000000000000000ffffffff0000000000
000000ffffffff0100000001000000640000000000000000000000ffffffff00
00000000000000ffffffffffffffff04000000640000000000000000000000ff
ffffff0000000000000000ffffffffffffffff04000000640000000000000000
000000ffffffff0000000000000000ffffffffffffffff040000006400000000
00000000000000ffffffff0000000000000000ffffffffffffffff0400000064
0000000000000000000000ffffffff0000000000000000ffffffffffffffff04
000000640000000000000000000000ffffffff0000000000000000ffffffffff
ffffff04000000640000000000000000000000ffffffff0000000000000000ff
ffffff0000000000000000ffffffff0000000000000000ffffffff0100000002
000000640000000000000000000000ffffffff0000000000000000ffffffff00
00000000000000ffffffff0000000000000000ffffffff020000000000000064
0000000000000000000000ffffffff0000000000000000ffffffffffffffff04
000000640000000000000000000000ffffffff0000000000000000ffffffff00
0000000000000000000000080000000800000008000000000000000000000001
0000000000000008000000080000000800000000000000000000000100000000
0000000800000008000000080000000000000000000000010000000000000008
0000000800000008000000000000000000000001000000000000000800000008
0000000800000000000000000000000100000000000000080000000800000008
0000000000000000000000010000000000000008000000080000000800000000
0000000000000001000000000000000800000008000000080000000000000000
0000000100000000000000080000000800000008000000000000000000000001
0000000000000008000000080000000800000000000000000000000100000000
0000000800000008000000080000000000000000000000010000000000000008
0000000800000008000000000000000000000001000000000000000800000008
0000000800000000000000000000000100000000000000080000000800000008
0000000000000000000000010000000000000008000000080000000800000000
0000000000000001000000000000000800000008000000080000000000000000
0000000100000000000000080000000800000008000000000000000000000001
0000000000000008000000080000000800000000000000000000000100000000
0000000800000008000000080000000000000000000000010000000000000008
0000000800000008000000000000000000000001000000000000000800000008
0000000800000000000000000000000100000000000000080000000800000008
0000000000000000000000010000000000000008000000080000000800000000
0000000000000001000000000000000800000008000000080000000000000000
0000000100000000000000080000000800000008000000000000000000000001
0000000000000008000000080000000800000000000000000000000100000000
0000000000000000000000040000001f00000042415f4c415345525f48554c4c
5f534d414c4c5f50454e4554524154494e47010000001f00000042415f4c4153
45525f48554c4c5f534d414c4c5f50454e4554524154494e47010000001c0000
004d495353494c45535f325f504c415945525f434f4e43555353494f4e010000
0017000000494f4e5f434841494e47554e5f554e52454c4941424c4500000000
00000000020000000d0000004155544f5f434f4f4c444f574e10000000574541
504f4e5f50524549474e495445020000001a000000424154544c455f5354414e
444152445f494e5445524e414c5f32080000004245414d5f42494f4e26000071
59000001fdffff4a000000000000000a00000000000000ab0f00000000000000
0000000000000000000000000000000000000000000000150000000100000000
0000000100000000000000000000000100000000000000000000000100000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000300000000000000180000000000000000
0000000000000000000000000000000000000001000000180000007374617273
2f7a5f62675f687562626c655f33312e706e672600000073746172732f7a5f58
2e30312e706c616e65745f726f636b795f62726f776e6973682e706e67800000
007f000000b40000000100000000000000000000000000000000000000010000
001800000073746172732f7a5f62675f687562626c655f32352e706e67260000
0073746172732f7a5f582e30312e706c616e65745f726f636b795f7265645f62
6c75652e706e67610100008b000000b400000001000000000000000000000000
0000000000000000000000010000000000000000000000000000000000000000
0000000100000000000000000000000000000000000000020000001800000073
746172732f7a5f62675f687562626c655f36302e706e67220000007374617273
2f7a5f706c616e65745f726f636b79726564343030783430302e706e67fe0200
004b000000b40000000100000000000000000000000000000001000000020000
0004000000010000000a00000074656c65706f72746572000000000100000008
000000636c6f6e656261790200000001000000040000006d696e640200000003
0000000100000004000000656e67690000000001000000060000006d616e7469
7300000000010000000500000068756d616e0000000000000000030000000200
0000010000001800000073746172732f7a5f62675f687562626c655f35322e70
6e672700000073746172732f7a5f582e30312e706c616e65745f79656c6c6f77
5f62726f776e6973682e706e67eb020000010000000000000001000000000000
0000000000000000000000000000000000010000000000000000000000000000
0000000000010000001500000073746172732f7a5f62675f7374617273332e70
6e67040000004e4f4e4500000000000000000000000001000000000000000000
00000000000000000000010000001800000073746172732f7a5f62675f687562
626c655f32362e706e671800000073746172732f7a5f706c616e65745f677265
656e2e706e67ae0000001b000000000000000100000000000000000000000000
000000000000010000001c00000073746172732f62675f6d696e65735f776172
6e696e675f312e706e67040000004e4f4e450000000000000000000000000100
0000010000000000000000000000000000000000000000000000000000000000
0000010000000000000000000000000000000000000000000000010000000000
0000000000000000000000000000000000000100000000000000000000000000
0000000000000000000001000000000000000000000000000000000000000000
0000010000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000100
00004b3e0000000000002800000043455f4d494e454c415945525f4d414e5449
535f48415a41524420657363617065202031303332371500000044455354524f
5945445f534849505f4d414e54495311000000444541445f435245575f444546
41554c542a00000043455f4d494e454c415945525f4d414e5449535f48415a41
524420676f742061776179202031303332390000000000000000ffffffff0200
0000020000000000000001000000000000002100000043455f4d414e5449535f
4d494e454c415945525f48415a4152445f4241444153531200000073686f756c
64206e6f74206265207365656e0e0000006d616e7469735f73636f75745f6302
000000060000006d616e746973040000004b6f6f6404000000656e6769070000
004976616e6f7661010000000000000000000000000000000100000010000000
0000000001000000c501000002000000040000004b6f6f64060000006d616e74
6973000000005900000057000000570000000200000001000000000000000000
0000ffffffff010000000b00000000000000ffffffffffffffff000000000000
0000000000000000000000000000000000000100000000000000000000000500
000000000000000000000000000000000000ffffffffe803000000000000c600
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000001000000000000000000
000000000000e8030000000000000000000000000000070000004976616e6f76
6104000000656e6769000000000a000000060100001100000000000000000000
000000000000000000ffffffff03000000010000000400000000000000000000
00ffffffffffffffff0000000000000000000000000000000000000000000000
0000000000020000000000000000000000000000000000000082160000000000
00ffffffffe803000000000000c6000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
000000000001000000000000000000000000000000e803000000000000000000
00000000001300000006000000000000000500000000000000000000003f0000
0000000000000000000000000000000000e80300000000000001000000020000
0002000000000000000000000000000000000000000000000000000000000000
0000000000e80300000000000001000000020000000100000001000000000000
00000000000000000000000000000000000000000000000000e8030000000000
0001000000050000000400000001000000000000000000000000000000000000
00000000000000000000000000e8030000000000000100000000000000000000
0001000000010000000000000000000000000000000000000000000000000000
000000000000000000e803000000000000010000000000000001000000000000
00010000000000000000000000000000002b0000000000000000000000000000
00e8030000000000000100000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
00010000000000000000000000000000000941ffff33d3ffff64000000640000
0000000000ffffffff6400000064000000ffffffff0000000003000000180000
006400000064000000ffffffff0000000000000000ffffffff00000000020000
00630000000000000064000000ffffffff4c00000000000000ffffffff010000
0000000000640000000000000000000000ffffffff0000000064000000ffffff
ff0000000001000000640000000000000000000000ffffffff000000000b0000
00ffffffffffffffff04000000640000006400000000000000ffffffff000000
0064000000ffffffffffffffff04000000640000006400000000000000ffffff
ff0000000000000000ffffffffffffffff040000001900000064000000640000
00ffffffff0000000000000000ffffffff010000000100000002000000060000
0001000000640000000500000001000000640000000400000004000000040000
0000000000000000000000000000000000040000000400000004000000000000
0000000000000000000000000004000000040000000400000000000000000000
0000000000000000000400000004000000040000000000000000000000000000
0000000000040000000400000004000000000000000000000000000000000000
0004000000040000000400000000000000000000000000000000000000040000
0004000000040000000000000000000000000000000000000000000000000000
00040000001700000042415f4d494e45535f534d414c4c5f48415a4152445f32
010000001e00000042415f4d495353494c45535f434f434b4154524943455f43
415553544943010000002100000042415f4c415345525f42555253545f534341
545445525f315f4f55544441544544000000001700000042415f53484f544755
4e5f534d414c4c5f435553544f4d0100000000000000020000000d0000004155
544f5f434f4f4c444f574e0a000000435245575f5354494d5301000000000000
00000000000100000000000000983a0000000000000000000000000000010000
00000000000000000000000000020000000000000000000000954e0000000000
000c00000001000000282e0a004db8000059350a0067b4000018790000e2c805
00611a0300ef4f02000100000041060000000000000000000000000000000000
0000000000000000000000000000000000ffffffff4106000000000000000000
000000000000000000d007000000000000000000000000000000000000120000
006578706c6f73696f6e5f6d697373696c65310c0000006465627269735f736d
616c6c00000000000000000000000000000000fa000000000000000000000000
000000000000000000000000000000e80300000000000000000000cff8ffffe6
03000000000000000000000b000000666c616b496d70616374330a0000006869
74536869656c6431040000006d69737354010000000000000000000004000000
0000000047a0180080fc0a0001000000193a0a004fdc0000ef400a00cfd70000
187900006dac0500c0db0300d03c020001000000400600000000000000000000
000000000000000000000000000000000000000000000000ffffffff40060000
00000000000000000000000000000000d0070000000000000000000000000000
00000000120000006578706c6f73696f6e5f6d697373696c65310c0000006465
627269735f736d616c6c00000000000000000000000000000000fa0000000000
00000000000000000000000000000000000000000000e8030000000000000000
00002bf9ffff7f04000000000000000000000b000000666c616b496d70616374
320a000000686974536869656c6433040000006d697373540100000000000000
000000040000000000000045db180080fc0a0001000000cd270a00e5bd0000fa
2e0a00f7b9000018790000b2800500524a0300f84e0200010000003f06000000
00000000000000000000000000000000000000000000000000000000000000ff
ffffff3f06000000000000000000000000000000000000d00700000000000000
0000000000000000000000120000006578706c6f73696f6e5f6d697373696c65
310c0000006465627269735f736d616c6c000000000000000000000000000000
00fa000000000000000000000000000000000000000000000000000000e80300
000000000000000000d3f8ffffee03000000000000000000000b000000666c61
6b496d70616374320a000000686974536869656c6433040000006d6973735401
000000000000000000000400000000000000a64e180080fc0a00010000009541
0a004fe7000047480a009ae20000187900000d4406004bb50300023602000100
00003e0600000000000000000000000000000000000000000000000000000000
000000000000ffffffff3e06000000000000000000000000000000000000d007
000000000000000000000000000000000000120000006578706c6f73696f6e5f
6d697373696c65310c0000006465627269735f736d616c6c0000000000000000
0000000000000000fa0000000000000000000000000000000000000000000000
00000000e803000000000000000000004ff9ffffb40400000000000000000000
0b000000666c616b496d70616374320a000000686974536869656c6431040000
006d69737354010000000000000000000004000000000000002df7140080fc0a
00010000000b400a0019e50000c4460a0070e0000018790000f1e50500f1e903
0063370200010000003d06000000000000000000000000000000000000000000
00000000000000000000000000ffffffff3d0600000000000000000000000000
0000000000d00700000000000000000000000000000000000012000000657870
6c6f73696f6e5f6d697373696c65310c0000006465627269735f736d616c6c00
000000000000000000000000000000fa00000000000000000000000000000000
0000000000000000000000e8030000000000000000000047f9ffffa904000000
000000000000000b000000666c616b496d70616374320a000000686974536869
656c6432040000006d6973735401000000000000000000000400000000000000
054b160080fc0a00010000004b390a0013db000024400a0099d6000018790000
5839060047780300913d0200010000003c060000000000000000000000000000
0000000000000000000000000000000000000000ffffffff3c06000000000000
000000000000000000000000d007000000000000000000000000000000000000
120000006578706c6f73696f6e5f6d697373696c65310c000000646562726973
5f736d616c6c00000000000000000000000000000000fa000000000000000000
000000000000000000000000000000000000e8030000000000000000000027f9
ffff7904000000000000000000000b000000666c616b496d70616374330a0000
00686974536869656c6432040000006d69737354010000000000000000000004
0000000000000016e9170080fc0a0001000000103f0a00aee30000cd450a000b
df000018790000f512060068c2030044380200010000003b0600000100000000
000000010000000100000000000000000000000000000000000000ffffffff3b
06000000000000000000000100000000000000d0070000000000000000000000
00000000000000120000006578706c6f73696f6e5f6d697373696c65310a0000
006465627269735f6d656400000000000000000000000000000000e803000000
0000000000000000000000000000000000000000000000e80300000000000000
00000043f9ffffa304000000000000000000000b000000666c616b496d706163
74320a000000686974536869656c6432040000006d6973735401000000000000
000000000400000000000000de98180080fc0a00010000004d350a00dbd40000
393c0a007fd0000018790000cdf405004d82030058410200010000003a060000
0100000000000000010000000100000000000000000000000000000000000000
ffffffff3a06000000000000000000000100000000000000d007000000000000
000000000000000000000000120000006578706c6f73696f6e5f6d697373696c
65310a0000006465627269735f6d656400000000000000000000000000000000
e8030000000000000000000000000000000000000000000000000000e8030000
000000000000000014f9ffff5c04000000000000000000000b000000666c616b
496d70616374340a000000686974536869656c6431040000006d697373540100
0000000000000000000400000000000000456a160080fc0a0003000000fd0104
00ce890000ba0a0400878d0000b888000070ff0300b8880000fc9afdff000000
0042060000020000000500000001000000010000000000000000000000000000
0000000000ffffffff4206000000000000000000000000000006000000d00700
00010000000100000001000000000000000e0000006578706c6f73696f6e5f62
6967320e0000006d697373696c655f325f6461726b0100000000000000020000
0036010000e80300000083ffff0083ffff000000000000000000000000000000
00e8030000000000000000000043f7ffff48fcffff00000000010000000e0000
00736d616c6c4578706c6f73696f6e0a000000686974536869656c6431040000
006d6973730600000001000000000000000100000000000000
[/code]

**Comment by Vhati** [comment]
> Saved and exited game while a modded missile weapon was fired, then opened the editor. Tried to save, but it couldn't,

Perfect description. It's a known bug. Thanks for the reminder.

There's a glitch in the missile saving code that corrupts the file, when writing any changes back to disk if missiles are on-screen.

This makes editing files that were created during combat risky. If you're lucky, you may be able to resume your game by renaming the backup file in that same folder. For now, try to save in peaceful situations. The next release will correct that glitch, and I have no excuse for why I haven't put that out months ago. I'm sorry.  =/

**Comment by SirWoofie** [comment]
Thanks for the tip, was in a risky situation anyways.

**Comment by Vhati** [comment]
Fixed in v26.
