### ISSUE TITLE
SavedGame Parser Error

### ISSUE THREAD

**Issue by Adarious** [Vhati/ftl-profile-editor#93]
[code]
SavedGame Parser Error

Exception: java.lang.RuntimeException: Not a bool: 2

Stack Trace...
  net.blerf.ftl.parser.Parser.readBool(Parser.java:21)
  net.blerf.ftl.parser.SavedGameParser.readSavedGame(SavedGameParser.java:84)
  net.blerf.ftl.ui.FTLFrame$11.actionPerformed(FTLFrame.java:802)
  javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
  javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)

Editor Version: 25
OS: Windows 8.1 6.3
VM: Java HotSpot(TM) 64-Bit Server VM, 1.8.0_111, amd64
[/code]

File ("ae_prof.sav")...
[code]
0900000002000000030000000c0000004143485f534543544f525f3500000000
0c0000004143485f534543544f525f38000000000d0000004143485f4e4f5f44
524f4e4553000000000100000000000000000000000000000000000000000000
0001000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
000000000000000000050000000b000000546865204b65737472656c10000000
504c415945525f534849505f48415244a4090000070000000000000000000000
000000000b000000546865204b65737472656c10000000504c415945525f5348
49505f4841524408070000050000000000000000000000000000000b00000054
6865204b65737472656c10000000504c415945525f534849505f484152443305
0000040000000000000000000000000000000b000000546865204b6573747265
6c10000000504c415945525f534849505f48415244a104000005000000000000
0000000000000000000b000000546865204b65737472656c10000000504c4159
45525f534849505f48415244f503000003000000000000000100000000000000
050000000b000000546865204b65737472656c10000000504c415945525f5348
49505f48415244a4090000070000000000000000000000000000000b00000054
6865204b65737472656c10000000504c415945525f534849505f484152440807
0000050000000000000000000000000000000b000000546865204b6573747265
6c10000000504c415945525f534849505f484152443305000004000000000000
0000000000000000000b000000546865204b65737472656c10000000504c4159
45525f534849505f48415244a104000005000000000000000000000000000000
0900000054686520546f72757312000000504c415945525f534849505f434952
434c45b10200000300000000000000000000000000000016000000930000004b
000000fa01000026050000e41900000800000056000000120000000000000015
0000000c00000042727563652042616e6e65720500000068756d616e01000000
10000000070000004c6975204a756e04000000726f636b010000007e00000007
0000004d6f6e7376696b0500000068756d616e01000000520000000c00000042
727563652042616e6e65720500000068756d616e01000000040000000c000000
42727563652042616e6e65720500000068756d616e01000000
[/code]

**Comment by Adarious** [comment]
This is what happened when I went to load my save, which, being in sector 8 for the first time with dinky weapons, I hoped would work.

**Comment by Vhati** [comment]
"ae_prof.sav" is a profile, which contains high scores and achievements across campaigns.

Saved games are called "continue.sav".

Make sure you're in the appropriate tab before clicking the "open" button.

.

Sidenote: Avoid saving during combat. There's a bug in the editor that causes corruption when writing a saved game that has certain projectiles/asteroids on the screen.

If you do run into that, there will still be a backup (*.bak) in the same folder, which you can rename to continue playing.
