### ISSUE TITLE
"Your saved game could not be interpreted correctly."

### ISSUE THREAD

**Issue by ArchangelX1** [Vhati/ftl-profile-editor#94]
[code]
SavedGame Parser Error

Exception: java.lang.IllegalArgumentException: Color parameter outside of expected range: Red Green Blue

Stack Trace...
  java.awt.Color.testColorValueRange(Unknown Source)
  java.awt.Color.<init>(Unknown Source)
  java.awt.Color.<init>(Unknown Source)
  net.blerf.ftl.ui.SavedGameFloorplanPanel$RoomSprite.referenceChanged(SavedGameFloorplanPanel.java:4105)
  net.blerf.ftl.ui.SavedGameFloorplanPanel$RoomSprite.<init>(SavedGameFloorplanPanel.java:4078)

Editor Version: 25
OS: Windows 10 10.0
VM: Java HotSpot(TM) Client VM, 1.8.0_131, x86
[/code]

File ("continue.sav")...
[code]
090000000100000002000000100000005f000000700200000d00000009000000
4361726e656c69616e15000000504c415945525f534849505f4352595354414c
5f3205000000000000000b0000000a000000656e765f64616e67657205000000
0a00000066697265645f73686f74bd0100000b0000006b696c6c65645f637265
7719000000090000006c6f73745f6372657701000000060000006e6562756c61
160000000f00000072656163746f725f75706772616465010000000e00000073
746f72655f7075726368617365150000000e00000073797374656d5f75706772
6164650b0000000a000000757365645f64726f6e65150000000c000000757365
645f6d697373696c655c0000000e000000776561706f6e5f7570677261646501
00000015000000504c415945525f534849505f4352595354414c5f3209000000
4361726e656c69616e110000006372797374616c5f637275697365725f320300
0000070000006372797374616c06000000536f70686961070000006372797374
616c0400000057696c6c070000006372797374616c0f0000004e6f7277796e20
536368756c747a6501000000a086010000000000000000001e000000e7030000
e1030000e7030000e70300000800000006000000536f70686961070000006372
797374616c000000007d0000004c010000290100000f00000000000000010000
0001000000ffffffff010000000200000000000000000000000f0000001e0000
001e0000006e0000008200000024000000100000000000000004000000030000
00610000005e000000000000000000000000000000ffffffffe8030000000000
006a000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000001000000000000
000000000000000000e803000000000000000000000000000050c3000050c300
00000000000f0000004e6f7277796e20536368756c747a650700000063727973
74616c000000007d000000c00000005700000001000000010000000100000001
000000ffffffff01000000030000000000000001000000040000001e0000001e
0000006e00000082000000240000001000000001000000010000000000000000
0000005e000000000000000000000000000000ffffffffe8030000000000006a
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000010000000000000000
00000000000000e803000000000000000000000000000050c3000050c3000000
000000050000004265726b6f04000000656e6769000000006400000011000000
9d00000002000000020000000100000001000000ffffffff0000000000000000
ffffffffffffffff1e0000001e0000006e000000820000002400000010000000
0100000003000000000000000000000059000000000000000000000000000000
ffffffffe8030000000000006a00000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000001000000000000000000000000000000e80300000000000000000000
00000000050000004665726173060000006d616e746973000000006400000029
0100009d00000004000000010000000100000001000000ffffffff0100000002
00000000000000ffffffffffffffff1e0000001e0000006e0000008200000024
00000010000000010000000100000003000000000000004c0000000000000000
00000000000000ffffffffe8030000000000006a000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000000000e803000000
000000000000000100000009000000546f6d2042616e6b7304000000656e6769
000000006400000029010000290100000e000000010000000100000001000000
ffffffff0000000000000000ffffffffffffffff1e0000001e0000006e000000
820000002400000010000000010000000100000001000000000000004c000000
000000000000000000000000ffffffffe8030000000000006a00000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
e80300000000000000000000010000000400000052656d6f0500000068756d61
6e00000000640000009d000000e30000000a0000000000000001000000010000
00ffffffff02000000000000000200000000000000ffffffffffffffff1a0000
001a0000006400000074000000200000000e0000000100000001000000030000
00000000004c000000000000000000000000000000ffffffffe8030000000000
006a000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
000000000000000000e80300000000000000000000010000000e000000537465
76656e2044656e676c6572060000006d616e7469730000000064000000060100
00c000000004000000020000000100000001000000ffffffff01000000030000
0000000000ffffffffffffffff1e0000001e0000006e00000082000000240000
0010000000010000000000000002000000000000003d00000000000000000000
0000000000ffffffffe8030000000000006a0000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000e8030000000000
000000000001000000050000004e6f656d69060000006d616e74697300000000
64000000060100009d00000004000000000000000100000001000000ffffffff
010000000400000000000000ffffffffffffffff1e0000001e0000006e000000
8200000024000000100000000000000000000000000000000000000032000000
000000000000000000000000ffffffffe8030000000000006a00000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
e803000000000000000000000100000019000000080000000800000000000000
00000000362300000000000000000000000000000000000000000000e8030000
0000000001000000080000000700000000000000000000000000000000000000
00000000000000000000000000000000e8030000000000000100000003000000
0000000000000000000000000000000000000000000000000000000000000000
00000000e8030000000000000100000008000000070000000000000000000000
000000000000000000000000000000000000000000000000e803000000000000
0100000008000000010000000000000000000000000000000000000000000000
000000000000000000000000e803000000000000010000000000000003000000
0300000000000000000000000000000000000000000000000000000000000000
00000000e8030000000000000100000003000000030000000000000000000000
000000000000000000000000000000000000000000000000e803000000000000
0100000003000000030000000000000000000000000000000000000000000000
000000000000000000000000e803000000000000010000000300000000000000
0000000000000000000000000000000000000000000000000000000000000000
e803000000000000010000000300000000000000000000000000000000000000
0000000000000000000000000000000000000000e80300000000000001000000
0000000000000000030000000000000000000000000000000000000000000000
00000000000000000000000000000000e8030000000000000100000000000000
0000000000000000e02e000018fcffff04000000000000000000000000000000
000000000000000001000000e80300000000000000000000c244040016460600
00000000000000000000000000000080000000800000000000000000ffffffff
0000000000000000ffffffffffffffff04000000000000800000000000000000
ffffffff0000000000000000ffffffff0000000000000000ffffffff00000000
00000000ffffffff0100000002000000000000800000000000000000ffffffff
0000000000000000ffffffff0000000000000000ffffffff0000000000000000
ffffffff0200000000000000000000800000000000000000ffffffff00000000
00000000ffffffff0000000000000000ffffffff0000000000000000ffffffff
ffffffff04000000000000800000000000000000ffffffff0000000000000000
ffffffff0000000000000000ffffffff0000000000000000ffffffff01000000
02000000000000800000000000000000ffffffff0000000000000000ffffffff
ffffffff04000000000000800000000000000000ffffffff0000000000000000
ffffffffffffffff04000000000000800000000000000000ffffffff00000000
00000000ffffffff0000000000000000ffffffff0000000000000000ffffffff
ffffffff04000000000000800000000000000000ffffffff0000000000000000
ffffffffffffffff04000000000000800000000000000000ffffffff00000000
00000000ffffffff0000000000000000ffffffff0000000000000000ffffffff
ffffffff04000000000000800000000000000000ffffffff0000000000000000
ffffffff0000000002000000000000800000000000000000ffffffff00000000
00000000ffffffffffffffff04000000000000800000000000000000ffffffff
0000000000000000ffffffffffffffff04000000000000800000000000000000
ffffffff0000000000000000ffffffff0000000000000000ffffffff00000000
00000000ffffffffffffffff04000000000000800000000000000000ffffffff
0000000000000000ffffffff0100000002000000000000800000000000000000
ffffffff0000000000000000ffffffff0000000001000000000000000f000000
0f0000000f000000000000000000000003000000000000000f0000000f000000
0f000000000000000000000003000000000000000f0000000f0000000f000000
000000000000000003000000000000000f0000000f0000000f00000000000000
0000000003000000000000000f0000000f0000000f0000000000000000000000
03000000000000000f0000000f0000000f000000000000000000000003000000
000000000f0000000f0000000f00000000000000000000000300000000000000
0f0000000f0000000f000000000000000000000003000000000000000f000000
0f0000000f000000000000000000000003000000000000000f0000000f000000
0f000000000000000000000003000000000000000f0000000f0000000f000000
000000000000000003000000000000000f0000000f0000000f00000000000000
0000000003000000000000000f0000000f0000000f0000000000000000000000
03000000000000000f0000000f0000000f000000000000000000000003000000
000000000f0000000f0000000f00000000000000000000000300000000000000
0f0000000f0000000f000000000000000000000003000000000000000f000000
0f0000000f000000000000000000000003000000000000000f0000000f000000
0f000000000000000000000003000000000000000f0000000f0000000f000000
000000000000000003000000000000000f0000000f0000000f00000000000000
00000000030000000000000000000000000000000400000008000000494f4e5f
5354554e010000000d0000004d495353494c45535f48554c4c01000000090000
004245414d5f46495245010000000f0000004c415345525f42555253545f325f
41010000000200000009000000444546454e53455f310000000000000000ffff
ffffffffffffffffffffffffffff010000000600000052455041495201000000
01000000c0000000290100000d0000000000000019000000030000000d000000
4155544f5f434f4f4c444f574e09000000494f4e5f41524d4f52100000005745
41504f4e5f50524549474e49544504000000110000004c415345525f43484152
474547554e5f320d000000434f4d4241545f4245414d5f320c000000494f4e5f
434841494e47554e0c0000004c415345525f48554c4c5f31bb7b0000880b0000
41fcffffe4000000bf79feff0700000000000000ffffffff0000000000000000
0000000000000000000000000000000000000000130000000100000001000000
0000000001000000000000000000000000000000010000000000000001000000
0000000000000000000000000000000000000000000000000000000000000000
0000000004000000000000001800000000000000000000000000000000000000
0000000000000000000000000100000000000000000000000000000000000000
010000001700000073746172732f62675f6461726b6e6562756c612e706e6716
00000073746172732f706c616e65745f62726f776e2e706e678f000000140000
00b4000000010000000000000000000000000000000000000001000000170000
0073746172732f62675f64756c6c7374617273322e706e671600000073746172
732f706c616e65745f70656163682e706e67eb010000a1000000000000000100
0000000000000000000000000000010000000200000001000000010000000600
0000424154544c4500000000010000000a000000414e54495f44524f4e450000
0000000000000d000000434f4d4241545f4245414d5f32000000000000000001
00000009000000424f4d425f464952450000000001000000090000004245414d
5f48554c4c00000000000000000c000000494f4e5f434841494e47554e000000
0005000000030000000200000000000000000000000000000000000000000000
0000000000000000000100000000000000000000000000000000000000000000
000100000000000000000000000000000000000000010000001a000000737461
72732f62675f6c6f6e656c79526564537461722e706e671b0000007374617273
2f706c616e65745f6761735f79656c6c6f772e706e676203000001000000b400
0000010000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000010000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000a07e0000100000005049524154455f53555252454e4445520d0000005049
524154455f4553434150451100000044455354524f5945445f44454641554c54
11000000444541445f435245575f44454641554c540000000000000000aa0000
00596f752061727269766520746f2066696e642061206c756d626572696e6720
5a6f6c74616e206672656967687465722077697468206e6f206f6e6520617420
7468652068656c6d2e20497427732061206d7973746572792077686174206861
7070656e656420746f2074686520637265772c20627574206974276420626520
61207368616d6520746f206c657420746865206f70706f7274756e6974792067
6f20746f2077617374652effffffff0100000000000000000000000000000000
00000000000000020000000000000000000000910c0000000000000000000000
000000000000000000000000000000000000004be20100eb2affffa3e1010014
2bffff05f801008a25ffff0000008000000080000000800000008000000000e1
0800000000000000000000e8030000501aae0044ba040000000000ffffff7f00
000000000000000000000044ba040000000000a8000000d7ffffff0000000000
0000000800000000000000e80300000000000000000000010000000100000004
000000401f0000401f0000000000000000000000000000010000000000000000
0000000100000000000000010000000100000000000000010000007d000000e8
0300000000000000000000e80300000000000000000000ffffffff0000000000
0000000000000000000000e803000018fcffff18fcffffffffffff0000000020
3500002035000000000000000000000000000001000000000000000000000001
00000000000000010000000100000000000000010000004d010000e803000000
00000000000000e80300000000000000000000ffffffff000000000000000000
00000000000000e803000018fcffff18fcffffffffffff00000000803e000080
3e00000000000000000000000000000100000000000000000000000100000000
0000000100000001000000000000000100000064000000e80300000000000000
000000e80300000000000000000000ffffffff00000000000000000000000000
000000e803000018fcffff18fcffff3f06000000000000602200006022000000
0000000000000000000000010000000000000000000000010000000000000001
000000010000000000000005000000a0010000e80300000000000000000000e8
0300000000000000000000ffffffff00000000000000000000000000000000e8
03000018fcffff18fcffffffffffff0000000000000000000000000100000000
00000001000000307500000000000000000000
[/code]

**Comment by Niels-NTG** [comment]
> Color parameter outside of expected range: Red Green Blue

Hmm… Haven't seen one of those before. Could you tell us some more about your save file?

**Comment by Vhati** [comment]
The player ship's first room's oxygen is read as MIN_INT (-2147483648), where one would expect 0-100. Extended systems info comes before the rooms chunk: clonebay/shields/cloaking read okay. So the parser wasn't getting lost in a system chunk.

My FTL game (1.5.13 Win7) can still load it. However, after a save+quit, the oxygen is 0, and the editor doesn't complain.

There IS precedent for MIN_INT appearing elsewhere to mean "not applicable", but I haven't seen that on oxygen before (which is why the editor panics). MIN_INT might indeed be a valid value, however FTL tends to tolerate garbage and substitute what it prefers at load time (e.g., replacing with zero).

I don't see how MIN_INT could've been put there by the editor.
I notice the oxygen system is powered off. Hmm...

Do tell us more about this savedgame, ArchangelX1. Can you reproduce this bug?
![ae_archangelx1_001_01-1](https://cloud.githubusercontent.com/assets/2262621/26619891/7efdd3be-45ae-11e7-9d73-7d4c6f6263ca.jpg)
