### ISSUE TITLE
problem with profile editing (can't read save)

### ISSUE THREAD

**Issue by stonykid** [Vhati/ftl-profile-editor#95]
[code]
Profile Parser Error

Exception: java.lang.RuntimeException: Not a bool: 15

Stack Trace...
  net.blerf.ftl.parser.Parser.readBool(Parser.java:21)
  net.blerf.ftl.parser.ProfileParser.readShipUnlocks(ProfileParser.java:317)
  net.blerf.ftl.parser.ProfileParser.readProfile(ProfileParser.java:84)
  net.blerf.ftl.ui.FTLFrame$4.actionPerformed(FTLFrame.java:403)
  javax.swing.AbstractButton.fireActionPerformed(Unknown Source)

Editor Version: 25
OS: Windows 10 10.0
VM: Java HotSpot(TM) 64-Bit Server VM, 1.8.0_131, amd64
[/code]

File ("continue.sav")...
[code]
0900000001000000000000000f0000002c0000006f020000030000000b000000
546865204b65737472656c10000000504c415945525f534849505f4841524406
000000000000000b0000000e00000064657374726f7965645f726f636b010000
000a000000656e765f64616e676572010000000a00000066697265645f73686f
74ed00000006000000686967686f32010000000b0000006b696c6c65645f6372
657703000000090000006c6f73745f6372657702000000060000006e6562756c
61030000000f00000072656163746f725f75706772616465010000000e000000
73746f72655f70757263686173656a0000000e00000073797374656d5f757067
726164650d0000000e000000776561706f6e5f75706772616465010000001000
0000504c415945525f534849505f484152440b000000546865204b6573747265
6c070000006b65737472616c030000000500000068756d616e0b000000437261
696720446f6c616e0500000068756d616e0500000046696c6970050000006875
6d616e050000004e6f74636801000000084c010000000000000000001e000000
1be1f50523e1f50532e1f505f68c9800080000000500000046696c6970070000
006372797374616c000000007d00000034000000c00000000e00000002000000
0100000001000000ffffffff010000000000000000000000020000000e000000
000000001e000000000000000000000024000000100000000100000000000000
00000000000000002b000000000000000000000000000000ffffffffe8030000
000000000f000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000001000000
000000000000000000000000e803000000000000000000000000000000000000
0000000000000000050000004e6f74636806000000656e657267790000000046
000000c00000009d0000000a000000010000000100000001000000ffffffff01
0000000000000000000000010000000a00000000000000000000000000000082
0000002400000010000000010000000000000000000000000000002b00000000
0000000000000000000000ffffffffe8030000000000000f0000000000000000
0000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000001000000000000000000000000000000e8
03000000000000000000000000000007000000546565204c656b060000006d61
6e746973000000000000000034000000e3000000ffffffffffffffff01000000
000000000f000000010000000000000000000000000000000f00000000000000
0000000000000000000000002400000010000000010000000000000001000000
000000002b0000000000000000000000000000000f000000e803000000000000
0f00000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000100000000000000
0000000000000000e803000018fcffff18fcffff000000000900000044726520
4b6f7a617206000000656e65726779000000004600000029010000c000000005
000000000000000100000001000000ffffffff01000000000000000000000000
0000000500000000000000000000006400000000000000200000001000000001
0000000000000000000000000000002b000000000000000000000000000000ff
ffffffe8030000000000000f0000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
00000001000000000000000000000000000000e803000018fcffff18fcffff00
0000000a0000004b6576696e2046697368060000006d616e7469730000000064
00000057000000e30000000f000000010000000100000001000000ffffffff01
0000000000000000000000010000000f00000000000000000000000000000000
0000002400000010000000010000000000000001000000000000002b00000000
0000000000000000000000ffffffffe8030000000000000f0000000000000000
0000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000001000000000000000000000000000000e8
03000018fcffff18fcffff00000000030000004f686d04000000656e67690000
000064000000920100009d00000002000000010000000100000001000000ffff
ffff000000000000000001000000020000000000000000000000000000000000
00002400000010000000010000000000000000000000000000002b0000000000
00000000000000000000ffffffffe8030000000000000f000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000001000000000000000000000000000000e803
000018fcffff18fcffff00000000030000005a617304000000656e6769000000
006400000092010000c000000003000000010000000100000001000000ffffff
ff00000000000000000100000003000000000000000000000000000000000000
002400000010000000010000000000000000000000000000002b000000000000
000000000000000000ffffffffe8030000000000000f00000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000001000000000000000000000000000000e80300
0018fcffff18fcffff00000000070000004d6f6e7376696b0500000068756d61
6e0000000064000000fb0100009d000000000000000000000001000000010000
00ffffffff020000000000000002000000000000000000000000000000070000
0000000000000000000000000000000000000000000100000000000000000000
000e00000019000000000000000000000000000000ffffffffe8030000000000
000f000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000001000000000000
000000000000000000e803000018fcffff18fcffff0000000019000000080000
0007000000000000000000000000000000000000000000000000000000000000
0000000000e80300000000000001000000080000000800000000000000000000
00000000000000000000000000000000000000000000000000e8030000000000
0001000000030000000100000000000000000000000000000000000000000000
00000000000000000000000000e8030000000000000100000008000000030000
0000000000000000000000000000000000000000000000000000000000000000
00e8030000000000000100000000000000000000000300000003000000000000
0000000000000000000000000000000000000000000000000000000000e80300
0000000000010000000300000003000000000000000000000000000000000000
0000000000000000000000000000000000e80300000000000001000000030000
0003000000000000000000000000000000000000000000000000000000000000
0000000000e80300000000000001000000030000000000000000000000000000
00000000000000000000000000000000000000000000000000e8030000000000
0001000000030000000300000000000000000000000000000000000000000000
00000000000000000000000000e8030000000000000100000000000000020000
0002000000000000000000000000000000000000000000000000000000000000
0000000000e80300000000000001000000030000000300000000000000000000
00000000000000000000000000000000000000000000000000e8030000000000
0001000000000000000300000000000000000000000000000000000000000000
0000000000000000000000000000000000e80300000000000001000000000000
00581b000018fcffff0000000000000000000000000400000005000000050000
000000000001000000e803000001000000e80300000000000000000000970f00
00a72105000000000000000000983a0000000000806400000000000000000000
00ffffffff0000000000000000ffffffff000000000100000064000000000000
0000000000ffffffff0000000000000000ffffffff0000000000000000ffffff
ff0000000000000000ffffffffffffffff040000006400000000000000000000
00ffffffff0000000000000000ffffffff010000000200000064000000000000
0000000000ffffffff0000000000000000ffffffff0100000000000000640000
000000000000000000ffffffff0000000000000000ffffffff00000000000000
00ffffffff0000000000000000ffffffffffffffff0400000064000000000000
0000000000ffffffff0000000000000000ffffffff0000000000000000ffffff
ff0000000000000000ffffffff00000000030000006400000000000000000000
00ffffffff0000000000000000ffffffffffffffff0400000064000000000000
0000000000ffffffff0000000000000000ffffffff0000000000000000ffffff
ff0000000000000000ffffffffffffffff040000006400000000000000000000
00ffffffff0000000000000000ffffffff0000000000000000ffffffff000000
0000000000ffffffffffffffff04000000640000000000000000000000ffffff
ff0000000000000000ffffffffffffffff040000006400000000000000000000
00ffffffff0000000000000000ffffffff0000000000000000ffffffff000000
0000000000ffffffff0100000002000000640000000000000000000000ffffff
ff0000000000000000ffffffffffffffff040000006400000000000000000000
00ffffffff0000000000000000ffffffffffffffff0400000064000000000000
0000000000ffffffff0000000000000000ffffffffffffffff04000000640000
000000000000000000ffffffff0000000000000000ffffffff00000000000000
00ffffffff0000000000000000ffffffff020000000000000064000000000000
0000000000ffffffff0000000000000000ffffffffffffffff04000000640000
000000000000000000ffffffff0000000000000000ffffffffffffffff040000
0000000000140000001400000014000000000000000000000003000000000000
0014000000140000001400000000000000000000000300000000000000140000
0014000000140000000000000000000000030000000000000014000000140000
0014000000000000000000000003000000000000001400000014000000140000
0000000000000000000300000000000000140000001400000014000000000000
0000000000030000000000000014000000140000001400000000000000000000
0003000000000000001400000014000000140000000000000000000000030000
0000000000140000001400000014000000000000000000000003000000000000
0014000000140000001400000000000000000000000300000000000000140000
0014000000140000000000000000000000030000000000000014000000140000
0014000000000000000000000003000000000000001400000014000000140000
0000000000000000000300000000000000140000001400000014000000000000
0000000000030000000000000014000000140000001400000000000000000000
0003000000000000001400000014000000140000000000000000000000030000
0000000000140000001400000014000000000000000000000003000000000000
0014000000140000001400000000000000000000000300000000000000140000
0014000000140000000000000000000000030000000000000014000000140000
0014000000000000000000000003000000000000001400000014000000140000
0000000000000000000300000000000000140000001400000014000000000000
0000000000030000000000000014000000140000001400000000000000000000
0003000000000000001400000014000000140000000000000000000000030000
0000000000140000001400000014000000000000000000000003000000000000
0014000000140000001400000000000000000000000300000000000000000000
00000000000400000010000000415254494c4c4552595f424f53535f31010000
0010000000415254494c4c4552595f424f53535f310100000010000000415254
494c4c4552595f424f53535f310100000010000000415254494c4c4552595f42
4f53535f310100000000000000030000000c0000004144565f5343414e4e4552
530d000000454e455247595f534849454c4410000000574541504f4e5f505245
49474e49544500000000fb480000f972000061fcffffa8000000000000000600
000000000000ffffffff00000000000000000000000000000000000000000000
0000000000001400000001000000010000000000000000000000010000000000
0000000000000000000001000000000000000000000001000000000000000000
0000010000000000000000000000000000000000000000000000050000000000
0000170000000000000001000000000000000000000000000000000000000100
00001700000073746172732f62675f6c6f6e656c79737461722e706e67180000
0073746172732f706c616e65745f626967626c75652e706e67d8000000bf0000
00b4000000010000000000000000000000000000000000000000000000010000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000001000000000000000000000000000000000000
0000000000010000000000000000000000000000000000000001000000170000
0073746172732f62675f64756c6c7374617273322e706e671b00000073746172
732f706c616e65745f6761735f79656c6c6f772e706e6767020000f1000000b4
0000000100000000000000000000000000000000000000000000000100000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000010000000000000000000000000000000000000000
0000000100000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000001
000000d57b00001d0000005049524154455f534c415645522073757272656e64
65722020313231390d0000005049524154455f4553434150451d000000504952
4154455f534c415645522064657374726f796564202031323233100000004445
41445f435245575f534c41564552000000000000000078000000596f75206272
6965666c7920636f6e736964657220636c6f6e696e672061207265706c616365
6d656e742c206275742064656369646520746f20726573706563742074686520
46656465726174696f6e206c61777320726567617264696e672073696d756c74
616e656f7573206475706c6963617465732efa2f000004000000000000000000
0000660000000000000001000000000000000c000000524f434b5f4649474854
5f501200000073686f756c64206e6f74206265207365656e11000000726f636b
5f66696768745f706972617465040000000500000068756d616e0b0000004368
726973746f7068205a04000000656e6769030000004b656e04000000726f636b
07000000426f6d6679204d04000000726f636b060000004465636c616e000000
000000000000000000000000000e00000010000000000000000a0000005a0200
00040000000b0000004368726973746f7068205a0500000068756d616e000000
0064000000570000003400000002000000000000000000000000000000ffffff
ff02000000000000000100000000000000ffffffffffffffff00000000000000
0000000000000000000000000000000000010000000000000000000000000000
0000000000000000000000000000000000ffffffffe8030000000000000f0000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000100000000000000000000
0000000000e8030000000000000000000000000000030000004b656e04000000
656e676900000000640000009d00000057000000040000000100000000000000
00000000ffffffff0000000000000000ffffffffffffffff0000000000000000
0000000000000000000000000000000001000000000000000000000000000000
00000000000000000000000000000000ffffffffe8030000000000000f000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000010000000000000000000000
00000000e803000000000000000000000000000007000000426f6d6679204d04
000000726f636b0000000096000000340000007a000000030000000300000000
00000000000000ffffffff010000000300000000000000ffffffffffffffff00
0000000000000000000000000000000000000000000000010000000000000000
0000000000000000000000000000000000000000000000ffffffffe803000000
0000000f00000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000100000000
0000000000000000000000e80300000000000000000000000000000600000044
65636c616e04000000726f636b000000009600000057000000c0000000060000
00010000000000000000000000ffffffff010000000100000000000000ffffff
ffffffffff000000000000000000000000000000000000000000000000010000
0000000000000000000000000000000000000000000000000000000000ffffff
ffe8030000000000000f00000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0001000000000000000000000000000000e80300000000000000000000000000
0011000000040000000400000000000000000000000000000000000000000000
00000000000000000000000000e8030000000000000100000004000000020000
0000000000000000000000000000000000000000000000000000000000000000
00e8030000000000000100000001000000010000000000000000000000000000
000000000000000000000000000000000000000000e803000000000000010000
0005000000000000000000000000000000000000000000000000000000000000
000000000000000000e803000000000000010000000000000000000000010000
0001000000000000000000000000000000000000000000000000000000000000
0000000000e80300000000000001000000000000000100000001000000000000
0000000000000000000000000000000000000000000000000000000000e80300
0000000000010000000000000003000000010000000000000000000000000000
000000000000000000000000000000000000000000e803000000000000010000
0000000000000000000000000000000000000000000200000000000000000000
0000000000000000000000000001000000e80300000000000000000000000000
0000000000000000000000000088130000000000006400000000000000000000
00ffffffff0000000000000000ffffffffffffffff0400000064000000000000
0000000000ffffffff0000000000000000ffffffff0100000003000000640000
000000000000000000ffffffff0000000000000000ffffffff00000000020000
00640000000000000000000000ffffffff0000000000000000ffffffff000000
0000000000ffffffff0000000000000000ffffffff0300000001000000640000
000000000000000000ffffffff0000000000000000ffffffff00000000000000
00ffffffff0000000000000000ffffffff010000000100000064000000000000
0000000000ffffffff0000000000000000ffffffffffffffff04000000640000
000000000000000000ffffffff0000000000000000ffffffff01000000010000
00640000000000000000000000ffffffff0000000000000000ffffffffffffff
ff04000000000000000400000004000000040000000000000000000000000000
0000000000040000000400000004000000000000000000000000000000000000
0004000000040000000400000000000000000000000000000000000000040000
0004000000040000000000000000000000000000000000000004000000040000
0004000000000000000000000000000000000000000400000004000000040000
0000000000000000000000000000000000040000000400000004000000000000
0000000000000000000000000004000000040000000400000000000000000000
0000000000000000000000000000000000030000000a0000004d495353494c45
535f32000000000d0000004c415345525f48454156595f31000000000d000000
4c415345525f42555253545f330000000000000000010000000a000000524f43
4b5f41524d4f520000000000000000000000000600000004000000983a000000
0000000000000000000000020000000000000000000000000000000200000000
00000000000000812000008109000000000000ffffffff010000000000000000
0000000000000010270000000000000000000000000000010000004865020069
e702004865020069e7020000350c0069e7020000000080000000800000008000
0000800000008000000080f40100000000000000000000485f03000000000058
a4feffffffff7f00000000000000000000000018fcffff000000000000000000
00000000000000000000000a00000000000000e8030000000000000000000048
65020049990200000000000000000000000000000000000000000000000000e8
030000000000000000000000000000000000000000000000000000e803000000
0000000000000004000000803e0000803e000000000000000000000000000001
0000000000000000000000010000000000000001000000010000000000000005
000000a0010000e80300000000000000000000e80300000000000000000000ff
ffffff00000000000000000000000000000000e803000018fcffff18fcffffff
ffffff00000000803e0000803e00000000000000000000000000000100000000
00000000000000010000000000000001000000010000000000000005000000a0
010000e80300000000000000000000e80300000000000000000000ffffffff00
000000000000000000000000000000e803000018fcffff18fcffffffffffff00
000000803e0000803e0000000000000000000000000000010000000000000000
000000010000000000000001000000010000000000000005000000a0010000e8
0300000000000000000000e80300000000000000000000ffffffff0000000000
0000000000000000000000e803000018fcffff18fcffffffffffff0000000080
3e0000803e000000000000000000000000000001000000000000000000000001
0000000000000001000000010000000000000005000000a0010000e803000000
00000000000000e80300000000000000000000ffffffff000000000000000000
00000000000000e803000018fcffff18fcffffffffffff000000000000000003
0000000000000010270000000000000000000000000000000000000000000000
0000000000000000000000ffffffff01000000000000000000000000000000e8
0300000000000000000000000000000000000000000000ffffffff0000000000
0000000000000000000000e803000018fcffff18fcffffffffffff0000000000
0000002823000000000000000000000000000000000000000000000000000000
00000000000000ffffffff01000000000000000000000000000000e803000000
00000000000000000000000000000000000000ffffffff000000000000000000
00000000000000e803000018fcffff18fcffffffffffff0000000000000000e0
2e00000000000000000000000000000000000000000000000000000000000000
000000ffffffff01000000000000000000000000000000e80300000000000000
000000000000000000000000000000ffffffff00000000000000000000000000
000000e803000018fcffff18fcffffffffffff00000000000000002000000000
000bc30100000000000000010000002e560000b63700000b0000000000000000
0000000000000000000000000000000000000000000000000000000000000001
00000000000000
[/code]
heres the code

**Comment by Vhati** [comment]
The editor can open two *different* kinds of files: profiles (ae_prof.sav or prof.sav) and savedgames (continue.sav). The former contain high scores and achievements. The latter track the state of the current campaign.

Note that you got a "Profile Parser Error" attempting to open a savedgame.
Choose the appropriate tab before clicking the "open" button.
