### ISSUE TITLE
SavedGame Parser Error

### ISSUE THREAD

**Issue by koumakpet** [Vhati/ftl-profile-editor#96]
FTL Profile Editor has detected that it cannot interpret your saved game correctly.

To submit a bug report, you can use GitHub (Signup is free).
Or post to the FTL forums here (Signup there is also free).

On GitHub, set the issue title as "SavedGame Parser Error".

I will fix the problem and release a new version as soon as I can.

Copy (Ctrl-A, Ctrl-C) the following text, including "[ code ] tags".

continue.sav:
[code]
0900000001000000000000000000000001000000000000000300000009000000
54686520546f72757312000000504c415945525f534849505f434952434c4501
000000000000000000000012000000504c415945525f534849505f434952434c
450900000054686520546f7275730e000000636972636c655f63727569736572
030000000500000068756d616e05000000426967627904000000656e67690400
00005461636804000000656e6769050000004d6172696101000000084c010000
000000000000001e000000100000000f000000000000001e0000000300000005
00000042696762790500000068756d616e000000006400000092010000060100
0008000000000000000100000000000000ffffffff0200000000000000000000
0000000000000000000800000000000000000000000000000000000000000000
0000000000010000000000000000000000000000000000000000000000000000
0000000000ffffffffe803000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
00000000000000000001000000000000000000000000000000e8030000000000
000000000000000000040000005461636804000000656e676900000000640000
007a0000000601000002000000020000000100000000000000ffffffff000000
0000000000020000000200000000000000000000000000000000000000000000
0000000000010000000000000000000000000000000000000000000000000000
0000000000ffffffffe803000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
00000000000000000001000000000000000000000000000000e8030000000000
000000000000000000050000004d6172696104000000656e6769000000006400
00006f0100007a0000000b000000010000000100000000000000ffffffff0000
000000000000010000000b000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
000000000000ffffffffe8030000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000001000000000000000000000000000000e80300000000
000000000000000000000a000000020000000200000000000000000000000000
00000000000000000000000000000000000000000000e8030000000000000100
0000020000000100000000000000000000000000000000000000000000000000
00000000000000000000e8030000000000000100000001000000010000000000
000000000000000000000000000000000000000000000000000000000000e803
0000000000000100000003000000000000000000000000000000000000000000
000000000000000000000000000000000000e803000000000000010000000300
0000000000000000000000000000000000000000000000000000000000000000
000000000000e803000000000000010000000100000001000000000000000000
0000000000000000000000000000000000000000000000000000e80300000000
0000010000000100000001000000000000000000000000000000000000000000
0000000000000000000000000000e80300000000000001000000010000000100
0000000000000000000000000000000000000000000000000000000000000000
0000e80300000000000001000000010000000100000000000000000000000000
00000000000000000000000000000000000000000000e8030000000000000100
0000000000000000000000000000000000000000000000000000000000000100
0000000000000000000000000000000000000000000001000000e80300000000
0000000000000000000000000000630000000000000000000000ffffffff0000
000000000000ffffffff0000000000000000ffffffff0000000000000000ffff
ffffffffffff04000000630000000000000000000000ffffffff000000000000
0000ffffffffffffffff04000000630000000000000000000000ffffffff0000
000000000000ffffffff0000000000000000ffffffff0000000000000000ffff
ffff0200000000000000630000000000000000000000ffffffff000000000000
0000ffffffff0000000000000000ffffffff0000000000000000ffffffff0000
000003000000630000000000000000000000ffffffff0000000000000000ffff
ffff0100000003000000630000000000000000000000ffffffff000000000000
0000ffffffff0000000001000000630000000000000000000000ffffffff0000
000000000000ffffffffffffffff04000000630000000000000000000000ffff
ffff0000000000000000ffffffff0000000000000000ffffffff000000000000
0000ffffffffffffffff04000000630000000000000000000000ffffffff0000
000000000000ffffffff0000000001000000630000000000000000000000ffff
ffff0000000000000000ffffffffffffffff0400000000000000000000000000
0000ffffffff0000000000000000ffffffffffffffff04000000630000000000
000000000000ffffffff0000000000000000ffffffff0000000000000000ffff
ffff0000000000000000ffffffff010000000200000063000000000000000000
0000ffffffff0000000000000000ffffffffffffffff04000000000000000000
000000000000ffffffff0000000000000000ffffffffffffffff040000006300
00000000000000000000ffffffff0000000000000000ffffffffffffffff0400
0000630000000000000000000000ffffffff0000000000000000ffffffffffff
ffff040000000000000004000000040000000400000001000000000000000000
0000000000000400000004000000040000000100000000000000000000000000
0000040000000400000004000000010000000000000000000000000000000400
0000040000000400000001000000000000000000000000000000040000000400
0000040000000100000000000000000000000000000004000000040000000400
0000010000000000000000000000000000000400000004000000040000000100
0000000000000000000000000000040000000400000004000000010000000000
0000000000000000000004000000040000000400000001000000000000000000
0000000000000400000004000000040000000100000000000000000000000000
0000040000000400000004000000010000000000000000000000000000000400
0000040000000400000001000000000000000000000000000000040000000400
0000040000000100000000000000000000000000000004000000040000000400
0000010000000000000000000000000000000400000004000000040000000100
0000000000000000000000000000040000000400000004000000010000000000
0000000000000000000004000000040000000400000001000000000000000000
0000000000000400000004000000040000000100000000000000000000000000
0000040000000400000004000000010000000000000000000000000000000400
0000040000000400000001000000000000000000000000000000040000000400
0000040000000100000000000000000000000000000004000000040000000400
0000010000000000000000000000000000000000000000000000010000000500
0000494f4e5f34000000000100000008000000434f4d4241545f310000000000
000000ffffffffffffffffffffffffffffffff01000000010000000b0000004e
414e4f5f4d454442415900000000583000005a67000041fcffffcb0000000000
00000000000000000000ffffffff000000000000000000000000000000000000
0000000000000000000014000000010000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
00000000000017000000010000001700000073746172732f62675f6c6f6e656c
79737461722e706e671600000073746172732f706c616e65745f62726f776e2e
706e67a002000071000000000000000100000000000000000000000000000000
0000000000000001000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000100000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000100000008
36000000000000000000001100000044455354524f5945445f44454641554c54
11000000444541445f435245575f44454641554c5400000000000000008f0100
00546865206461746120796f7520636172727920697320766974616c20746f20
7468652072656d61696e696e672046656465726174696f6e20666c6565742e20
596f75276c6c206e65656420737570706c69657320666f7220746865206a6f75
726e65792c20736f206d616b65207375726520746f206578706c6f7265206561
636820736563746f72206265666f7265206d6f76696e67206f6e20746f207468
65206e6578742e204275742067657420746f207468652065786974206265666f
726520746865207075727375696e6720526562656c20666c6565742063616e20
636174636820757021200a200a5449503a2045766173696f6e202d2020457661
64696e6720656e656d792073686f7473206973206372756369616c2c20627574
2069742072657175697265732066756e6374696f6e696e6720656e67696e6573
20414e4420612070696c6f742e20486176696e6720736f6d656f6e65206d616e
2074686520656e67696e65732077696c6c20696e63726561736520796f757220
65766173696f6e2061732077656c6c2effffffff010000000000000000000000
0000000000000000000000000200000000000000000000008a05000000000000
0000000000000000000000000000000000000000ffffffff0000008000000080
000000800000008018fcffff18fcffff00000080000000800000008000000080
000000800000008018fcffff00000000e8030000c05102000000000000000000
ffffff7f00000000000000000000000018fcffff000000000000000000000000
00000000000000000000000000000000e8030000000000000000000000000000
00000000e803000000000000000000000100000000000000a00f000000000000
00000000000000000000000000000000000000000000000000000000ffffffff
01000000000000000000000000000000e8030000000000000000000000000000
0000000000000000ffffffff00000000000000000000000000000000e8030000
18fcffff18fcffffffffffff0000000000000000200000000000000000000000
01000000307500000000000000000000
[/code]

**Comment by Vhati** [comment]
I'm afraid I can't reproduce the problem. I can turn that wall of text back into "continue.sav" at my end, and it opens successfully with the latest release of the editor (v25), using stock FTL 1.5.13 resources.

Did you have any mods installed later, which were not present when the savedgame was created? If the savedgame refers to resources that don't exist or are significantly different,, that can cause problems - both for the editor and the game.

**Comment by Vhati** [comment]
Otherwise, is there anything interesting in the log ("profile-editor-log.txt"). It can be found in the editor's folder.

**Comment by koumakpet** [comment]
It's ok I finded that I had only v20 editor that was problem now it works perfectly
