### ISSUE TITLE
SavedGame Parser Error

### ISSUE THREAD

**Issue by CorvetteCole** [Vhati/ftl-profile-editor#98]
[code]
SavedGame Parser Error

Exception: java.lang.RuntimeException: Not a bool: 2

Stack Trace...
  net.blerf.ftl.parser.Parser.readBool(Parser.java:21)
  net.blerf.ftl.parser.SavedGameParser.readSavedGame(SavedGameParser.java:84)
  net.blerf.ftl.ui.FTLFrame$11.actionPerformed(FTLFrame.java:802)
  javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
  javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)

Editor Version: 25
OS: Windows 8.1 6.3
VM: Java HotSpot(TM) 64-Bit Server VM, 1.7.0_80, amd64
[/code]

File ("ae_prof.sav")...
[code]
0900000002000000160000000c0000004143485f534543544f525f3501000000
0c0000004143485f534543544f525f38010000000c0000004143485f57494e5f
45415359010000000e0000004143485f57494e5f4e4f524d414c010000000d00
00004143485f4e4f5f524550414952010000000f0000004143485f4e4f5f4d49
5353494c4553010000000d0000004143485f4e4f5f44524f4e4553010000000c
0000004143485f4e4f5f4445415448010000000e0000004143485f534c494345
5f44494345010000000d0000004143485f535546464f43415445010000001500
00004143485f554e495445445f46454445524154494f4e020000001000000041
43485f46554c4c5f415253454e414c020000000e0000004143485f544f554748
5f5348495002000000120000004143485f454e455247595f534849454c445301
000000100000004143485f454e455247595f504f574552010000001000000041
43485f4645445f50415449454e434502000000110000004143485f4645445f44
49504c4f4d414359020000000f0000004143485f4645445f5550475241444501
000000130000004143485f4c414e4955535f414456414e434544010000001000
00004143485f4c414e4955535f53435241500100000017000000504c41594552
5f534849505f4645445f564943544f52590100000001000000ffffffffffffff
ff18000000504c415945525f534849505f454e455247595f5155455354000000
0001000000010000000100000000000000000000000000000001000000000000
0001000000000000000000000000000000000000000000000001000000000000
0000000000000000000100000000000000000000000000000000000000000000
00050000000a000000546865204f73707265790f000000504c415945525f5348
49505f464544800a000008000000010000000100000001000000080000005265
642d5461696c12000000504c415945525f534849505f484152445f3268090000
080000000000000001000000010000000f0000005468652041646a7564696361
746f7212000000504c415945525f534849505f454e4552475998050000080000
000000000000000000000000000b000000546865204b65737472656c10000000
504c415945525f534849505f484152441c050000060000000000000001000000
010000000900000054686520546f72757312000000504c415945525f53484950
5f434952434c4516040000050000000000000000000000000000000a0000000b
000000546865204b65737472656c10000000504c415945525f534849505f4841
52441c050000060000000000000001000000010000000b000000546865204b65
737472656c10000000504c415945525f534849505f484152446f030000060000
000000000000000000000000000b000000546865204b65737472656c10000000
504c415945525f534849505f4841524411030000050000000000000000000000
00000000080000005265642d5461696c12000000504c415945525f534849505f
484152445f326809000008000000000000000100000001000000090000005468
6520546f72757312000000504c415945525f534849505f434952434c45160400
00050000000000000000000000000000000900000054686520546f7275731200
0000504c415945525f534849505f434952434c45bb0300000600000000000000
00000000000000000900000054686520546f72757312000000504c415945525f
534849505f434952434c4565010000040000000000000000000000000000000a
000000546865204f73707265790f000000504c415945525f534849505f464544
800a0000080000000100000001000000010000000f0000005468652041646a75
64696361746f7212000000504c415945525f534849505f454e45524759980500
00080000000000000000000000000000000f0000005468652041646a75646963
61746f7212000000504c415945525f534849505f454e45524759310300000500
0000000000000000000000000000130000009b00000045000000780200007f04
0000b52100000a000000480000000e000000010000000f000000070000004d61
7877656c6c04000000656e6769010000000b0000000c00000054686f6d617320
426c6f636809000000616e6165726f626963010000008a0000000e0000005374
6576656e2044656e676c657206000000656e65726779010000004f0000000700
00004d61726b616e6409000000616e6165726f62696301000000020000000b00
00004a61636b2053686972616904000000656e676901000000
[/code]

**Comment by Vhati** [comment]
> SavedGame Parser Error
> 
> File ("ae_prof.sav")

"ae_prof.sav" is a profile, which contains high scores and achievements across campaigns.

Saved games are called "continue.sav".

Make sure you're in the appropriate tab before clicking the "open" button.

.

Sidenote: Avoid saves made during combat. There's a bug in the editor that causes corruption when writing a saved game that has certain projectiles/asteroids on the screen.

If you do run into that, there will still be a backup (*.bak) in the same folder, which you can rename to continue playing.
