### ISSUE TITLE
SavedGame Parser Error

### ISSUE THREAD

**Issue by CosmicSloth** [Vhati/ftl-profile-editor#99]
[code]
SavedGame Parser Error

Exception: java.lang.RuntimeException: Could not find blueprint for ship: 

Stack Trace...
  net.blerf.ftl.parser.SavedGameParser.readShip(SavedGameParser.java:420)
  net.blerf.ftl.parser.SavedGameParser.readSavedGame(SavedGameParser.java:129)
  net.blerf.ftl.ui.FTLFrame$11.actionPerformed(FTLFrame.java:802)
  javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
  javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)

Editor Version: 25
OS: Windows 10 10.0
VM: Java HotSpot(TM) Client VM, 1.8.0_131, x86
[/code]

File ("ae_prof.sav")...
[code]
0900000000000000000000000100000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000010000000b000000546865204b65737472656c10
000000504c415945525f534849505f484152441e000000010000000000000002
00000001000000010000000b000000546865204b65737472656c10000000504c
415945525f534849505f484152441e0000000100000000000000020000000100
0000000000000000000002000000020000000000000000000000030000000300
0000010000000000000000000000000000000000000001000000000000000000
0000000000000100000004000000090000004d6f7274726176656e0500000068
756d616e0100000001000000090000004d6f7274726176656e0500000068756d
616e0100000000000000000000000000000001000000
[/code]

**Comment by Vhati** [comment]
> SavedGame Parser Error
> 
> File ("ae_prof.sav")

"ae_prof.sav" is a profile, which contains high scores and achievements across campaigns.

Saved games are called "continue.sav".

Make sure you're in the appropriate tab before clicking the "open" button.

.

Sidenote: Avoid saves made during combat. There's a bug in the editor that causes corruption when writing a saved game that has certain projectiles/asteroids on the screen.

If you do run into that, there will still be a backup (*.bak) in the same folder, which you can rename to continue playing.
